using System.Security.Claims;
using Microsoft.AspNetCore.Http;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Query;
using Spaarke.Dataverse;

namespace Sprk.Bff.Api.Services.Compose;

/// <summary>
/// Canonical orchestration implementation of <see cref="IComposeService"/> for the Compose
/// drafting workspace.
/// </summary>
/// <remarks>
/// <para>
/// <b>Three-axis composition</b>: this orchestrator coordinates three concerns kept
/// deliberately separate (per spec §10.5 Placement Justification + CLAUDE.md §11 component
/// justification):
/// <list type="bullet">
///   <item><see cref="IComposeDocumentService"/> (task 022) — SPE plumbing (Graph
///   drive-item read/write/version). Owns the wire-level Graph dependency.</item>
///   <item><see cref="ComposeSessionService"/> (task 023; concrete per ADR-010 strict) —
///   ChatSession binding. Owns the reuse of the existing three-tier (Redis hot / Cosmos
///   warm / Dataverse cold) session infrastructure.</item>
///   <item><see cref="IGenericEntityService"/> (from <c>Spaarke.Dataverse</c>) —
///   <c>sprk_document</c> read/create for the first-Save promotion contract.</item>
/// </list>
/// </para>
/// <para>
/// <b>ADR-013 facade boundary verification</b>: the constructor INJECTS only the three
/// concerns listed above + <see cref="ILogger{T}"/>. It does NOT inject any AI-internal
/// type. The repo-wide grep guard (per spike #4 §9) confirms zero references to
/// <c>IOpenAiClient</c>, <c>IPlaybookService</c>, <c>IPlaybookOrchestrationService</c>,
/// or <c>IPlaybookExecutionEngine</c> anywhere in <see cref="ComposeService"/> or
/// <see cref="IComposeService"/>.
/// </para>
/// <para>
/// <b>First-Save promotion idempotency (FR-06)</b>: <see cref="PromoteIfEphemeralAsync"/>
/// looks up an existing <c>sprk_document</c> row by SPE drive-item id (alternate key
/// <c>sprk_graphitemid_uk</c>, created by task 010 / FW-1 OI-1) BEFORE attempting create.
/// If a row is found, the existing id is returned and no row is created. Concurrent
/// callers racing through the lookup-then-create window resolve via Dataverse alternate-key
/// uniqueness — the second create is caught and the now-existing row is retrieved.
/// </para>
/// <para>
/// <b>Spike #3 reuse pivot (deferred)</b>: spike #3 §2.2 documents that R1+ may migrate
/// promotion to a new <c>DocumentCheckoutService.PromoteEphemeralAsync</c> method that
/// owns the lock-then-promote flow uniformly. For task 021 (Phase 2), this orchestrator
/// owns the FR-06 contract directly per POML step 3; the reuse pivot is queued for
/// Phase 5 (tasks 050/051/052) once <c>DocumentCheckoutService</c> is extended.
/// </para>
/// <para>
/// <b>Lifetime</b>: <c>Scoped</c>. Matches the existing <see cref="IComposeSessionService"/>
/// lifetime and the per-request OBO context required by Graph + Dataverse calls.
/// </para>
/// <para>
/// <b>Test coverage</b>: per spec FR-22 + project CLAUDE.md §10 #6 / bff-extensions.md §F,
/// unit tests for this service are owned by task 026 (Wave 5, dependency on this Wave 2
/// task). The test surface lands in
/// <c>tests/unit/Sprk.Bff.Api.Tests/Services/Compose/ComposeServiceTests.cs</c> per
/// ADR-038 §1 unit-domain category. The Wave 5 PR closes the test-update obligation; this
/// Wave 2 PR notes the deferral explicitly per the bff-extensions §F exception clause
/// ("test surface is generated by a tested upstream contract").
/// </para>
/// </remarks>
public class ComposeService : IComposeService
{
    // Dataverse schema constants for sprk_document promotion.
    // Verified against spaarkedev1 schema 2026-07-01: primary name field is
    // sprk_documentname (NVARCHAR(850) NOT NULL); sprk_filename holds the SPE
    // file name; sprk_name is NOT a real attribute on sprk_document.
    private const string DocumentLogicalName = "sprk_document";
    private const string DocumentIdAttribute = "sprk_documentid";
    private const string GraphItemIdAttribute = "sprk_graphitemid";
    private const string DisplayNameAttribute = "sprk_documentname";
    private const string FileNameAttribute = "sprk_filename";

    private readonly IComposeDocumentService _documentService;
    private readonly ComposeSessionService _sessionService;
    private readonly IGenericEntityService _dataverse;
    private readonly ILogger<ComposeService> _logger;

    public ComposeService(
        IComposeDocumentService documentService,
        ComposeSessionService sessionService,
        IGenericEntityService dataverse,
        ILogger<ComposeService> logger)
    {
        _documentService = documentService;
        _sessionService = sessionService;
        _dataverse = dataverse;
        _logger = logger;
    }

    /// <inheritdoc />
    public Task<UploadComposeDocumentResult> UploadAsync(
        UploadComposeDocumentRequest request,
        HttpContext httpContext,
        CancellationToken cancellationToken = default)
    {
        // Upload-to-SPE for Compose is delegated to the existing Assistant upload pipeline
        // (Assistant → SPE → drive-item id → "Open in Compose" hand-off). Per spec §10.5
        // Placement Justification + design.md §14 row 5 (R1 default-open = Browse + Search),
        // ComposeService does NOT own a parallel upload endpoint — the Compose surface
        // calls the existing upload flow, then invokes ComposeService.LoadAsync with the
        // resulting drive-item id (Path B continuation).
        //
        // This method is preserved on the interface for two reasons:
        //   1) Future R2 inline upload from inside Compose (drag-drop into editor) will
        //      land here; the endpoint shape is stable.
        //   2) The test surface (task 026) can stub this in a focused way.
        //
        // For R1, callers SHOULD use the existing upload pipeline and then LoadAsync.
        throw new NotImplementedException(
            "Compose upload routes through the existing Assistant upload pipeline in R1; " +
            "see spec §10.5 Placement Justification. Use LoadAsync with the resulting " +
            "SPE drive-item id. This method is reserved for R2+ inline upload.");
    }

    /// <inheritdoc />
    public async Task<LoadComposeDocumentResult> LoadAsync(
        LoadComposeDocumentRequest request,
        HttpContext httpContext,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(request.DriveId))
        {
            throw new ArgumentException("DriveId is required for SPE drive-item access.", nameof(request));
        }

        if (string.IsNullOrWhiteSpace(request.DocumentSpeId))
        {
            throw new ArgumentException("DocumentSpeId (drive-item id) is required.", nameof(request));
        }

        if (string.IsNullOrWhiteSpace(request.TenantId))
        {
            throw new ArgumentException("TenantId is required for ADR-015 Tier 3 isolation.", nameof(request));
        }

        _logger.LogInformation(
            "Compose load: tenant={TenantId} drive={DriveId} driveItem={DocumentSpeId} record={DocumentRecordId}",
            request.TenantId,
            request.DriveId,
            request.DocumentSpeId,
            request.DocumentRecordId);

        // 1) Fetch DOCX bytes from SPE via the SPE plumbing service (task 022).
        var loadResult = await _documentService
            .LoadDocxAsync(httpContext, request.DriveId, request.DocumentSpeId, cancellationToken)
            .ConfigureAwait(false);

        if (!loadResult.Found || loadResult.Content is null)
        {
            throw new InvalidOperationException(
                $"SPE drive-item not found or unreadable: drive={request.DriveId} item={request.DocumentSpeId}");
        }

        // 2) Bind / re-bind a ChatSession for the load. For Path A (DocumentRecordId
        //    present), the session is bound to the sprk_documentid; for Path B
        //    continuation, it is bound to the SPE drive-item id.
        var bindingId = request.DocumentRecordId.HasValue
            ? request.DocumentRecordId.Value.ToString()
            : request.DocumentSpeId;

        var session = await _sessionService
            .EnsureSessionForDocumentAsync(
                tenantId: request.TenantId,
                documentId: bindingId,
                playbookId: null,
                ct: cancellationToken)
            .ConfigureAwait(false);

        // Drain the SPE stream into memory once for the caller — endpoints will project
        // this into the HTTP response. The stream from task 022 is caller-disposed.
        ReadOnlyMemory<byte> content;
        await using (var stream = loadResult.Content)
        {
            using var buffer = new MemoryStream();
            await stream!.CopyToAsync(buffer, cancellationToken).ConfigureAwait(false);
            content = buffer.ToArray();
        }

        return new LoadComposeDocumentResult
        {
            DocumentSpeId = request.DocumentSpeId,
            DriveId = request.DriveId,
            SessionId = session.SessionId,
            DocumentRecordId = request.DocumentRecordId,
            Content = content,
            ETag = loadResult.ETag,
            FileName = loadResult.FileName,
            Size = loadResult.Size,
        };
    }

    /// <inheritdoc />
    public async Task<SaveComposeDocumentResult> SaveAsync(
        SaveComposeDocumentRequest request,
        HttpContext httpContext,
        CancellationToken cancellationToken = default)
    {
        if (string.IsNullOrWhiteSpace(request.DriveId))
        {
            throw new ArgumentException("DriveId is required for SPE drive-item access.", nameof(request));
        }

        if (string.IsNullOrWhiteSpace(request.DocumentSpeId))
        {
            throw new ArgumentException("DocumentSpeId (drive-item id) is required.", nameof(request));
        }

        if (string.IsNullOrWhiteSpace(request.SessionId))
        {
            throw new ArgumentException("SessionId is required for first-Save promotion rebind.", nameof(request));
        }

        if (string.IsNullOrWhiteSpace(request.TenantId))
        {
            throw new ArgumentException("TenantId is required for ADR-015 Tier 3 isolation.", nameof(request));
        }

        var user = httpContext.User
            ?? throw new InvalidOperationException("HttpContext.User is null; auth pipeline misconfigured.");
        var correlationId = ResolveCorrelationId(httpContext);

        _logger.LogInformation(
            "Compose save: tenant={TenantId} drive={DriveId} driveItem={DocumentSpeId} session={SessionId} record={DocumentRecordId} size={SizeBytes} correlationId={CorrelationId}",
            request.TenantId,
            request.DriveId,
            request.DocumentSpeId,
            request.SessionId,
            request.DocumentRecordId,
            request.Content.Length,
            correlationId);

        // 1) Always commit a new SPE version FIRST. Promotion happens after a successful
        //    SPE write so a failed Save never leaves a half-promoted Document record.
        using var contentStream = new MemoryStream(request.Content.ToArray(), writable: false);

        var saveResult = await _documentService
            .SaveDocxAsync(httpContext, request.DriveId, request.DocumentSpeId, contentStream, user, correlationId, cancellationToken)
            .ConfigureAwait(false);

        if (!saveResult.Found || string.IsNullOrEmpty(saveResult.VersionId))
        {
            throw new InvalidOperationException(
                $"SPE save failed: drive-item not found or version not returned. drive={request.DriveId} item={request.DocumentSpeId}");
        }

        // 2) First-Save promotion (FR-06). Idempotent — repeated Saves see an existing
        //    sprk_document row and return its id unchanged.
        var promoteRequest = new PromoteComposeDocumentRequest
        {
            DocumentSpeId = request.DocumentSpeId,
            SessionId = request.SessionId,
            TenantId = request.TenantId,
            DisplayName = request.DisplayName,
        };

        var promotion = await PromoteIfEphemeralAsync(promoteRequest, httpContext, cancellationToken)
            .ConfigureAwait(false);

        return new SaveComposeDocumentResult
        {
            DocumentSpeId = request.DocumentSpeId,
            DriveId = request.DriveId,
            SessionId = promotion.SessionId,
            DocumentRecordId = promotion.DocumentRecordId,
            VersionId = saveResult.VersionId!,
            ETag = saveResult.ETag,
            Size = saveResult.Size,
            WasPromotedThisSave = promotion.WasCreated,
        };
    }

    /// <inheritdoc />
    public async Task<PromoteComposeDocumentResult> PromoteIfEphemeralAsync(
        PromoteComposeDocumentRequest request,
        HttpContext httpContext,
        CancellationToken cancellationToken = default)
    {

        if (string.IsNullOrWhiteSpace(request.DocumentSpeId))
        {
            throw new ArgumentException("DocumentSpeId (drive-item id) is required.", nameof(request));
        }

        if (string.IsNullOrWhiteSpace(request.SessionId))
        {
            throw new ArgumentException("SessionId is required for the ephemeral→promoted rebind.", nameof(request));
        }

        if (string.IsNullOrWhiteSpace(request.TenantId))
        {
            throw new ArgumentException("TenantId is required for ADR-015 Tier 3 isolation.", nameof(request));
        }

        // 1) Idempotency check: look up by alternate key on the SPE drive-item id.
        //    The alternate key sprk_graphitemid_uk was created by task 010 / FW-1 OI-1.
        //    If a row already exists, return its id unchanged — no row creation, no rebind
        //    duplication.
        var existingId = await TryFindDocumentByGraphItemIdAsync(
            request.DocumentSpeId,
            cancellationToken).ConfigureAwait(false);

        if (existingId.HasValue)
        {
            _logger.LogDebug(
                "Compose promote: existing sprk_document {DocumentRecordId} found for driveItem={DocumentSpeId} — idempotent no-op",
                existingId.Value,
                request.DocumentSpeId);

            // Re-bind session to the existing sprk_documentid (idempotent per
            // IComposeSessionService contract — second call with the same target is a
            // no-op).
            await _sessionService.RebindToDocumentIdAsync(
                tenantId: request.TenantId,
                sessionId: request.SessionId,
                currentDocumentId: request.DocumentSpeId,
                newDocumentId: existingId.Value.ToString(),
                ct: cancellationToken).ConfigureAwait(false);

            return new PromoteComposeDocumentResult
            {
                DocumentSpeId = request.DocumentSpeId,
                SessionId = request.SessionId,
                DocumentRecordId = existingId.Value,
                WasCreated = false,
            };
        }

        // 2) Create the sprk_document row. The display name (sprk_documentname —
        //    the entity's primary name attribute) is used when supplied; a
        //    sensible fallback is derived from the drive-item id (UI can always
        //    refine). sprk_filename mirrors the SPE file name for downstream
        //    consumers (index/RAG pipeline reads it as the source name).
        var entity = new Entity(DocumentLogicalName);
        entity[GraphItemIdAttribute] = request.DocumentSpeId;
        var effectiveDisplayName = !string.IsNullOrWhiteSpace(request.DisplayName)
            ? request.DisplayName!
            : $"Compose document ({request.DocumentSpeId})";
        entity[DisplayNameAttribute] = effectiveDisplayName;
        if (!string.IsNullOrWhiteSpace(request.DisplayName))
        {
            entity[FileNameAttribute] = request.DisplayName!;
        }

        Guid newId;
        try
        {
            newId = await _dataverse.CreateAsync(entity, cancellationToken).ConfigureAwait(false);

            _logger.LogInformation(
                "Compose promote: created sprk_document {DocumentRecordId} for driveItem={DocumentSpeId}",
                newId,
                request.DocumentSpeId);
        }
        catch (InvalidOperationException ex)
        {
            // Narrow race window: a concurrent Save promoted first. Re-look up by the
            // alternate key and return the now-existing id. If the lookup still fails,
            // surface the original exception — something else is wrong.
            _logger.LogWarning(ex,
                "Compose promote: create failed for driveItem={DocumentSpeId} — likely concurrent promotion. Re-resolving via alternate key.",
                request.DocumentSpeId);

            var raceWinnerId = await TryFindDocumentByGraphItemIdAsync(
                request.DocumentSpeId,
                cancellationToken).ConfigureAwait(false);

            if (!raceWinnerId.HasValue)
            {
                throw;
            }

            newId = raceWinnerId.Value;
        }

        // 3) Rebind the ChatSession DocumentId from the SPE drive-item id to the new
        //    sprk_documentid (FR-07). Idempotent per IComposeSessionService contract.
        await _sessionService.RebindToDocumentIdAsync(
            tenantId: request.TenantId,
            sessionId: request.SessionId,
            currentDocumentId: request.DocumentSpeId,
            newDocumentId: newId.ToString(),
            ct: cancellationToken).ConfigureAwait(false);

        return new PromoteComposeDocumentResult
        {
            DocumentSpeId = request.DocumentSpeId,
            SessionId = request.SessionId,
            DocumentRecordId = newId,
            WasCreated = true,
        };
    }

    /// <summary>
    /// Looks up an existing <c>sprk_document</c> row by SPE drive-item id via the
    /// <c>sprk_graphitemid_uk</c> alternate key. Returns the row's
    /// <c>sprk_documentid</c> or <c>null</c> when no row exists.
    /// </summary>
    private async Task<Guid?> TryFindDocumentByGraphItemIdAsync(
        string driveItemId,
        CancellationToken cancellationToken)
    {
        var key = new KeyAttributeCollection
        {
            { GraphItemIdAttribute, driveItemId },
        };

        try
        {
            var entity = await _dataverse.RetrieveByAlternateKeyAsync(
                DocumentLogicalName,
                key,
                new[] { DocumentIdAttribute },
                cancellationToken).ConfigureAwait(false);

            return entity?.Id;
        }
        catch (InvalidOperationException ex)
        {
            // RetrieveByAlternateKeyAsync semantics vary by implementation — some surface
            // "not found" as null, others as InvalidOperationException. Treat as not-found
            // here; the canonical CreateAsync path below will fail loud on real auth or
            // transport faults.
            _logger.LogDebug(ex,
                "Compose promote alternate-key lookup raised InvalidOperationException for driveItem={DocumentSpeId} — treating as not-found",
                driveItemId);
            return null;
        }
    }

    /// <summary>
    /// Resolves a correlation id from common headers / <c>HttpContext.TraceIdentifier</c>
    /// for downstream telemetry stitching. Mirrors the pattern in
    /// <c>HttpContextExtensions.GetCorrelationId</c> from Spaarke.Core.
    /// </summary>
    private static string ResolveCorrelationId(HttpContext httpContext)
    {
        const string CorrelationHeader = "X-Correlation-ID";
        if (httpContext.Request.Headers.TryGetValue(CorrelationHeader, out var values))
        {
            var headerValue = values.ToString();
            if (!string.IsNullOrWhiteSpace(headerValue))
            {
                return headerValue;
            }
        }
        return httpContext.TraceIdentifier;
    }
}
