// ─────────────────────────────────────────────────────────────────────────────
// Seed script — run with: npm run seed
// Idempotent: clears and re-seeds the database each time.
// ─────────────────────────────────────────────────────────────────────────────

import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  clearAll,
  upsertUser,
  insertApproval,
  insertRiskAssessment,
  insertAttachment,
  insertComment,
  insertAuditEvent,
  getDb,
} from "./db.js";
import { computeRisk } from "./risk.js";
import type {
  Approval,
  Attachment,
  Comment,
  AuditEvent,
  User,
} from "./types.js";

const __dirname = path.dirname(fileURLToPath(import.meta.url));

// ─────────────────────────────────────────────────────────────────────────────
// Sample users
// ─────────────────────────────────────────────────────────────────────────────

const USERS: User[] = [
  { id: "mgr_201", name: "Samantha Sandy",  email: "ssandy@company.com",    role: "approver"  },
  { id: "mgr_202", name: "Robert Kim",      email: "rkim@company.com",      role: "approver"  },
  { id: "mgr_203", name: "Lisa Chen",       email: "lchen@company.com",     role: "approver"  },
  { id: "mgr_204", name: "David Park",      email: "dpark@company.com",     role: "approver"  },
  { id: "usr_101", name: "John Azure",      email: "jazure@company.com",    role: "requester" },
  { id: "usr_102", name: "Maria Gomez",     email: "mgomez@company.com",    role: "requester" },
  { id: "usr_103", name: "Kevin Walsh",     email: "kwalsh@company.com",    role: "requester" },
  { id: "usr_104", name: "Sarah Williams",  email: "swilliams@company.com", role: "requester" },
  { id: "usr_105", name: "Tom Fletcher",    email: "tfletcher@company.com", role: "requester" },
  { id: "usr_106", name: "Priya Nair",      email: "pnair@company.com",     role: "requester" },
  { id: "adm_001", name: "Admin User",      email: "admin@company.com",     role: "admin"     },
];

// ─────────────────────────────────────────────────────────────────────────────
// Date helpers
// ─────────────────────────────────────────────────────────────────────────────

function daysAgo(n: number): string {
  return new Date(Date.now() - n * 86_400_000).toISOString();
}
function daysFromNow(n: number): string {
  return new Date(Date.now() + n * 86_400_000).toISOString();
}
function hoursAgo(n: number): string {
  return new Date(Date.now() - n * 3_600_000).toISOString();
}

// ─────────────────────────────────────────────────────────────────────────────
// Attachment text content (for .txt preview support)
// ─────────────────────────────────────────────────────────────────────────────

// ─────────────────────────────────────────────────────────────────────────────
// 55 sample approvals  (apr_1001 – apr_1055)
// ─────────────────────────────────────────────────────────────────────────────

const SEED_APPROVALS: Approval[] = [

  // ═══════════════════════════════════════════════════════════════════════════
  // PROMO PRICING  (7 total: apr_1001, 1002, 1003, 1019, 1025, 1026, 1027)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "apr_1001",
    title: "Activision InComm (MX) Campaign",
    type: "promo_pricing",
    display_type: "C2C Promo Pricing",
    status: "pending",
    risk_level: "medium",
    requester_id: "usr_101",
    requester_name: "John Azure",
    assignee_ids: ["mgr_201", "mgr_202"],
    submitted_at: daysAgo(2),
    due_at: daysFromNow(3),
    amount: 0,
    currency: "USD",
    country: "MEX",
    summary: "Promo pricing exception for Activision × InComm retail campaign in Mexico.",
    fields: [
      { label: "Publisher Name",      value: "Activision" },
      { label: "Retailer Name",       value: "InComm (MX)" },
      { label: "Country",             value: "MEX" },
      { label: "Campaign Start Date", value: "2026-04-01" },
      { label: "Campaign End Date",   value: "2026-04-15" },
      { label: "Discount %",          value: "20" },
    ],
    attachment_ids: ["att_001"],
    comment_ids:   ["com_001"],
    history_ids:   ["evt_001"],
    allowed_actions: [],
  },

  {
    id: "apr_1002",
    title: "EA Sports GameStop Summer Promo",
    type: "promo_pricing",
    display_type: "C2C Promo Pricing",
    status: "pending",
    risk_level: "low",
    requester_id: "usr_102",
    requester_name: "Maria Gomez",
    assignee_ids: ["mgr_201"],
    submitted_at: daysAgo(1),
    due_at: daysFromNow(7),
    amount: 0,
    currency: "USD",
    country: "USA",
    summary: "Standard summer promotional pricing for EA Sports titles at GameStop.",
    fields: [
      { label: "Publisher Name",      value: "EA Sports" },
      { label: "Retailer Name",       value: "GameStop" },
      { label: "Country",             value: "USA" },
      { label: "Campaign Start Date", value: "2026-06-01" },
      { label: "Campaign End Date",   value: "2026-06-30" },
      { label: "Discount %",          value: "15" },
    ],
    attachment_ids: ["att_002"],
    comment_ids:   [],
    history_ids:   ["evt_002"],
    allowed_actions: [],
  },

  {
    id: "apr_1003",
    title: "Ubisoft WalMart Pricing Exception",
    type: "promo_pricing",
    display_type: "C2C Promo Pricing",
    status: "pending",
    risk_level: "medium",
    requester_id: "usr_101",
    requester_name: "John Azure",
    assignee_ids: ["mgr_201", "mgr_202"],
    submitted_at: daysAgo(3),
    due_at: daysFromNow(1),
    amount: 0,
    currency: "USD",
    country: "USA",
    summary: "Pricing exception for Ubisoft titles at WalMart — 40% discount below standard MAP.",
    fields: [
      { label: "Publisher Name",      value: "Ubisoft" },
      { label: "Retailer Name",       value: "WalMart" },
      { label: "Country",             value: "USA" },
      { label: "Campaign Start Date", value: "2026-04-05" },
      { label: "Campaign End Date",   value: "2026-04-12" },
      { label: "Discount %",          value: "40" },
    ],
    attachment_ids: ["att_003"],
    comment_ids:   ["com_002"],
    history_ids:   ["evt_003", "evt_004"],
    allowed_actions: [],
  },

  {
    id: "apr_1019",
    title: "Nintendo × Target Spring Promo",
    type: "promo_pricing",
    display_type: "C2C Promo Pricing",
    status: "pending",
    risk_level: "low",
    requester_id: "usr_101",
    requester_name: "John Azure",
    assignee_ids: ["mgr_201"],
    submitted_at: daysAgo(1),
    due_at: daysFromNow(10),
    amount: 0,
    currency: "USD",
    country: "USA",
    summary: "Standard spring promotional pricing for Nintendo Switch titles at Target.",
    fields: [
      { label: "Publisher Name",      value: "Nintendo" },
      { label: "Retailer Name",       value: "Target" },
      { label: "Country",             value: "USA" },
      { label: "Campaign Start Date", value: "2026-04-10" },
      { label: "Campaign End Date",   value: "2026-04-20" },
      { label: "Discount %",          value: "10" },
    ],
    attachment_ids: ["att_019"],
    comment_ids:   [],
    history_ids:   ["evt_024"],
    allowed_actions: [],
  },

  {
    id: "apr_1025",
    title: "GameStop Q2 Holiday Promotion",
    type: "promo_pricing",
    display_type: "C2C Promo Pricing",
    status: "pending",
    risk_level: "medium",
    requester_id: "usr_101",
    requester_name: "John Azure",
    assignee_ids: ["mgr_201", "mgr_202"],
    submitted_at: daysAgo(2),
    due_at: daysFromNow(5),
    amount: 0,
    currency: "USD",
    country: "USA",
    summary: "Q2 holiday window promotional pricing across all GameStop locations in North America.",
    fields: [
      { label: "Publisher Name",      value: "Multiple Publishers" },
      { label: "Retailer Name",       value: "GameStop" },
      { label: "Country",             value: "USA" },
      { label: "Campaign Start Date", value: "2026-05-25" },
      { label: "Campaign End Date",   value: "2026-06-07" },
      { label: "Discount %",          value: "25" },
    ],
    attachment_ids: ["att_025"],
    comment_ids:   ["com_015"],
    history_ids:   ["evt_039"],
    allowed_actions: [],
  },

  {
    id: "apr_1026",
    title: "Sony PlayStation Best Buy Bundle Deal",
    type: "promo_pricing",
    display_type: "C2C Promo Pricing",
    status: "pending",
    risk_level: "high",
    requester_id: "usr_102",
    requester_name: "Maria Gomez",
    assignee_ids: ["mgr_201", "mgr_202", "mgr_203"],
    submitted_at: daysAgo(5),
    due_at: daysAgo(1), // overdue
    amount: 0,
    currency: "USD",
    country: "USA",
    summary: "Exclusive bundle pricing exception for Sony PlayStation hardware + game bundles at Best Buy — 35% below MSRP.",
    fields: [
      { label: "Publisher Name",      value: "Sony Interactive Entertainment" },
      { label: "Retailer Name",       value: "Best Buy" },
      { label: "Country",             value: "USA" },
      { label: "Campaign Start Date", value: "2026-04-01" },
      { label: "Campaign End Date",   value: "2026-04-30" },
      { label: "Discount %",          value: "35" },
    ],
    attachment_ids: ["att_026"],
    comment_ids:   ["com_016"],
    history_ids:   ["evt_040"],
    allowed_actions: [],
  },

  {
    id: "apr_1027",
    title: "2K Sports Amazon Prime Day Discount",
    type: "promo_pricing",
    display_type: "C2C Promo Pricing",
    status: "pending",
    risk_level: "low",
    requester_id: "usr_101",
    requester_name: "John Azure",
    assignee_ids: ["mgr_201"],
    submitted_at: daysAgo(1),
    due_at: daysFromNow(14),
    amount: 0,
    currency: "USD",
    country: "USA",
    summary: "Promotional discount for 2K Sports digital titles on Amazon Prime Day — standard digital clearance.",
    fields: [
      { label: "Publisher Name",      value: "2K Sports" },
      { label: "Retailer Name",       value: "Amazon" },
      { label: "Country",             value: "USA" },
      { label: "Campaign Start Date", value: "2026-07-14" },
      { label: "Campaign End Date",   value: "2026-07-15" },
      { label: "Discount %",          value: "18" },
    ],
    attachment_ids: [],
    comment_ids:   [],
    history_ids:   ["evt_041"],
    allowed_actions: [],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // PURCHASE ORDER  (12 total: apr_1004, 1005, 1006, 1020, 1028, 1029, 1030, 1051–1055)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "apr_1004",
    title: "Office Supplies Q2 Restock",
    type: "purchase_order",
    display_type: "Purchase Order",
    status: "pending",
    risk_level: "low",
    requester_id: "usr_103",
    requester_name: "Kevin Walsh",
    assignee_ids: ["mgr_201"],
    submitted_at: daysAgo(1),
    due_at: daysFromNow(5),
    amount: 529.20,
    currency: "USD",
    country: "USA",
    summary: "Routine Q2 office supply replenishment from Office Depot.",
    fields: [
      { label: "Vendor Name",             value: "Office Depot" },
      { label: "Amount",                  value: "529.20" },
      { label: "Currency",                value: "USD" },
      { label: "Business Justification",  value: "Q2 routine restock — stock below 2-week buffer" },
      { label: "Delivery Date",           value: "2026-03-25" },
    ],
    attachment_ids: ["att_004"],
    comment_ids:   [],
    history_ids:   ["evt_005"],
    allowed_actions: [],
  },

  {
    id: "apr_1005",
    title: "Cloud Infrastructure Annual Renewal",
    type: "purchase_order",
    display_type: "Purchase Order",
    status: "pending",
    risk_level: "medium",
    requester_id: "usr_103",
    requester_name: "Kevin Walsh",
    assignee_ids: ["mgr_201", "mgr_202"],
    submitted_at: daysAgo(4),
    due_at: daysFromNow(2),
    amount: 28_000,
    currency: "USD",
    country: "USA",
    summary: "Annual renewal for AWS enterprise support and reserved instance contracts.",
    fields: [
      { label: "Vendor Name",             value: "Amazon Web Services" },
      { label: "Amount",                  value: "28000" },
      { label: "Currency",                value: "USD" },
      { label: "Business Justification",  value: "Annual cloud infrastructure renewal — 12-month reserved instances for prod + staging" },
      { label: "Delivery Date",           value: "2026-04-01" },
    ],
    attachment_ids: ["att_005"],
    comment_ids:   ["com_003"],
    history_ids:   ["evt_006"],
    allowed_actions: [],
  },

  {
    id: "apr_1006",
    title: "Emergency Hardware Procurement",
    type: "purchase_order",
    display_type: "Purchase Order",
    status: "pending",
    risk_level: "high",
    requester_id: "usr_104",
    requester_name: "Sarah Williams",
    assignee_ids: ["mgr_201", "mgr_202"],
    submitted_at: hoursAgo(6),
    due_at: daysFromNow(1),
    amount: 78_500,
    currency: "USD",
    country: "USA",
    summary: "Emergency server hardware replacement following critical failure in production data center.",
    fields: [
      { label: "Vendor Name",             value: "Dell Technologies" },
      { label: "Amount",                  value: "78500" },
      { label: "Currency",                value: "USD" },
      { label: "Business Justification",  value: "Critical server failure in prod DC — replacement hardware needed within 24h to avoid SLA breach" },
      { label: "Delivery Date",           value: "2026-03-18" },
    ],
    attachment_ids: ["att_006"],
    comment_ids:   [],
    history_ids:   ["evt_007"],
    allowed_actions: [],
  },

  {
    id: "apr_1020",
    title: "Laptop Fleet Refresh — Engineering",
    type: "purchase_order",
    display_type: "Purchase Order",
    status: "pending",
    risk_level: "low",
    requester_id: "usr_103",
    requester_name: "Kevin Walsh",
    assignee_ids: ["mgr_201"],
    submitted_at: daysAgo(2),
    due_at: daysFromNow(10),
    amount: 22_000,
    currency: "USD",
    country: "USA",
    summary: "Standard 3-year laptop refresh cycle for 20 engineering laptops.",
    fields: [
      { label: "Vendor Name",             value: "Apple / CDW" },
      { label: "Amount",                  value: "22000" },
      { label: "Currency",                value: "USD" },
      { label: "Business Justification",  value: "20 laptops are 3+ years old. Standard refresh cycle per IT policy." },
      { label: "Delivery Date",           value: "2026-04-05" },
    ],
    attachment_ids: ["att_020"],
    comment_ids:   [],
    history_ids:   ["evt_020"],
    allowed_actions: [],
  },

  {
    id: "apr_1028",
    title: "AWS Annual Commit Renewal",
    type: "purchase_order",
    display_type: "Purchase Order",
    status: "pending",
    risk_level: "high",
    requester_id: "usr_103",
    requester_name: "Kevin Walsh",
    assignee_ids: ["mgr_201", "mgr_202", "mgr_203"],
    submitted_at: daysAgo(6),
    due_at: daysFromNow(0),
    amount: 220_000,
    currency: "USD",
    country: "USA",
    summary: "Annual AWS committed-use discount (CUD) renewal covering all production workloads — deadline today.",
    fields: [
      { label: "Vendor Name",             value: "Amazon Web Services" },
      { label: "Amount",                  value: "220000" },
      { label: "Currency",                value: "USD" },
      { label: "Business Justification",  value: "12-month CUD renewal for EC2, RDS, and S3 — 38% discount vs on-demand pricing. Failure to renew today triggers 30-day penalty window." },
      { label: "Delivery Date",           value: "2026-03-18" },
    ],
    attachment_ids: ["att_028"],
    comment_ids:   ["com_017"],
    history_ids:   ["evt_042", "evt_043"],
    allowed_actions: [],
  },

  {
    id: "apr_1029",
    title: "Summer Intern Hardware Batch",
    type: "purchase_order",
    display_type: "Purchase Order",
    status: "pending",
    risk_level: "low",
    requester_id: "usr_104",
    requester_name: "Sarah Williams",
    assignee_ids: ["mgr_201"],
    submitted_at: daysAgo(3),
    due_at: daysFromNow(12),
    amount: 12_000,
    currency: "USD",
    country: "USA",
    summary: "Purchase of 15 MacBook Airs for summer 2026 intern cohort starting June 1.",
    fields: [
      { label: "Vendor Name",             value: "Apple Business (via CDW)" },
      { label: "Amount",                  value: "12000" },
      { label: "Currency",                value: "USD" },
      { label: "Business Justification",  value: "15 interns joining June 1, 2026. Hardware must be ordered 6 weeks in advance per IT procurement SLA." },
      { label: "Delivery Date",           value: "2026-05-15" },
    ],
    attachment_ids: ["att_029"],
    comment_ids:   [],
    history_ids:   ["evt_044"],
    allowed_actions: [],
  },

  {
    id: "apr_1030",
    title: "Zoom Enterprise License Renewal",
    type: "purchase_order",
    display_type: "Purchase Order",
    status: "pending",
    risk_level: "medium",
    requester_id: "usr_103",
    requester_name: "Kevin Walsh",
    assignee_ids: ["mgr_201", "mgr_204"],
    submitted_at: daysAgo(2),
    due_at: daysFromNow(8),
    amount: 31_200,
    currency: "USD",
    country: "USA",
    summary: "Annual Zoom Enterprise license renewal for 400 seats, including Zoom Phone and Webinar add-ons.",
    fields: [
      { label: "Vendor Name",             value: "Zoom Video Communications" },
      { label: "Amount",                  value: "31200" },
      { label: "Currency",                value: "USD" },
      { label: "Business Justification",  value: "Standard annual renewal. 400 seats × $78/seat/year. Current license expires April 5, 2026." },
      { label: "Delivery Date",           value: "2026-04-05" },
    ],
    attachment_ids: [],
    comment_ids:   [],
    history_ids:   ["evt_045"],
    allowed_actions: [],
  },

  {
    id: "apr_1051",
    title: "Printer Toner & Consumables Q2",
    type: "purchase_order",
    display_type: "Purchase Order",
    status: "pending",
    risk_level: "low",
    requester_id: "usr_103",
    requester_name: "Kevin Walsh",
    assignee_ids: ["mgr_201"],
    submitted_at: daysAgo(1),
    due_at: daysFromNow(6),
    amount: 340,
    currency: "USD",
    country: "USA",
    summary: "Routine Q2 restock of printer toner cartridges and paper for the Chicago office.",
    fields: [
      { label: "Vendor Name",             value: "Staples Business Advantage" },
      { label: "Amount",                  value: "340" },
      { label: "Currency",                value: "USD" },
      { label: "Business Justification",  value: "Quarterly consumables restock. Stock below 1-week buffer." },
      { label: "Delivery Date",           value: "2026-04-01" },
    ],
    attachment_ids: ["att_051"],
    comment_ids:   [],
    history_ids:   ["evt_069"],
    allowed_actions: [],
  },

  {
    id: "apr_1052",
    title: "Conference Room Webcam Upgrade",
    type: "purchase_order",
    display_type: "Purchase Order",
    status: "pending",
    risk_level: "low",
    requester_id: "usr_104",
    requester_name: "Sarah Williams",
    assignee_ids: ["mgr_201"],
    submitted_at: daysAgo(2),
    due_at: daysFromNow(9),
    amount: 1_150,
    currency: "USD",
    country: "USA",
    summary: "Replace three aging conference room webcams with Logitech Rally Bar Minis for hybrid meeting quality.",
    fields: [
      { label: "Vendor Name",             value: "Logitech / B&H Photo" },
      { label: "Amount",                  value: "1150" },
      { label: "Currency",                value: "USD" },
      { label: "Business Justification",  value: "3 conference rooms have cameras with known video quality issues. Affects remote participant experience in daily stand-ups and client calls." },
      { label: "Delivery Date",           value: "2026-04-08" },
    ],
    attachment_ids: ["att_052"],
    comment_ids:   [],
    history_ids:   ["evt_070"],
    allowed_actions: [],
  },

  {
    id: "apr_1053",
    title: "Ergonomic Desk Accessories — Sales Team",
    type: "purchase_order",
    display_type: "Purchase Order",
    status: "pending",
    risk_level: "low",
    requester_id: "usr_106",
    requester_name: "Priya Nair",
    assignee_ids: ["mgr_201"],
    submitted_at: daysAgo(1),
    due_at: daysFromNow(11),
    amount: 870,
    currency: "USD",
    country: "USA",
    summary: "Ergonomic accessories (monitor stands, wrist rests, keyboard trays) for 10 sales team members returning to office.",
    fields: [
      { label: "Vendor Name",             value: "Ergotron / Amazon Business" },
      { label: "Amount",                  value: "870" },
      { label: "Currency",                value: "USD" },
      { label: "Business Justification",  value: "10 sales staff transitioning to hybrid schedule starting April 1. Ergonomic setup required per HR return-to-office policy." },
      { label: "Delivery Date",           value: "2026-03-28" },
    ],
    attachment_ids: ["att_053"],
    comment_ids:   [],
    history_ids:   ["evt_071"],
    allowed_actions: [],
  },

  {
    id: "apr_1054",
    title: "Slack Pro Seat Expansion — Q2",
    type: "purchase_order",
    display_type: "Purchase Order",
    status: "pending",
    risk_level: "low",
    requester_id: "usr_103",
    requester_name: "Kevin Walsh",
    assignee_ids: ["mgr_201"],
    submitted_at: daysAgo(3),
    due_at: daysFromNow(7),
    amount: 2_880,
    currency: "USD",
    country: "USA",
    summary: "Add 20 Slack Pro seats for the Q2 contractor and new-hire cohort.",
    fields: [
      { label: "Vendor Name",             value: "Slack Technologies" },
      { label: "Amount",                  value: "2880" },
      { label: "Currency",                value: "USD" },
      { label: "Business Justification",  value: "20 new contractors and hires joining Q2. Slack seats needed on day 1 for onboarding and project collaboration." },
      { label: "Delivery Date",           value: "2026-04-01" },
    ],
    attachment_ids: ["att_054"],
    comment_ids:   [],
    history_ids:   ["evt_072"],
    allowed_actions: [],
  },

  {
    id: "apr_1055",
    title: "Standing Desk Mats — Austin Office",
    type: "purchase_order",
    display_type: "Purchase Order",
    status: "pending",
    risk_level: "low",
    requester_id: "usr_105",
    requester_name: "Tom Fletcher",
    assignee_ids: ["mgr_201"],
    submitted_at: daysAgo(1),
    due_at: daysFromNow(14),
    amount: 480,
    currency: "USD",
    country: "USA",
    summary: "Anti-fatigue standing desk mats for 8 employees at the Austin office.",
    fields: [
      { label: "Vendor Name",             value: "Topo by Ergodriven / Amazon Business" },
      { label: "Amount",                  value: "480" },
      { label: "Currency",                value: "USD" },
      { label: "Business Justification",  value: "Austin team requested standing mats following ergonomic assessment in Feb 2026. Standard wellness purchase under $500/person." },
      { label: "Delivery Date",           value: "2026-04-10" },
    ],
    attachment_ids: ["att_055"],
    comment_ids:   [],
    history_ids:   ["evt_073"],
    allowed_actions: [],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CAPITAL EXPENDITURE (7 total: apr_1007, 1008, 1031, 1032, 1033, 1034, 1035)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "apr_1007",
    title: "Data Center UPS Replacement",
    type: "capex",
    display_type: "Capital Expenditure",
    status: "pending",
    risk_level: "medium",
    requester_id: "usr_103",
    requester_name: "Kevin Walsh",
    assignee_ids: ["mgr_201", "mgr_203"],
    submitted_at: daysAgo(5),
    due_at: daysFromNow(4),
    amount: 42_000,
    currency: "USD",
    country: "USA",
    summary: "Replace aging UPS units in primary data center to maintain uptime SLA.",
    fields: [
      { label: "Project Name",           value: "DC UPS Modernisation" },
      { label: "Amount",                 value: "42000" },
      { label: "Currency",               value: "USD" },
      { label: "Department",             value: "IT Infrastructure" },
      { label: "Expected ROI",           value: "Reduced downtime risk; avoid $200K SLA penalty exposure" },
      { label: "Business Justification", value: "Current UPS units are 8 years old and have had 2 partial failures in Q1 2026." },
    ],
    attachment_ids: ["att_007"],
    comment_ids:   [],
    history_ids:   ["evt_008"],
    allowed_actions: [],
  },

  {
    id: "apr_1008",
    title: "New Office Build-Out — Austin",
    type: "capex",
    display_type: "Capital Expenditure",
    status: "pending",
    risk_level: "high",
    requester_id: "usr_104",
    requester_name: "Sarah Williams",
    assignee_ids: ["mgr_201", "mgr_202", "mgr_203"],
    submitted_at: daysAgo(7),
    due_at: daysFromNow(0),
    amount: 380_000,
    currency: "USD",
    country: "USA",
    summary: "Capital expenditure for new Austin office build-out: fit-out, furniture, AV, and network.",
    fields: [
      { label: "Project Name",           value: "Austin Office Expansion" },
      { label: "Amount",                 value: "380000" },
      { label: "Currency",               value: "USD" },
      { label: "Department",             value: "Real Estate & Facilities" },
      { label: "Expected ROI",           value: "Supports 80-person headcount growth over 24 months" },
      { label: "Business Justification", value: "Current Austin lease expires April 2026; new space required for planned hiring. Board approved headcount plan attached." },
    ],
    attachment_ids: ["att_008"],
    comment_ids:   ["com_004"],
    history_ids:   ["evt_009", "evt_010"],
    allowed_actions: [],
  },

  {
    id: "apr_1031",
    title: "New York Office Renovation",
    type: "capex",
    display_type: "Capital Expenditure",
    status: "pending",
    risk_level: "high",
    requester_id: "usr_104",
    requester_name: "Sarah Williams",
    assignee_ids: ["mgr_201", "mgr_202", "mgr_203"],
    submitted_at: daysAgo(8),
    due_at: daysFromNow(6),
    amount: 175_000,
    currency: "USD",
    country: "USA",
    summary: "Renovation of New York HQ floors 12–14 to support hybrid work model with collaborative spaces.",
    fields: [
      { label: "Project Name",           value: "NYC HQ Hybrid Work Renovation" },
      { label: "Amount",                 value: "175000" },
      { label: "Currency",               value: "USD" },
      { label: "Department",             value: "Real Estate & Facilities" },
      { label: "Expected ROI",           value: "Supports 150-person hybrid model; reduces leased sq ft by 20%" },
      { label: "Business Justification", value: "Post-COVID space audit identified 40% underutilisation. Renovation redesigns floors for collaboration hubs and hot-desking." },
    ],
    attachment_ids: ["att_031_capex"],
    comment_ids:   ["com_018"],
    history_ids:   ["evt_046", "evt_047"],
    allowed_actions: [],
  },

  {
    id: "apr_1032",
    title: "Security Camera Upgrade — All Sites",
    type: "capex",
    display_type: "Capital Expenditure",
    status: "pending",
    risk_level: "medium",
    requester_id: "usr_103",
    requester_name: "Kevin Walsh",
    assignee_ids: ["mgr_201", "mgr_204"],
    submitted_at: daysAgo(4),
    due_at: daysFromNow(15),
    amount: 55_000,
    currency: "USD",
    country: "USA",
    summary: "Replace end-of-life CCTV systems across 6 office locations with IP-based HD cameras.",
    fields: [
      { label: "Project Name",           value: "Physical Security Modernisation" },
      { label: "Amount",                 value: "55000" },
      { label: "Currency",               value: "USD" },
      { label: "Department",             value: "Corporate Security" },
      { label: "Expected ROI",           value: "Compliance with SOC 2 Type II physical security controls" },
      { label: "Business Justification", value: "Existing cameras are analogue and failing. SOC 2 audit flagged as a finding in Q4 2025." },
    ],
    attachment_ids: [],
    comment_ids:   [],
    history_ids:   ["evt_048"],
    allowed_actions: [],
  },

  {
    id: "apr_1033",
    title: "EV Charging Station Installation",
    type: "capex",
    display_type: "Capital Expenditure",
    status: "pending",
    risk_level: "low",
    requester_id: "usr_106",
    requester_name: "Priya Nair",
    assignee_ids: ["mgr_201"],
    submitted_at: daysAgo(3),
    due_at: daysFromNow(21),
    amount: 18_500,
    currency: "USD",
    country: "USA",
    summary: "Install 10 Level-2 EV charging stations in HQ parking garage for employee use.",
    fields: [
      { label: "Project Name",           value: "HQ EV Charging Infrastructure" },
      { label: "Amount",                 value: "18500" },
      { label: "Currency",               value: "USD" },
      { label: "Department",             value: "Sustainability / Facilities" },
      { label: "Expected ROI",           value: "ESG benefit; supports company net-zero 2030 commitment" },
      { label: "Business Justification", value: "Employee survey: 42% own or plan to own an EV within 12 months. Current zero chargers on site." },
    ],
    attachment_ids: [],
    comment_ids:   [],
    history_ids:   ["evt_049"],
    allowed_actions: [],
  },

  {
    id: "apr_1034",
    title: "Network Infrastructure Upgrade — Chicago",
    type: "capex",
    display_type: "Capital Expenditure",
    status: "pending",
    risk_level: "medium",
    requester_id: "usr_103",
    requester_name: "Kevin Walsh",
    assignee_ids: ["mgr_201", "mgr_203"],
    submitted_at: daysAgo(5),
    due_at: daysFromNow(18),
    amount: 67_000,
    currency: "USD",
    country: "USA",
    summary: "Replace aging Cisco network switching and Wi-Fi 5 infrastructure in Chicago office with Wi-Fi 6E.",
    fields: [
      { label: "Project Name",           value: "Chicago Network Refresh 2026" },
      { label: "Amount",                 value: "67000" },
      { label: "Currency",               value: "USD" },
      { label: "Department",             value: "IT Infrastructure" },
      { label: "Expected ROI",           value: "3x throughput improvement; eliminates $24K/year in managed ISP premium" },
      { label: "Business Justification", value: "Chicago switches are 6 years old and no longer under vendor support. Bandwidth saturation occurring daily during peak hours." },
    ],
    attachment_ids: ["att_034"],
    comment_ids:   [],
    history_ids:   ["evt_050"],
    allowed_actions: [],
  },

  {
    id: "apr_1035",
    title: "Warehouse Racking System — Dallas",
    type: "capex",
    display_type: "Capital Expenditure",
    status: "pending",
    risk_level: "low",
    requester_id: "usr_106",
    requester_name: "Priya Nair",
    assignee_ids: ["mgr_201"],
    submitted_at: daysAgo(2),
    due_at: daysFromNow(28),
    amount: 34_000,
    currency: "USD",
    country: "USA",
    summary: "Install modular pallet racking in Dallas fulfilment warehouse to increase storage capacity by 30%.",
    fields: [
      { label: "Project Name",           value: "Dallas Warehouse Capacity Expansion" },
      { label: "Amount",                 value: "34000" },
      { label: "Currency",               value: "USD" },
      { label: "Department",             value: "Operations / Logistics" },
      { label: "Expected ROI",           value: "Avoids $8K/month 3PL overflow cost; 18-month payback" },
      { label: "Business Justification", value: "Q1 peak exceeded warehouse capacity by 22%. Racking expansion avoids costly 3PL overflow through Q3." },
    ],
    attachment_ids: [],
    comment_ids:   [],
    history_ids:   ["evt_051"],
    allowed_actions: [],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // CONTRACT / SOW  (7 total: apr_1009, 1010, 1011, 1036, 1037, 1038, 1039)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "apr_1009",
    title: "Freelance Design SOW — Q2 Campaign",
    type: "contract_sow",
    display_type: "Contract / SOW",
    status: "pending",
    risk_level: "low",
    requester_id: "usr_102",
    requester_name: "Maria Gomez",
    assignee_ids: ["mgr_201"],
    submitted_at: daysAgo(1),
    due_at: daysFromNow(6),
    amount: 4_800,
    currency: "USD",
    country: "USA",
    summary: "SOW with Alex Rivera Design Studio for Q2 marketing campaign assets.",
    fields: [
      { label: "Vendor / Agency Name", value: "Alex Rivera Design Studio" },
      { label: "Contract Value",       value: "4800" },
      { label: "Currency",             value: "USD" },
      { label: "Start Date",           value: "2026-03-15" },
      { label: "End Date",             value: "2026-04-30" },
      { label: "Scope Summary",        value: "Brand packaging refresh (5 SKUs), Q2 social assets, trade show booth design" },
    ],
    attachment_ids: ["att_009"],
    comment_ids:   [],
    history_ids:   ["evt_011"],
    allowed_actions: [],
  },

  {
    id: "apr_1010",
    title: "Marketing Agency Retainer Extension",
    type: "contract_sow",
    display_type: "Contract / SOW",
    status: "pending",
    risk_level: "medium",
    requester_id: "usr_102",
    requester_name: "Maria Gomez",
    assignee_ids: ["mgr_201", "mgr_203"],
    submitted_at: daysAgo(3),
    due_at: daysFromNow(5),
    amount: 24_000,
    currency: "USD",
    country: "USA",
    summary: "12-month extension of existing retainer with Ogilvy for brand and comms work.",
    fields: [
      { label: "Vendor / Agency Name", value: "Ogilvy & Mather" },
      { label: "Contract Value",       value: "24000" },
      { label: "Currency",             value: "USD" },
      { label: "Start Date",           value: "2026-04-01" },
      { label: "End Date",             value: "2027-03-31" },
      { label: "Scope Summary",        value: "Brand strategy, campaign creative, social media management — 12-month retainer at $2K/mo" },
    ],
    attachment_ids: ["att_010"],
    comment_ids:   ["com_005"],
    history_ids:   ["evt_012"],
    allowed_actions: [],
  },

  {
    id: "apr_1011",
    title: "Multi-Year Enterprise Software Agreement",
    type: "contract_sow",
    display_type: "Contract / SOW",
    status: "pending",
    risk_level: "high",
    requester_id: "usr_103",
    requester_name: "Kevin Walsh",
    assignee_ids: ["mgr_201", "mgr_202", "mgr_203"],
    submitted_at: daysAgo(6),
    due_at: daysFromNow(2),
    amount: 150_000,
    currency: "USD",
    country: "GBR",
    summary: "3-year enterprise license agreement with Salesforce UK including custom implementation.",
    fields: [
      { label: "Vendor / Agency Name", value: "Salesforce UK Ltd" },
      { label: "Contract Value",       value: "150000" },
      { label: "Currency",             value: "USD" },
      { label: "Start Date",           value: "2026-05-01" },
      { label: "End Date",             value: "2029-04-30" },
      { label: "Scope Summary",        value: "Enterprise CRM license (500 seats), custom integration SOW, 3-year Premier Support" },
    ],
    attachment_ids: ["att_011"],
    comment_ids:   ["com_006", "com_007"],
    history_ids:   ["evt_013", "evt_014"],
    allowed_actions: [],
  },

  {
    id: "apr_1036",
    title: "Salesforce CRM Expansion",
    type: "contract_sow",
    display_type: "Contract / SOW",
    status: "pending",
    risk_level: "medium",
    requester_id: "usr_102",
    requester_name: "Maria Gomez",
    assignee_ids: ["mgr_201", "mgr_203"],
    submitted_at: daysAgo(4),
    due_at: daysFromNow(9),
    amount: 95_000,
    currency: "USD",
    country: "USA",
    summary: "Expand Salesforce CRM from 200 to 450 seats and add Marketing Cloud Professional edition.",
    fields: [
      { label: "Vendor / Agency Name", value: "Salesforce Inc." },
      { label: "Contract Value",       value: "95000" },
      { label: "Currency",             value: "USD" },
      { label: "Start Date",           value: "2026-05-01" },
      { label: "End Date",             value: "2027-04-30" },
      { label: "Scope Summary",        value: "250 additional Sales Cloud seats, Marketing Cloud Professional, 12-month implementation support" },
    ],
    attachment_ids: ["att_036"],
    comment_ids:   ["com_019"],
    history_ids:   ["evt_052"],
    allowed_actions: [],
  },

  {
    id: "apr_1037",
    title: "IT Security Audit — Deloitte",
    type: "contract_sow",
    display_type: "Contract / SOW",
    status: "pending",
    risk_level: "low",
    requester_id: "usr_103",
    requester_name: "Kevin Walsh",
    assignee_ids: ["mgr_201"],
    submitted_at: daysAgo(2),
    due_at: daysFromNow(11),
    amount: 38_000,
    currency: "USD",
    country: "USA",
    summary: "Annual IT security audit and penetration testing engagement with Deloitte Cyber Risk.",
    fields: [
      { label: "Vendor / Agency Name", value: "Deloitte Cyber Risk Services" },
      { label: "Contract Value",       value: "38000" },
      { label: "Currency",             value: "USD" },
      { label: "Start Date",           value: "2026-04-15" },
      { label: "End Date",             value: "2026-06-30" },
      { label: "Scope Summary",        value: "SOC 2 readiness assessment, pen test (external + internal), cloud security review (AWS + Azure), remediation report" },
    ],
    attachment_ids: ["att_037"],
    comment_ids:   [],
    history_ids:   ["evt_053"],
    allowed_actions: [],
  },

  {
    id: "apr_1038",
    title: "PR Agency Annual Contract — APAC",
    type: "contract_sow",
    display_type: "Contract / SOW",
    status: "pending",
    risk_level: "medium",
    requester_id: "usr_102",
    requester_name: "Maria Gomez",
    assignee_ids: ["mgr_201", "mgr_202"],
    submitted_at: daysAgo(3),
    due_at: daysFromNow(7),
    amount: 72_000,
    currency: "USD",
    country: "AUS",
    summary: "12-month PR and communications retainer with Edelman APAC for Australia and Southeast Asia.",
    fields: [
      { label: "Vendor / Agency Name", value: "Edelman APAC" },
      { label: "Contract Value",       value: "72000" },
      { label: "Currency",             value: "USD" },
      { label: "Start Date",           value: "2026-04-01" },
      { label: "End Date",             value: "2027-03-31" },
      { label: "Scope Summary",        value: "Media relations, crisis comms, executive thought leadership — AUS, SGP, JPN markets" },
    ],
    attachment_ids: [],
    comment_ids:   ["com_020"],
    history_ids:   ["evt_054"],
    allowed_actions: [],
  },

  {
    id: "apr_1039",
    title: "Legal Counsel Retainer — Employment Law",
    type: "contract_sow",
    display_type: "Contract / SOW",
    status: "pending",
    risk_level: "low",
    requester_id: "usr_106",
    requester_name: "Priya Nair",
    assignee_ids: ["mgr_201"],
    submitted_at: daysAgo(1),
    due_at: daysFromNow(13),
    amount: 16_000,
    currency: "USD",
    country: "USA",
    summary: "Quarterly retainer for employment law advisory services with Wilson Sonsini.",
    fields: [
      { label: "Vendor / Agency Name", value: "Wilson Sonsini Goodrich & Rosati" },
      { label: "Contract Value",       value: "16000" },
      { label: "Currency",             value: "USD" },
      { label: "Start Date",           value: "2026-04-01" },
      { label: "End Date",             value: "2026-06-30" },
      { label: "Scope Summary",        value: "Q2 employment law advisory: offer letters, severance review, CA labor compliance" },
    ],
    attachment_ids: [],
    comment_ids:   [],
    history_ids:   ["evt_055"],
    allowed_actions: [],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // TRAVEL EXCEPTION  (7 total: apr_1012, 1013, 1014, 1040, 1041, 1042, 1043)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "apr_1012",
    title: "Domestic Conference — SalesForce World Tour",
    type: "travel_exception",
    display_type: "Travel Exception",
    status: "pending",
    risk_level: "low",
    requester_id: "usr_105",
    requester_name: "Tom Fletcher",
    assignee_ids: ["mgr_201"],
    submitted_at: daysAgo(1),
    due_at: daysFromNow(8),
    amount: 1_200,
    currency: "USD",
    country: "USA",
    summary: "Travel exception for SalesForce World Tour conference in NYC — slightly over $1K limit.",
    fields: [
      { label: "Traveler Name",          value: "Tom Fletcher" },
      { label: "Destination",            value: "New York, NY, USA" },
      { label: "Travel Dates",           value: "April 14–16, 2026" },
      { label: "Estimated Cost",         value: "1200" },
      { label: "Currency",               value: "USD" },
      { label: "Business Justification", value: "SalesForce World Tour is a key pipeline event. Last year we closed 2 enterprise deals from leads generated." },
      { label: "Policy Exception Reason", value: "Hotel costs in NYC during conference period exceed standard $200/night cap by ~20%" },
    ],
    attachment_ids: ["att_012"],
    comment_ids:   [],
    history_ids:   ["evt_015"],
    allowed_actions: [],
  },

  {
    id: "apr_1013",
    title: "International Sales Visit — Tokyo",
    type: "travel_exception",
    display_type: "Travel Exception",
    status: "pending",
    risk_level: "medium",
    requester_id: "usr_105",
    requester_name: "Tom Fletcher",
    assignee_ids: ["mgr_201", "mgr_202"],
    submitted_at: daysAgo(2),
    due_at: daysFromNow(4),
    amount: 3_800,
    currency: "USD",
    country: "JPN",
    summary: "International travel exception for key enterprise account meetings in Tokyo.",
    fields: [
      { label: "Traveler Name",          value: "Tom Fletcher" },
      { label: "Destination",            value: "Tokyo, Japan" },
      { label: "Travel Dates",           value: "April 20–25, 2026" },
      { label: "Estimated Cost",         value: "3800" },
      { label: "Currency",               value: "USD" },
      { label: "Business Justification", value: "In-person meetings with 3 enterprise prospects — $1.2M combined pipeline. Client requested on-site visit." },
      { label: "Policy Exception Reason", value: "International travel requires VP approval per policy T-2024-03" },
    ],
    attachment_ids: ["att_013"],
    comment_ids:   ["com_008"],
    history_ids:   ["evt_016"],
    allowed_actions: [],
  },

  {
    id: "apr_1014",
    title: "Executive Offsite — Napa Valley",
    type: "travel_exception",
    display_type: "Travel Exception",
    status: "pending",
    risk_level: "high",
    requester_id: "usr_104",
    requester_name: "Sarah Williams",
    assignee_ids: ["mgr_201", "mgr_202", "mgr_203"],
    submitted_at: daysAgo(4),
    due_at: hoursAgo(-8), // overdue
    amount: 9_500,
    currency: "USD",
    country: "USA",
    summary: "Q2 executive leadership offsite in Napa Valley — 15 attendees, 2 nights.",
    fields: [
      { label: "Traveler Name",          value: "Leadership Team (15 pax)" },
      { label: "Destination",            value: "Napa Valley, CA, USA" },
      { label: "Travel Dates",           value: "April 10–12, 2026" },
      { label: "Estimated Cost",         value: "9500" },
      { label: "Currency",               value: "USD" },
      { label: "Business Justification", value: "Annual exec strategy offsite — OKR planning and team alignment for H2 2026." },
      { label: "Policy Exception Reason", value: "Per-person cost of $633 significantly exceeds $300/night cap. Venue selected for privacy and facilitation quality." },
    ],
    attachment_ids: [],
    comment_ids:   ["com_009"],
    history_ids:   ["evt_017", "evt_018"],
    allowed_actions: [],
  },

  {
    id: "apr_1040",
    title: "Tokyo Sales Conference 2026",
    type: "travel_exception",
    display_type: "Travel Exception",
    status: "pending",
    risk_level: "high",
    requester_id: "usr_105",
    requester_name: "Tom Fletcher",
    assignee_ids: ["mgr_201", "mgr_202", "mgr_203"],
    submitted_at: daysAgo(5),
    due_at: daysAgo(2), // overdue
    amount: 45_000,
    currency: "USD",
    country: "JPN",
    summary: "Annual APAC sales conference in Tokyo — 20 attendees, 4 nights, including client entertainment.",
    fields: [
      { label: "Traveler Name",          value: "Sales Team APAC (20 pax)" },
      { label: "Destination",            value: "Tokyo, Japan" },
      { label: "Travel Dates",           value: "April 22–26, 2026" },
      { label: "Estimated Cost",         value: "45000" },
      { label: "Currency",               value: "USD" },
      { label: "Business Justification", value: "Annual APAC sales kickoff and key customer meetings. $8M ARR renewal discussions scheduled." },
      { label: "Policy Exception Reason", value: "Total spend significantly exceeds $5K international travel cap. Requires VP + CFO sign-off per policy INT-2025-01." },
    ],
    attachment_ids: ["att_040"],
    comment_ids:   ["com_021"],
    history_ids:   ["evt_056", "evt_057"],
    allowed_actions: [],
  },

  {
    id: "apr_1041",
    title: "Barcelona Design Sprint",
    type: "travel_exception",
    display_type: "Travel Exception",
    status: "pending",
    risk_level: "medium",
    requester_id: "usr_102",
    requester_name: "Maria Gomez",
    assignee_ids: ["mgr_201", "mgr_202"],
    submitted_at: daysAgo(3),
    due_at: daysFromNow(6),
    amount: 8_200,
    currency: "USD",
    country: "ESP",
    summary: "Travel for 4-person design team to client office in Barcelona for UX design sprint week.",
    fields: [
      { label: "Traveler Name",          value: "Design Team (4 pax)" },
      { label: "Destination",            value: "Barcelona, Spain" },
      { label: "Travel Dates",           value: "April 27 – May 2, 2026" },
      { label: "Estimated Cost",         value: "8200" },
      { label: "Currency",               value: "USD" },
      { label: "Business Justification", value: "Client (Ubisoft EU) requires on-site co-design sprint for Q3 project. Mandatory per contract SOW clause 4.2." },
      { label: "Policy Exception Reason", value: "International group travel over $5K requires VP approval" },
    ],
    attachment_ids: [],
    comment_ids:   [],
    history_ids:   ["evt_058"],
    allowed_actions: [],
  },

  {
    id: "apr_1042",
    title: "AWS re:Invent Conference — Las Vegas",
    type: "travel_exception",
    display_type: "Travel Exception",
    status: "pending",
    risk_level: "low",
    requester_id: "usr_103",
    requester_name: "Kevin Walsh",
    assignee_ids: ["mgr_201"],
    submitted_at: daysAgo(2),
    due_at: daysFromNow(22),
    amount: 2_400,
    currency: "USD",
    country: "USA",
    summary: "Travel exception for 2 engineers to attend AWS re:Invent in Las Vegas — hotel exceeds daily cap.",
    fields: [
      { label: "Traveler Name",          value: "Kevin Walsh + 1 engineer" },
      { label: "Destination",            value: "Las Vegas, NV, USA" },
      { label: "Travel Dates",           value: "May 18–22, 2026" },
      { label: "Estimated Cost",         value: "2400" },
      { label: "Currency",               value: "USD" },
      { label: "Business Justification", value: "AWS re:Invent is our most important cloud training event. Engineers attending will complete Solutions Architect certification track." },
      { label: "Policy Exception Reason", value: "Conference hotel rate ($290/night) exceeds $200/night domestic cap" },
    ],
    attachment_ids: [],
    comment_ids:   [],
    history_ids:   ["evt_059"],
    allowed_actions: [],
  },

  {
    id: "apr_1043",
    title: "London Finance Team Offsite",
    type: "travel_exception",
    display_type: "Travel Exception",
    status: "pending",
    risk_level: "medium",
    requester_id: "usr_106",
    requester_name: "Priya Nair",
    assignee_ids: ["mgr_201", "mgr_204"],
    submitted_at: daysAgo(2),
    due_at: daysFromNow(10),
    amount: 14_500,
    currency: "GBP",
    country: "GBR",
    summary: "Annual finance team offsite in London for H2 planning and compliance workshop — 8 attendees.",
    fields: [
      { label: "Traveler Name",          value: "Finance Team (8 pax)" },
      { label: "Destination",            value: "London, UK" },
      { label: "Travel Dates",           value: "May 5–7, 2026" },
      { label: "Estimated Cost",         value: "14500" },
      { label: "Currency",               value: "GBP" },
      { label: "Business Justification", value: "H2 2026 budget planning session and mandatory IFRS compliance training. 4 attendees travelling internationally." },
      { label: "Policy Exception Reason", value: "International group travel GBP amount converts above $15K USD threshold" },
    ],
    attachment_ids: ["att_043"],
    comment_ids:   [],
    history_ids:   ["evt_060"],
    allowed_actions: [],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MARKETING BUDGET  (8 total: apr_1015, 1016, 1044, 1045, 1046, 1047, 1048, 1049)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "apr_1015",
    title: "Q2 Paid Social Budget Increase",
    type: "marketing_budget",
    display_type: "Marketing Budget",
    status: "pending",
    risk_level: "medium",
    requester_id: "usr_102",
    requester_name: "Maria Gomez",
    assignee_ids: ["mgr_201", "mgr_203"],
    submitted_at: daysAgo(2),
    due_at: daysFromNow(3),
    amount: 18_000,
    currency: "USD",
    country: "USA",
    summary: "Request to increase Q2 paid social budget by $18K to capture high-intent spring gaming season.",
    fields: [
      { label: "Campaign Name",          value: "Spring Gaming Season 2026" },
      { label: "Budget Amount",          value: "18000" },
      { label: "Currency",               value: "USD" },
      { label: "Channel",                value: "Paid Social (Meta, TikTok)" },
      { label: "Quarter",                value: "Q2" },
      { label: "Business Justification", value: "Q1 ROAS was 4.2x. Spring window has historically 30% higher conversion. Increase will be self-funding within 6 weeks." },
    ],
    attachment_ids: ["att_015"],
    comment_ids:   [],
    history_ids:   ["evt_019"],
    allowed_actions: [],
  },

  {
    id: "apr_1016",
    title: "Unplanned Gaming Expo Sponsorship",
    type: "marketing_budget",
    display_type: "Marketing Budget",
    status: "pending",
    risk_level: "high",
    requester_id: "usr_102",
    requester_name: "Maria Gomez",
    assignee_ids: ["mgr_201", "mgr_202", "mgr_203"],
    submitted_at: daysAgo(1),
    due_at: daysFromNow(2),
    amount: 65_000,
    currency: "USD",
    country: "USA",
    summary: "Unplanned sponsorship commitment for Gaming Expo 2026 — deadline today for platinum tier.",
    fields: [
      { label: "Campaign Name",          value: "Gaming Expo 2026 Platinum Sponsorship" },
      { label: "Budget Amount",          value: "65000" },
      { label: "Currency",               value: "USD" },
      { label: "Channel",                value: "Events / Sponsorship" },
      { label: "Quarter",                value: "Q2" },
      { label: "Business Justification", value: "Platinum tier includes keynote slot and 100 sqft booth. Competitors are confirmed sponsors. Missing this could cede mindshare." },
    ],
    attachment_ids: ["att_016"],
    comment_ids:   ["com_010"],
    history_ids:   ["evt_021"],
    allowed_actions: [],
  },

  {
    id: "apr_1044",
    title: "Q2 Marketing Campaign — Paid Social",
    type: "marketing_budget",
    display_type: "Marketing Budget",
    status: "pending",
    risk_level: "medium",
    requester_id: "usr_102",
    requester_name: "Maria Gomez",
    assignee_ids: ["mgr_201", "mgr_203"],
    submitted_at: daysAgo(3),
    due_at: daysFromNow(7),
    amount: 42_000,
    currency: "USD",
    country: "USA",
    summary: "Q2 paid social media campaign across Meta, TikTok, and YouTube for new product launch.",
    fields: [
      { label: "Campaign Name",          value: "Q2 Product Launch — Paid Social" },
      { label: "Budget Amount",          value: "42000" },
      { label: "Currency",               value: "USD" },
      { label: "Channel",                value: "Paid Social (Meta, TikTok, YouTube)" },
      { label: "Quarter",                value: "Q2" },
      { label: "Business Justification", value: "New product launch targeting 18–34 demographic. Benchmarked CPM of $12 forecasts 3.5M impressions. Q1 ROAS benchmark: 4.1x." },
    ],
    attachment_ids: ["att_044"],
    comment_ids:   [],
    history_ids:   ["evt_061"],
    allowed_actions: [],
  },

  {
    id: "apr_1045",
    title: "Q2 Marketing Budget — Brand Awareness",
    type: "marketing_budget",
    display_type: "Marketing Budget",
    status: "pending",
    risk_level: "high",
    requester_id: "usr_102",
    requester_name: "Maria Gomez",
    assignee_ids: ["mgr_201", "mgr_202", "mgr_203"],
    submitted_at: daysAgo(5),
    due_at: daysAgo(1), // overdue
    amount: 85_000,
    currency: "USD",
    country: "USA",
    summary: "Q2 brand awareness campaign across TV, OOH, and digital — significant budget overrun vs plan.",
    fields: [
      { label: "Campaign Name",          value: "Q2 Brand Awareness Push" },
      { label: "Budget Amount",          value: "85000" },
      { label: "Currency",               value: "USD" },
      { label: "Channel",                value: "TV (cable), OOH (billboard), Digital Display" },
      { label: "Quarter",                value: "Q2" },
      { label: "Business Justification", value: "Brand health scores declined 8 points in Q1. Campaign required to halt erosion ahead of competitor launch in May. Exceeds $50K quarterly limit by $35K." },
    ],
    attachment_ids: ["att_045"],
    comment_ids:   ["com_022"],
    history_ids:   ["evt_062", "evt_063"],
    allowed_actions: [],
  },

  {
    id: "apr_1046",
    title: "Q3 Influencer Marketing Budget",
    type: "marketing_budget",
    display_type: "Marketing Budget",
    status: "pending",
    risk_level: "medium",
    requester_id: "usr_102",
    requester_name: "Maria Gomez",
    assignee_ids: ["mgr_201", "mgr_203"],
    submitted_at: daysAgo(2),
    due_at: daysFromNow(14),
    amount: 35_000,
    currency: "USD",
    country: "USA",
    summary: "Q3 influencer marketing program across Instagram and YouTube — 12 macro-influencers for gaming vertical.",
    fields: [
      { label: "Campaign Name",          value: "Q3 Gaming Influencer Program" },
      { label: "Budget Amount",          value: "35000" },
      { label: "Currency",               value: "USD" },
      { label: "Channel",                value: "Influencer (Instagram, YouTube)" },
      { label: "Quarter",                value: "Q3" },
      { label: "Business Justification", value: "Gaming influencer channel delivered 6.2x ROAS in Q2 2025 pilot. Scaling to 12 creators for sustained Q3 presence." },
    ],
    attachment_ids: [],
    comment_ids:   [],
    history_ids:   ["evt_064"],
    allowed_actions: [],
  },

  {
    id: "apr_1047",
    title: "E3 Trade Show Marketing Activation",
    type: "marketing_budget",
    display_type: "Marketing Budget",
    status: "pending",
    risk_level: "high",
    requester_id: "usr_102",
    requester_name: "Maria Gomez",
    assignee_ids: ["mgr_201", "mgr_202", "mgr_203"],
    submitted_at: daysAgo(6),
    due_at: daysFromNow(3),
    amount: 120_000,
    currency: "USD",
    country: "USA",
    summary: "E3 2026 trade show activation including booth build, demo stations, and press event — largest single event spend of year.",
    fields: [
      { label: "Campaign Name",          value: "E3 2026 — Main Hall Activation" },
      { label: "Budget Amount",          value: "120000" },
      { label: "Currency",               value: "USD" },
      { label: "Channel",                value: "Events / Trade Show" },
      { label: "Quarter",                value: "Q2" },
      { label: "Business Justification", value: "E3 is the most-watched gaming media event globally. Booth presence drives product visibility for Q3 launch. Last year's activation generated 450 press mentions." },
    ],
    attachment_ids: ["att_047"],
    comment_ids:   ["com_023"],
    history_ids:   ["evt_065"],
    allowed_actions: [],
  },

  {
    id: "apr_1048",
    title: "Holiday Season Digital Ad Spend",
    type: "marketing_budget",
    display_type: "Marketing Budget",
    status: "pending",
    risk_level: "medium",
    requester_id: "usr_102",
    requester_name: "Maria Gomez",
    assignee_ids: ["mgr_201", "mgr_203"],
    submitted_at: daysAgo(1),
    due_at: daysFromNow(25),
    amount: 28_000,
    currency: "USD",
    country: "USA",
    summary: "Pre-approved holiday season digital ad spend for Q4 campaign preparation — media buying reservation required now.",
    fields: [
      { label: "Campaign Name",          value: "Holiday Season 2026 — Digital" },
      { label: "Budget Amount",          value: "28000" },
      { label: "Currency",               value: "USD" },
      { label: "Channel",                value: "Paid Search (Google), Programmatic Display" },
      { label: "Quarter",                value: "Q4" },
      { label: "Business Justification", value: "Media inventory reservation required 6+ months ahead for Q4. Locking CPM rates now avoids 40% premium during peak period." },
    ],
    attachment_ids: [],
    comment_ids:   [],
    history_ids:   ["evt_066"],
    allowed_actions: [],
  },

  {
    id: "apr_1049",
    title: "Podcast Sponsorship — Gaming Culture Series",
    type: "marketing_budget",
    display_type: "Marketing Budget",
    status: "pending",
    risk_level: "low",
    requester_id: "usr_106",
    requester_name: "Priya Nair",
    assignee_ids: ["mgr_201"],
    submitted_at: daysAgo(1),
    due_at: daysFromNow(9),
    amount: 9_600,
    currency: "USD",
    country: "USA",
    summary: "3-month sponsorship of 'Level Up' podcast — top-5 gaming culture podcast, 180K weekly listeners.",
    fields: [
      { label: "Campaign Name",          value: "Level Up Podcast Sponsorship — Q2" },
      { label: "Budget Amount",          value: "9600" },
      { label: "Currency",               value: "USD" },
      { label: "Channel",                value: "Podcast / Audio" },
      { label: "Quarter",                value: "Q2" },
      { label: "Business Justification", value: "Podcast audience is 78% core gaming demographic (18–34M). CPM of $18 is below industry benchmark. 3-month host-read ad series." },
    ],
    attachment_ids: [],
    comment_ids:   [],
    history_ids:   ["evt_067"],
    allowed_actions: [],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // VENDOR ONBOARDING  (7 total: apr_1017, 1018, 1022, 1023, 1024, 1050, +1 below)
  // ═══════════════════════════════════════════════════════════════════════════

  {
    id: "apr_1017",
    title: "New Catering Supplier — HQ",
    type: "vendor_onboarding",
    display_type: "Vendor Onboarding",
    status: "pending",
    risk_level: "low",
    requester_id: "usr_103",
    requester_name: "Kevin Walsh",
    assignee_ids: ["mgr_201"],
    submitted_at: daysAgo(2),
    due_at: daysFromNow(9),
    amount: 18_000,
    currency: "USD",
    country: "USA",
    summary: "Onboard Fresh Harvest Catering as replacement for HQ office catering services.",
    fields: [
      { label: "Vendor Name",            value: "Fresh Harvest Catering Co." },
      { label: "Vendor Type",            value: "Supplier" },
      { label: "Annual Spend Estimate",  value: "18000" },
      { label: "Currency",               value: "USD" },
      { label: "Business Contact",       value: "Facilities Manager — Kevin Walsh" },
      { label: "Business Justification", value: "Current catering vendor contract ends March 31. Fresh Harvest won competitive RFP at 15% lower cost." },
    ],
    attachment_ids: ["att_017"],
    comment_ids:   [],
    history_ids:   ["evt_022"],
    allowed_actions: [],
  },

  {
    id: "apr_1018",
    title: "Offshore Development Agency Onboarding",
    type: "vendor_onboarding",
    display_type: "Vendor Onboarding",
    status: "pending",
    risk_level: "medium",
    requester_id: "usr_103",
    requester_name: "Kevin Walsh",
    assignee_ids: ["mgr_201", "mgr_202"],
    submitted_at: daysAgo(3),
    due_at: daysFromNow(6),
    amount: 240_000,
    currency: "USD",
    country: "IND",
    summary: "Onboard Infosys Digital Services as supplemental engineering capacity for Project Atlas.",
    fields: [
      { label: "Vendor Name",            value: "Infosys Digital Services" },
      { label: "Vendor Type",            value: "Contractor" },
      { label: "Annual Spend Estimate",  value: "240000" },
      { label: "Currency",               value: "USD" },
      { label: "Business Contact",       value: "VP Engineering — Kevin Walsh" },
      { label: "Business Justification", value: "Project Atlas requires 8 additional engineers for 12 months. Internal hiring timeline is 6 months. Offshore capacity bridges the gap." },
    ],
    attachment_ids: ["att_018"],
    comment_ids:   ["com_011"],
    history_ids:   ["evt_023"],
    allowed_actions: [],
  },

  {
    id: "apr_1022",
    title: "Acme Corp Vendor Onboarding",
    type: "vendor_onboarding",
    display_type: "Vendor Onboarding",
    status: "pending",
    risk_level: "medium",
    requester_id: "usr_102",
    requester_name: "Maria Gomez",
    assignee_ids: ["mgr_201", "mgr_204"],
    submitted_at: daysAgo(3),
    due_at: daysFromNow(7),
    amount: 120_000,
    currency: "USD",
    country: "USA",
    summary: "Onboard Acme Corp Solutions LLC as an approved ERP integration vendor for Project Mercury.",
    fields: [
      { label: "Vendor Name",            value: "Acme Corp Solutions LLC" },
      { label: "Vendor Type",            value: "Consultant" },
      { label: "Annual Spend Estimate",  value: "120000" },
      { label: "Currency",               value: "USD" },
      { label: "Business Contact",       value: "Procurement — Maria Gomez" },
      { label: "Business Justification", value: "Acme Corp is SAP-recommended integration partner. Pre-existing tech stack knowledge reduces project risk and onboarding time by ~3 months." },
    ],
    attachment_ids: ["att_031"],
    comment_ids:   ["com_012"],
    history_ids:   ["evt_031"],
    allowed_actions: [],
  },

  {
    id: "apr_1023",
    title: "Mexico City Retail Expansion",
    type: "vendor_onboarding",
    display_type: "Vendor Onboarding",
    status: "pending",
    risk_level: "low",
    requester_id: "usr_101",
    requester_name: "John Azure",
    assignee_ids: ["mgr_201"],
    submitted_at: daysAgo(2),
    due_at: daysFromNow(12),
    amount: 0,
    currency: "USD",
    country: "MEX",
    summary: "Onboard Grupo Coppel as regional retail distribution partner for Mexico City metro expansion.",
    fields: [
      { label: "Vendor Name",            value: "Grupo Coppel S.A. de C.V." },
      { label: "Vendor Type",            value: "Supplier" },
      { label: "Annual Spend Estimate",  value: "45000" },
      { label: "Currency",               value: "USD" },
      { label: "Business Contact",       value: "Channel Sales — John Azure" },
      { label: "Business Justification", value: "Coppel operates 1,400 stores in MX with strong gaming section. Adding as channel partner increases MX retail coverage by ~40%." },
    ],
    attachment_ids: [],
    comment_ids:   [],
    history_ids:   ["evt_032"],
    allowed_actions: [],
  },

  {
    id: "apr_1024",
    title: "Cloud Security Tooling — CrowdStrike",
    type: "vendor_onboarding",
    display_type: "Vendor Onboarding",
    status: "pending",
    risk_level: "high",
    requester_id: "usr_103",
    requester_name: "Kevin Walsh",
    assignee_ids: ["mgr_201", "mgr_202", "mgr_203"],
    submitted_at: daysAgo(4),
    due_at: daysFromNow(3),
    amount: 180_000,
    currency: "USD",
    country: "USA",
    summary: "Onboard CrowdStrike Falcon as enterprise EDR solution — replaces legacy AV across all endpoints.",
    fields: [
      { label: "Vendor Name",            value: "CrowdStrike Inc." },
      { label: "Vendor Type",            value: "Technology" },
      { label: "Annual Spend Estimate",  value: "180000" },
      { label: "Currency",               value: "USD" },
      { label: "Business Contact",       value: "CISO — Kevin Walsh" },
      { label: "Business Justification", value: "Current AV (Symantec) failed to detect 2 threat events in Q1 2026. CrowdStrike scored highest in Gartner evaluation. SOC 2 audit recommended replacement." },
    ],
    attachment_ids: ["att_024"],
    comment_ids:   ["com_013"],
    history_ids:   ["evt_033"],
    allowed_actions: [],
  },

  {
    id: "apr_1021",
    title: "Translation Services — Lionbridge",
    type: "vendor_onboarding",
    display_type: "Vendor Onboarding",
    status: "pending",
    risk_level: "low",
    requester_id: "usr_102",
    requester_name: "Maria Gomez",
    assignee_ids: ["mgr_201"],
    submitted_at: daysAgo(2),
    due_at: daysFromNow(16),
    amount: 0,
    currency: "USD",
    country: "USA",
    summary: "Onboard Lionbridge as approved localization and translation vendor for product packaging and digital content.",
    fields: [
      { label: "Vendor Name",            value: "Lionbridge Technologies" },
      { label: "Vendor Type",            value: "Agency" },
      { label: "Annual Spend Estimate",  value: "28000" },
      { label: "Currency",               value: "USD" },
      { label: "Business Contact",       value: "Marketing — Maria Gomez" },
      { label: "Business Justification", value: "Product expanding to 8 new markets in LATAM and EMEA. Lionbridge provides certified translation in 60 languages with gaming sector experience." },
    ],
    attachment_ids: [],
    comment_ids:   [],
    history_ids:   ["evt_030"],
    allowed_actions: [],
  },

  {
    id: "apr_1050",
    title: "Logistics Partner — APAC Fulfilment",
    type: "vendor_onboarding",
    display_type: "Vendor Onboarding",
    status: "pending",
    risk_level: "medium",
    requester_id: "usr_106",
    requester_name: "Priya Nair",
    assignee_ids: ["mgr_201", "mgr_202"],
    submitted_at: daysAgo(3),
    due_at: daysFromNow(11),
    amount: 95_000,
    currency: "USD",
    country: "SGP",
    summary: "Onboard DHL Supply Chain APAC as fulfilment partner for Singapore and Australia markets.",
    fields: [
      { label: "Vendor Name",            value: "DHL Supply Chain APAC" },
      { label: "Vendor Type",            value: "Supplier" },
      { label: "Annual Spend Estimate",  value: "95000" },
      { label: "Currency",               value: "USD" },
      { label: "Business Contact",       value: "Operations — Priya Nair" },
      { label: "Business Justification", value: "APAC expansion requires local 3PL partner. DHL has existing network in SGP, AUS, and NZL. Onboarding required 8 weeks before Q3 launch." },
    ],
    attachment_ids: [],
    comment_ids:   ["com_014"],
    history_ids:   ["evt_068"],
    allowed_actions: [],
  },

];

// ─────────────────────────────────────────────────────────────────────────────
// Attachments  (~25 of 50 approvals have attachments)
// ─────────────────────────────────────────────────────────────────────────────

const SEED_ATTACHMENTS: Attachment[] = [
  // Existing ─────────────────────────────────────────────────────────────────
  { id: "att_001",       approval_id: "apr_1001", name: "Activision_InComm_SOW.txt",          mime_type: "text/plain",                                                         size_bytes:    1_024, preview_supported: true,  storage_key: "attachments/att_001.txt"          },
  { id: "att_002",       approval_id: "apr_1002", name: "EA_GameStop_PromoSheet.pdf",          mime_type: "application/pdf",                                                    size_bytes:  245_760, preview_supported: false, storage_key: "attachments/att_002.pdf"          },
  { id: "att_003",       approval_id: "apr_1003", name: "Ubisoft_WalMart_Exception.pdf",       mime_type: "application/pdf",                                                    size_bytes:  189_440, preview_supported: false, storage_key: "attachments/att_003.pdf"          },
  { id: "att_004",       approval_id: "apr_1004", name: "OfficeSupplies_Q2_PO.txt",            mime_type: "text/plain",                                                         size_bytes:      892, preview_supported: true,  storage_key: "attachments/att_004.txt"          },
  { id: "att_005",       approval_id: "apr_1005", name: "AWS_Renewal_Quote.pdf",               mime_type: "application/pdf",                                                    size_bytes:  312_320, preview_supported: false, storage_key: "attachments/att_005.pdf"          },
  { id: "att_006",       approval_id: "apr_1006", name: "Dell_Emergency_Quote.pdf",            mime_type: "application/pdf",                                                    size_bytes:  156_672, preview_supported: false, storage_key: "attachments/att_006.pdf"          },
  { id: "att_007",       approval_id: "apr_1007", name: "UPS_Replacement_Spec.pdf",            mime_type: "application/pdf",                                                    size_bytes:  204_800, preview_supported: false, storage_key: "attachments/att_007.pdf"          },
  { id: "att_008",       approval_id: "apr_1008", name: "Austin_Office_Proposal.pdf",          mime_type: "application/pdf",                                                    size_bytes:  512_000, preview_supported: false, storage_key: "attachments/att_008.pdf"          },
  { id: "att_009",       approval_id: "apr_1009", name: "RiveraDesign_SOW.txt",                mime_type: "text/plain",                                                         size_bytes:    1_280, preview_supported: true,  storage_key: "attachments/att_009.txt"          },
  { id: "att_010",       approval_id: "apr_1010", name: "Ogilvy_RetainerExtension.pdf",        mime_type: "application/pdf",                                                    size_bytes:  278_528, preview_supported: false, storage_key: "attachments/att_010.pdf"          },
  { id: "att_011",       approval_id: "apr_1011", name: "Salesforce_MSA_Draft.pdf",            mime_type: "application/pdf",                                                    size_bytes: 1_048_576,preview_supported: false, storage_key: "attachments/att_011.pdf"          },
  { id: "att_012",       approval_id: "apr_1012", name: "SFWorldTour_Registration.pdf",        mime_type: "application/pdf",                                                    size_bytes:   98_304, preview_supported: false, storage_key: "attachments/att_012.pdf"          },
  { id: "att_013",       approval_id: "apr_1013", name: "Tokyo_TravelItinerary.pdf",           mime_type: "application/pdf",                                                    size_bytes:  143_360, preview_supported: false, storage_key: "attachments/att_013.pdf"          },
  { id: "att_015",       approval_id: "apr_1015", name: "Q2_PaidSocial_Plan.pdf",              mime_type: "application/pdf",                                                    size_bytes:  334_848, preview_supported: false, storage_key: "attachments/att_015.pdf"          },
  { id: "att_016",       approval_id: "apr_1016", name: "GamingExpo_SponsorDeck.pdf",          mime_type: "application/pdf",                                                    size_bytes: 2_097_152,preview_supported: false, storage_key: "attachments/att_016.pdf"          },
  { id: "att_017",       approval_id: "apr_1017", name: "FreshHarvest_Proposal.pdf",           mime_type: "application/pdf",                                                    size_bytes:  212_992, preview_supported: false, storage_key: "attachments/att_017.pdf"          },
  { id: "att_018",       approval_id: "apr_1018", name: "Infosys_NDA_and_MSA.pdf",             mime_type: "application/pdf",                                                    size_bytes:  655_360, preview_supported: false, storage_key: "attachments/att_018.pdf"          },
  { id: "att_019",       approval_id: "apr_1019", name: "Nintendo_Target_Promo.pdf",           mime_type: "application/pdf",                                                    size_bytes:  178_176, preview_supported: false, storage_key: "attachments/att_019.pdf"          },
  { id: "att_020",       approval_id: "apr_1020", name: "LaptopRefresh_Quote.pdf",             mime_type: "application/pdf",                                                    size_bytes:  122_880, preview_supported: false, storage_key: "attachments/att_020.pdf"          },
  // New ──────────────────────────────────────────────────────────────────────
  { id: "att_024",       approval_id: "apr_1024", name: "CrowdStrike_Proposal.pdf",            mime_type: "application/pdf",                                                    size_bytes:  450_560, preview_supported: false, storage_key: "attachments/att_024.pdf"          },
  { id: "att_025",       approval_id: "apr_1025", name: "GameStop_Q2Holiday_Terms.pdf",        mime_type: "application/pdf",                                                    size_bytes:  163_840, preview_supported: false, storage_key: "attachments/att_025.pdf"          },
  { id: "att_026",       approval_id: "apr_1026", name: "Sony_BestBuy_BundleDeal.pdf",         mime_type: "application/pdf",                                                    size_bytes:  286_720, preview_supported: false, storage_key: "attachments/att_026.pdf"          },
  { id: "att_028",       approval_id: "apr_1028", name: "AWS_CUD_Renewal_Contract.pdf",        mime_type: "application/pdf",                                                    size_bytes:  819_200, preview_supported: false, storage_key: "attachments/att_028.pdf"          },
  { id: "att_029",       approval_id: "apr_1029", name: "InternHardware_Batch_Quote.xlsx",
    mime_type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",              size_bytes:   45_056, preview_supported: false, storage_key: "attachments/att_029.xlsx"         },
  { id: "att_031",       approval_id: "apr_1022", name: "AcmeCorp_Onboarding_Packet.txt",      mime_type: "text/plain",                                                         size_bytes:    2_048, preview_supported: true,  storage_key: "attachments/att_031.txt"          },
  { id: "att_031_capex", approval_id: "apr_1031", name: "NYC_Renovation_Proposal.pdf",         mime_type: "application/pdf",                                                    size_bytes:  720_896, preview_supported: false, storage_key: "attachments/att_031_capex.pdf"    },
  { id: "att_034",       approval_id: "apr_1034", name: "Chicago_Network_BOM.xlsx",
    mime_type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",              size_bytes:   61_440, preview_supported: false, storage_key: "attachments/att_034.xlsx"         },
  { id: "att_036",       approval_id: "apr_1036", name: "Salesforce_Expansion_Quote.pdf",      mime_type: "application/pdf",                                                    size_bytes:  368_640, preview_supported: false, storage_key: "attachments/att_036.pdf"          },
  { id: "att_037",       approval_id: "apr_1037", name: "Deloitte_SecurityAudit_SOW.pdf",      mime_type: "application/pdf",                                                    size_bytes:  491_520, preview_supported: false, storage_key: "attachments/att_037.pdf"          },
  { id: "att_040",       approval_id: "apr_1040", name: "Tokyo_Conference_Itinerary.pdf",      mime_type: "application/pdf",                                                    size_bytes:  225_280, preview_supported: false, storage_key: "attachments/att_040.pdf"          },
  { id: "att_043",       approval_id: "apr_1043", name: "London_Offsite_Agenda.docx",
    mime_type: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",        size_bytes:   38_912, preview_supported: false, storage_key: "attachments/att_043.docx"         },
  { id: "att_044",       approval_id: "apr_1044", name: "Q2_PaidSocial_MediaPlan.xlsx",
    mime_type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",              size_bytes:   73_728, preview_supported: false, storage_key: "attachments/att_044.xlsx"         },
  { id: "att_045",       approval_id: "apr_1045", name: "Q2_BrandAwareness_Brief.pdf",         mime_type: "application/pdf",                                                    size_bytes:  557_056, preview_supported: false, storage_key: "attachments/att_045.pdf"          },
  { id: "att_047",       approval_id: "apr_1047", name: "E3_2026_ActivationDeck.pdf",          mime_type: "application/pdf",                                                    size_bytes: 3_145_728,preview_supported: false, storage_key: "attachments/att_047.pdf"          },
  // New low-risk PO attachments ────────────────────────────────────────────────
  { id: "att_051",       approval_id: "apr_1051", name: "Staples_Toner_Quote.pdf",              mime_type: "application/pdf",                                                    size_bytes:   32_768, preview_supported: false, storage_key: "attachments/att_051.pdf"          },
  { id: "att_052",       approval_id: "apr_1052", name: "Logitech_Webcam_Quote.pdf",            mime_type: "application/pdf",                                                    size_bytes:   41_984, preview_supported: false, storage_key: "attachments/att_052.pdf"          },
  { id: "att_053",       approval_id: "apr_1053", name: "Ergotron_DeskMats_Quote.pdf",          mime_type: "application/pdf",                                                    size_bytes:   28_672, preview_supported: false, storage_key: "attachments/att_053.pdf"          },
  { id: "att_054",       approval_id: "apr_1054", name: "Slack_Seat_Expansion_Order.pdf",       mime_type: "application/pdf",                                                    size_bytes:   36_864, preview_supported: false, storage_key: "attachments/att_054.pdf"          },
  { id: "att_055",       approval_id: "apr_1055", name: "Ergodriven_DeskMats_Quote.pdf",        mime_type: "application/pdf",                                                    size_bytes:   24_576, preview_supported: false, storage_key: "attachments/att_055.pdf"          },
];

// ─────────────────────────────────────────────────────────────────────────────
// Comments  (~15 approvals with comments)
// ─────────────────────────────────────────────────────────────────────────────

const SEED_COMMENTS: Comment[] = [
  // Existing ─────────────────────────────────────────────────────────────────
  { id: "com_001", approval_id: "apr_1001", author_id: "mgr_201", author_name: "Samantha Sandy", body: "Please confirm finance sign-off before we proceed.",                     created_at: daysAgo(1)    },
  { id: "com_002", approval_id: "apr_1003", author_id: "mgr_202", author_name: "Robert Kim",     body: "40% below MAP is very aggressive. Need additional justification.",        created_at: daysAgo(2)    },
  { id: "com_003", approval_id: "apr_1005", author_id: "mgr_202", author_name: "Robert Kim",     body: "Confirm reserved instance allocation aligns with capacity plan.",         created_at: daysAgo(3)    },
  { id: "com_004", approval_id: "apr_1008", author_id: "mgr_203", author_name: "Lisa Chen",      body: "Have we received the board resolution? Please attach.",                   created_at: daysAgo(5)    },
  { id: "com_005", approval_id: "apr_1010", author_id: "mgr_201", author_name: "Samantha Sandy", body: "Retainer extension looks reasonable given Q1 performance.",              created_at: daysAgo(2)    },
  { id: "com_006", approval_id: "apr_1011", author_id: "mgr_202", author_name: "Robert Kim",     body: "3-year commitment at this value needs CFO sign-off per policy.",         created_at: daysAgo(5)    },
  { id: "com_007", approval_id: "apr_1011", author_id: "mgr_201", author_name: "Samantha Sandy", body: "Legal is reviewing the UK data residency clauses.",                      created_at: daysAgo(3)    },
  { id: "com_008", approval_id: "apr_1013", author_id: "mgr_201", author_name: "Samantha Sandy", body: "Confirmed: VP approval granted verbally. Formalising here.",             created_at: daysAgo(1)    },
  { id: "com_009", approval_id: "apr_1014", author_id: "mgr_202", author_name: "Robert Kim",     body: "This is overdue. Approve or reject ASAP — venue deposit needed.",        created_at: hoursAgo(4)   },
  { id: "com_010", approval_id: "apr_1016", author_id: "mgr_203", author_name: "Lisa Chen",      body: "Deadline for platinum tier is March 19. Please decide quickly.",         created_at: daysAgo(1)    },
  { id: "com_011", approval_id: "apr_1018", author_id: "mgr_201", author_name: "Samantha Sandy", body: "InfoSec must review the data handling agreement before approval.",       created_at: daysAgo(2)    },
  // New ──────────────────────────────────────────────────────────────────────
  { id: "com_012", approval_id: "apr_1022", author_id: "mgr_204", author_name: "David Park",     body: "Acme Corp came through referral from SAP account team — good signal on technical fit.", created_at: daysAgo(2) },
  { id: "com_013", approval_id: "apr_1024", author_id: "mgr_202", author_name: "Robert Kim",     body: "CrowdStrike scored best-in-class in our Q1 bake-off. Recommend fast-tracking approval.", created_at: daysAgo(3) },
  { id: "com_014", approval_id: "apr_1050", author_id: "mgr_201", author_name: "Samantha Sandy", body: "Confirm DHL APAC data processing agreement covers AUS privacy requirements.", created_at: daysAgo(2) },
  { id: "com_015", approval_id: "apr_1025", author_id: "mgr_202", author_name: "Robert Kim",     body: "25% discount approved under standard holiday tier per pricing policy HP-2025-12.", created_at: daysAgo(1) },
  { id: "com_016", approval_id: "apr_1026", author_id: "mgr_201", author_name: "Samantha Sandy", body: "This is overdue — Best Buy deadline passed. Need resolution today.",      created_at: hoursAgo(8)   },
  { id: "com_017", approval_id: "apr_1028", author_id: "mgr_202", author_name: "Robert Kim",     body: "AWS sent final reminder — we lose the discount window at midnight tonight. Escalating to CFO.", created_at: hoursAgo(2) },
  { id: "com_018", approval_id: "apr_1031", author_id: "mgr_203", author_name: "Lisa Chen",      body: "Architect drawings are approved by building management. Proceed to contractor bid.", created_at: daysAgo(6) },
  { id: "com_019", approval_id: "apr_1036", author_id: "mgr_201", author_name: "Samantha Sandy", body: "Salesforce Exec sponsor confirmed 15% multi-year discount. Good deal — recommend approve.", created_at: daysAgo(3) },
  { id: "com_020", approval_id: "apr_1038", author_id: "mgr_202", author_name: "Robert Kim",     body: "Edelman performed well in ANZ market last year. Retainer terms look standard.", created_at: daysAgo(2) },
  { id: "com_021", approval_id: "apr_1040", author_id: "mgr_201", author_name: "Samantha Sandy", body: "This is already overdue — Tokyo deposits were due yesterday. Immediate decision needed.", created_at: hoursAgo(6) },
  { id: "com_022", approval_id: "apr_1045", author_id: "mgr_202", author_name: "Robert Kim",     body: "Brand health data confirms the urgency. However, $35K over cap requires CFO counter-sign.", created_at: daysAgo(4) },
  { id: "com_023", approval_id: "apr_1047", author_id: "mgr_203", author_name: "Lisa Chen",      body: "E3 booth design approved by Creative Director. Contractor bids attached separately.", created_at: daysAgo(5) },
];

// ─────────────────────────────────────────────────────────────────────────────
// Audit events
// ─────────────────────────────────────────────────────────────────────────────

function makeSubmitEvent(
  id: string,
  approvalId: string,
  actorId: string,
  actorName: string,
  ts: string,
): AuditEvent {
  return { id, approval_id: approvalId, actor_id: actorId, actor_name: actorName, action: "submitted", timestamp: ts };
}

const SEED_EVENTS: AuditEvent[] = [
  // Existing ─────────────────────────────────────────────────────────────────
  makeSubmitEvent("evt_001", "apr_1001", "usr_101", "John Azure",      daysAgo(2)),
  makeSubmitEvent("evt_002", "apr_1002", "usr_102", "Maria Gomez",     daysAgo(1)),
  makeSubmitEvent("evt_003", "apr_1003", "usr_101", "John Azure",      daysAgo(3)),
  { id: "evt_004", approval_id: "apr_1003", actor_id: "mgr_202", actor_name: "Robert Kim",     action: "commented", comment: "Needs more justification",        timestamp: daysAgo(2) },
  makeSubmitEvent("evt_005", "apr_1004", "usr_103", "Kevin Walsh",     daysAgo(1)),
  makeSubmitEvent("evt_006", "apr_1005", "usr_103", "Kevin Walsh",     daysAgo(4)),
  makeSubmitEvent("evt_007", "apr_1006", "usr_104", "Sarah Williams",  hoursAgo(6)),
  makeSubmitEvent("evt_008", "apr_1007", "usr_103", "Kevin Walsh",     daysAgo(5)),
  makeSubmitEvent("evt_009", "apr_1008", "usr_104", "Sarah Williams",  daysAgo(7)),
  { id: "evt_010", approval_id: "apr_1008", actor_id: "mgr_203", actor_name: "Lisa Chen",      action: "commented", comment: "Need board resolution attached",  timestamp: daysAgo(5) },
  makeSubmitEvent("evt_011", "apr_1009", "usr_102", "Maria Gomez",     daysAgo(1)),
  makeSubmitEvent("evt_012", "apr_1010", "usr_102", "Maria Gomez",     daysAgo(3)),
  makeSubmitEvent("evt_013", "apr_1011", "usr_103", "Kevin Walsh",     daysAgo(6)),
  { id: "evt_014", approval_id: "apr_1011", actor_id: "mgr_202", actor_name: "Robert Kim",     action: "commented", comment: "CFO sign-off required",           timestamp: daysAgo(5) },
  makeSubmitEvent("evt_015", "apr_1012", "usr_105", "Tom Fletcher",    daysAgo(1)),
  makeSubmitEvent("evt_016", "apr_1013", "usr_105", "Tom Fletcher",    daysAgo(2)),
  makeSubmitEvent("evt_017", "apr_1014", "usr_104", "Sarah Williams",  daysAgo(4)),
  { id: "evt_018", approval_id: "apr_1014", actor_id: "mgr_202", actor_name: "Robert Kim",     action: "commented", comment: "This is overdue — please decide", timestamp: hoursAgo(4) },
  makeSubmitEvent("evt_019", "apr_1015", "usr_102", "Maria Gomez",     daysAgo(2)),
  makeSubmitEvent("evt_020", "apr_1020", "usr_103", "Kevin Walsh",     daysAgo(2)),
  makeSubmitEvent("evt_021", "apr_1016", "usr_102", "Maria Gomez",     daysAgo(1)),
  makeSubmitEvent("evt_022", "apr_1017", "usr_103", "Kevin Walsh",     daysAgo(2)),
  makeSubmitEvent("evt_023", "apr_1018", "usr_103", "Kevin Walsh",     daysAgo(3)),
  makeSubmitEvent("evt_024", "apr_1019", "usr_101", "John Azure",      daysAgo(1)),
  // New ──────────────────────────────────────────────────────────────────────
  makeSubmitEvent("evt_030", "apr_1021", "usr_102", "Maria Gomez",     daysAgo(2)),
  makeSubmitEvent("evt_031", "apr_1022", "usr_102", "Maria Gomez",     daysAgo(3)),
  makeSubmitEvent("evt_032", "apr_1023", "usr_101", "John Azure",      daysAgo(2)),
  makeSubmitEvent("evt_033", "apr_1024", "usr_103", "Kevin Walsh",     daysAgo(4)),
  makeSubmitEvent("evt_039", "apr_1025", "usr_101", "John Azure",      daysAgo(2)),
  makeSubmitEvent("evt_040", "apr_1026", "usr_102", "Maria Gomez",     daysAgo(5)),
  { id: "evt_040b", approval_id: "apr_1026", actor_id: "mgr_201", actor_name: "Samantha Sandy", action: "commented", comment: "Overdue — Best Buy deadline passed", timestamp: hoursAgo(8) },
  makeSubmitEvent("evt_041", "apr_1027", "usr_101", "John Azure",      daysAgo(1)),
  makeSubmitEvent("evt_042", "apr_1028", "usr_103", "Kevin Walsh",     daysAgo(6)),
  { id: "evt_043", approval_id: "apr_1028", actor_id: "mgr_202", actor_name: "Robert Kim",     action: "commented", comment: "Escalating to CFO — expires midnight", timestamp: hoursAgo(2) },
  makeSubmitEvent("evt_044", "apr_1029", "usr_104", "Sarah Williams",  daysAgo(3)),
  makeSubmitEvent("evt_045", "apr_1030", "usr_103", "Kevin Walsh",     daysAgo(2)),
  makeSubmitEvent("evt_046", "apr_1031", "usr_104", "Sarah Williams",  daysAgo(8)),
  { id: "evt_047", approval_id: "apr_1031", actor_id: "mgr_203", actor_name: "Lisa Chen",      action: "commented", comment: "Architect drawings approved — proceed to bid", timestamp: daysAgo(6) },
  makeSubmitEvent("evt_048", "apr_1032", "usr_103", "Kevin Walsh",     daysAgo(4)),
  makeSubmitEvent("evt_049", "apr_1033", "usr_106", "Priya Nair",      daysAgo(3)),
  makeSubmitEvent("evt_050", "apr_1034", "usr_103", "Kevin Walsh",     daysAgo(5)),
  makeSubmitEvent("evt_051", "apr_1035", "usr_106", "Priya Nair",      daysAgo(2)),
  makeSubmitEvent("evt_052", "apr_1036", "usr_102", "Maria Gomez",     daysAgo(4)),
  makeSubmitEvent("evt_053", "apr_1037", "usr_103", "Kevin Walsh",     daysAgo(2)),
  makeSubmitEvent("evt_054", "apr_1038", "usr_102", "Maria Gomez",     daysAgo(3)),
  makeSubmitEvent("evt_055", "apr_1039", "usr_106", "Priya Nair",      daysAgo(1)),
  makeSubmitEvent("evt_056", "apr_1040", "usr_105", "Tom Fletcher",    daysAgo(5)),
  { id: "evt_057", approval_id: "apr_1040", actor_id: "mgr_201", actor_name: "Samantha Sandy", action: "commented", comment: "Overdue — Tokyo deposits due yesterday", timestamp: hoursAgo(6) },
  makeSubmitEvent("evt_058", "apr_1041", "usr_102", "Maria Gomez",     daysAgo(3)),
  makeSubmitEvent("evt_059", "apr_1042", "usr_103", "Kevin Walsh",     daysAgo(2)),
  makeSubmitEvent("evt_060", "apr_1043", "usr_106", "Priya Nair",      daysAgo(2)),
  makeSubmitEvent("evt_061", "apr_1044", "usr_102", "Maria Gomez",     daysAgo(3)),
  makeSubmitEvent("evt_062", "apr_1045", "usr_102", "Maria Gomez",     daysAgo(5)),
  { id: "evt_063", approval_id: "apr_1045", actor_id: "mgr_202", actor_name: "Robert Kim",     action: "commented", comment: "CFO counter-sign required for over-cap spend", timestamp: daysAgo(4) },
  makeSubmitEvent("evt_064", "apr_1046", "usr_102", "Maria Gomez",     daysAgo(2)),
  makeSubmitEvent("evt_065", "apr_1047", "usr_102", "Maria Gomez",     daysAgo(6)),
  makeSubmitEvent("evt_066", "apr_1048", "usr_102", "Maria Gomez",     daysAgo(1)),
  makeSubmitEvent("evt_067", "apr_1049", "usr_106", "Priya Nair",      daysAgo(1)),
  makeSubmitEvent("evt_068", "apr_1050", "usr_106", "Priya Nair",      daysAgo(3)),
  makeSubmitEvent("evt_069", "apr_1051", "usr_103", "Kevin Walsh",     daysAgo(1)),
  makeSubmitEvent("evt_070", "apr_1052", "usr_104", "Sarah Williams",  daysAgo(2)),
  makeSubmitEvent("evt_071", "apr_1053", "usr_106", "Priya Nair",      daysAgo(1)),
  makeSubmitEvent("evt_072", "apr_1054", "usr_103", "Kevin Walsh",     daysAgo(3)),
  makeSubmitEvent("evt_073", "apr_1055", "usr_105", "Tom Fletcher",    daysAgo(1)),
];

// ─────────────────────────────────────────────────────────────────────────────
// Write text attachment files to storage/
// ─────────────────────────────────────────────────────────────────────────────

// ─────────────────────────────────────────────────────────────────────────────
// Run seed
// ─────────────────────────────────────────────────────────────────────────────

export async function seedDatabase(): Promise<void> {
  console.log("Seeding approvals database...");
  console.log(`   Database: ${path.resolve(__dirname, "..", "approvals.db")}`);

  clearAll();
  console.log("  Cleared existing data");

  // Users
  for (const user of USERS) upsertUser(user);
  console.log(`  Inserted ${USERS.length} users`);

  // Approvals + risk assessments
  for (const approval of SEED_APPROVALS) {
    insertApproval(approval);
    const risk = computeRisk({
      id: approval.id,
      type: approval.type,
      amount: approval.amount,
      currency: approval.currency,
      country: approval.country,
      fields: approval.fields,
      attachment_ids: approval.attachment_ids,
      due_at: approval.due_at,
      summary: approval.summary,
    });
    insertRiskAssessment(risk);
    // Update the stored risk_level to match computed value
    getDb()
      .prepare("UPDATE approvals SET risk_level = ? WHERE id = ?")
      .run(risk.risk_level, approval.id);
  }
  console.log(`  Inserted ${SEED_APPROVALS.length} approvals with risk assessments`);

  // Attachments
  for (const att of SEED_ATTACHMENTS) insertAttachment(att);
  for (const att of SEED_ATTACHMENTS) {
    const row = getDb()
      .prepare("SELECT attachment_ids FROM approvals WHERE id = ?")
      .get(att.approval_id) as { attachment_ids: string } | undefined;
    if (row) {
      const ids: string[] = JSON.parse(row.attachment_ids);
      if (!ids.includes(att.id)) {
        ids.push(att.id);
        getDb()
          .prepare("UPDATE approvals SET attachment_ids = ? WHERE id = ?")
          .run(JSON.stringify(ids), att.approval_id);
      }
    }
  }
  console.log(`  Inserted ${SEED_ATTACHMENTS.length} attachments`);

  // Comments
  for (const comment of SEED_COMMENTS) insertComment(comment);
  for (const comment of SEED_COMMENTS) {
    const row = getDb()
      .prepare("SELECT comment_ids FROM approvals WHERE id = ?")
      .get(comment.approval_id) as { comment_ids: string } | undefined;
    if (row) {
      const ids: string[] = JSON.parse(row.comment_ids);
      if (!ids.includes(comment.id)) {
        ids.push(comment.id);
        getDb()
          .prepare("UPDATE approvals SET comment_ids = ? WHERE id = ?")
          .run(JSON.stringify(ids), comment.approval_id);
      }
    }
  }
  console.log(`  Inserted ${SEED_COMMENTS.length} comments`);

  // Audit events
  for (const event of SEED_EVENTS) insertAuditEvent(event);
  for (const event of SEED_EVENTS) {
    const row = getDb()
      .prepare("SELECT history_ids FROM approvals WHERE id = ?")
      .get(event.approval_id) as { history_ids: string } | undefined;
    if (row) {
      const ids: string[] = JSON.parse(row.history_ids);
      if (!ids.includes(event.id)) {
        ids.push(event.id);
        getDb()
          .prepare("UPDATE approvals SET history_ids = ? WHERE id = ?")
          .run(JSON.stringify(ids), event.approval_id);
      }
    }
  }
  console.log(`  Inserted ${SEED_EVENTS.length} audit events`);

  // Print summary
  const db = getDb();
  const counts     = db.prepare("SELECT status,     COUNT(*) as n FROM approvals GROUP BY status")    .all() as { status: string;     n: number }[];
  const riskCounts = db.prepare("SELECT risk_level, COUNT(*) as n FROM approvals GROUP BY risk_level").all() as { risk_level: string; n: number }[];
  const totalAmt   = (db.prepare("SELECT COALESCE(SUM(amount),0) as total FROM approvals WHERE status='pending'").get() as { total: number }).total;

  console.log("\nSeed summary:");
  console.log("  Status:", counts.map((c) => `${c.status}: ${c.n}`).join(", "));
  console.log("  Risk:  ", riskCounts.map((c) => `${c.risk_level}: ${c.n}`).join(", "));
  console.log(`  Total pending amount: $${totalAmt.toLocaleString("en-US", { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`);
  console.log("\nSeed complete.\n");
}

// Only auto-execute when run directly (not when imported by index.ts)
if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  seedDatabase().catch((err) => {
    console.error("Seed failed:", err);
    process.exit(1);
  });
}
