namespace Sprk.Bff.Api.Api.Workspace.Models;

/// <summary>
/// Summary of the top-priority matter for inclusion in the briefing response.
/// </summary>
/// <param name="MatterId">Dataverse sprk_matter record ID.</param>
/// <param name="Name">Display name of the matter.</param>
/// <param name="Deadline">Next key deadline for the matter (null if unknown).</param>
/// <param name="Reason">Human-readable reason this matter is the top priority (e.g., "Highest priority score").</param>
public record TopMatterSummary(
    Guid MatterId,
    string Name,
    DateTimeOffset? Deadline,
    string Reason);

/// <summary>
/// Response DTO for the GET /api/workspace/briefing endpoint.
/// Contains structured deterministic metrics (always present) and an optional AI-enhanced narrative.
/// </summary>
/// <param name="ActiveMatters">Count of matters with an active/open status.</param>
/// <param name="TotalSpend">Sum of all invoiced amounts across active matters.</param>
/// <param name="TotalBudget">Sum of all budget amounts across active matters.</param>
/// <param name="UtilizationPercent">Portfolio-level spend / budget expressed as a percentage (0 when budget is 0).</param>
/// <param name="MattersAtRisk">Count of matters where overdueeventcount &gt; 0 or utilization &gt; 85%.</param>
/// <param name="OverdueEvents">Total count of overdue events across all active matters.</param>
/// <param name="TopPriorityMatter">The highest-priority active matter; null when there are no active matters.</param>
/// <param name="Narrative">
/// Natural-language briefing paragraph. Template-based by default; AI-enhanced when
/// <see cref="IsAiEnhanced"/> is true.
/// </param>
/// <param name="IsAiEnhanced">
/// True when the narrative was generated by the AI (PlaybookService); false when it is template-based.
/// </param>
/// <param name="GeneratedAt">UTC timestamp when this briefing was generated and cached.</param>
public record BriefingResponse(
    int ActiveMatters,
    decimal TotalSpend,
    decimal TotalBudget,
    double UtilizationPercent,
    int MattersAtRisk,
    int OverdueEvents,
    TopMatterSummary? TopPriorityMatter,
    string Narrative,
    bool IsAiEnhanced,
    DateTimeOffset GeneratedAt);
