using System.Diagnostics;
using System.Globalization;
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.Json;
using Microsoft.Extensions.Options;
using Sprk.Bff.Api.Api.Insights;
using Sprk.Bff.Api.Models.Ai;
using Sprk.Bff.Api.Models.Ai.PublicContracts;
using Sprk.Bff.Api.Models.Insights;
using Sprk.Bff.Api.Services.Ai.Insights.Ingest;
using Sprk.Bff.Api.Services.Ai.Insights.Nodes;
using Sprk.Bff.Api.Services.Ai.PublicContracts;

namespace Sprk.Bff.Api.Services.Ai.Insights;

/// <summary>
/// Phase 1.5 Zone A implementation of <see cref="IInsightsAi"/> — orchestrates the
/// synthesis path (<see cref="AnswerQuestionAsync"/> via D-P13 cache +
/// <see cref="IPlaybookExecutionEngine"/>), the ingest path
/// (<see cref="RunIngestAsync"/> via the universal-ingest@v1 JPS playbook), and embedding
/// generation (<see cref="EmbedTextAsync"/> via <see cref="IOpenAiClient"/>) for
/// Zone B callers.
/// </summary>
/// <remarks>
/// <para>
/// <b>Zone A placement</b>: lives under <c>Services/Ai/Insights/</c> and freely imports
/// AI internals (<see cref="IPlaybookExecutionEngine"/>, <see cref="IOpenAiClient"/>,
/// <see cref="IInsightsPlaybookExecutionCache"/>, <see cref="IPlaybookOrchestrationService"/>).
/// Zone B callers receive <see cref="IInsightsAi"/> via DI and have no visibility into any
/// of these types.
/// </para>
/// <para>
/// <b>Phase 1.5 r2 Wave C-G4 (task 022) — IngestOrchestrator retirement</b>: the legacy
/// code-defined ingest path (<c>IIngestOrchestrator</c> + <c>IngestOrchestrator.cs</c>)
/// has been retired. Universal-ingest is now ONE canonical JPS playbook
/// (<c>universal-ingest@v1</c>), parameterized per design-a5 §6 — per D-P15-02 "Insights
/// IS a JPS application; no parallel orchestrators." The kill-switch for the ingest path
/// now lives at the playbook level (deploy a no-op playbook to disable), NOT at the
/// orchestrator. The <c>InsightsIngestOptions</c> feature flag has been deleted as part
/// of the same task.
/// </para>
/// <para>
/// <b>ADR-013 + ADR-009 + ADR-010 compliance</b>:
/// <list type="bullet">
///   <item>ADR-013: Zone A; single facade implementation behind the IInsightsAi seam.</item>
///   <item>ADR-009: synthesis path goes through the D-P13 Redis cache
///   (<see cref="IInsightsPlaybookExecutionCache"/>); no direct
///   <see cref="IDistributedCache"/> usage here.</item>
///   <item>ADR-010: single concrete impl behind the interface; registered Scoped (engine
///   transitively depends on Scoped services). Constructor depends on 6 services after
///   Wave C-G4 retirement of <c>IIngestOrchestrator</c> + <c>IOptions&lt;InsightsIngestOptions&gt;</c>
///   — well inside the ADR-010 ctor-param cap.</item>
/// </list>
/// </para>
/// </remarks>
public sealed class InsightsOrchestrator : IInsightsAi
{
    /// <summary>
    /// Canonical name of the universal-ingest@v1 playbook. Per-environment Guid resolution
    /// goes through <see cref="InsightsPlaybookNameMapOptions"/> — the same name catalog
    /// the <c>/api/insights/ask</c> endpoint uses for predict-matter-cost@v1. Deploy-time
    /// configuration MUST map this name to the Dataverse <c>sprk_analysisplaybook</c> Guid
    /// generated by <c>Deploy-Playbook.ps1</c> in the target environment.
    /// </summary>
    /// <remarks>
    /// Per <see cref="InsightsPlaybookNameMapOptions"/> XML doc, App Service POSIX env-var
    /// rules forbid <c>@</c> and <c>-</c> in env-var keys (Linux App Service), so the
    /// configuration key MUST use the snake_case_only variant
    /// (<c>universal_ingest_v1</c>). The Dataverse <c>sprk_name</c> still uses
    /// <c>universal-ingest@v1</c>; the map key is purely an API/config-layer string.
    /// File-source bindings (<c>appsettings.json</c>) accept either form but the
    /// canonical contract is snake_case_only for portability.
    /// </remarks>
    private const string UniversalIngestPlaybookCanonicalName = "universal_ingest_v1";

    /// <summary>
    /// Output variable name on the <c>emitObservations</c> node in
    /// <c>universal-ingest@v1</c> (per <c>universal-ingest.playbook.json</c>). The
    /// adapter reads the node's <see cref="NodeOutput.StructuredData"/> as
    /// <see cref="ObservationEmissionResult"/> and projects to
    /// <see cref="InsightsIngestResult"/>. Mismatch (e.g., playbook renamed the variable)
    /// will cause the adapter to log a Warning and surface an empty result.
    /// </summary>
    private const string EmitObservationsOutputVariable = "emission";

    /// <summary>
    /// Output variable name on the <c>layer1Classify</c> node. Used by the adapter as
    /// the fallback source of the <c>Layer1Classification</c> field when the emission
    /// node did not run (e.g., sanitize-empty short-circuit) — preserves the r1 facade
    /// contract where <c>InsightsIngestResult.Layer1Classification</c> is populated
    /// whenever Layer 1 ran successfully.
    /// </summary>
    private const string Layer1OutputVariable = "layer1";

    private static readonly EventId IngestPlaybookAdapterMismatchEvent = new(8062, "InsightsRunIngestPlaybookAdapterMismatch");
    private static readonly EventId IngestPlaybookFailedEvent = new(8063, "InsightsRunIngestPlaybookFailed");

    private readonly IPlaybookExecutionEngine _engine;
    private readonly IInsightsPlaybookExecutionCache _cache;
    private readonly IOpenAiClient _openAi;
    private readonly IPlaybookOrchestrationService _playbookOrchestration;
    private readonly IIngestDocumentSource _ingestDocumentSource;
    private readonly IOptionsMonitor<InsightsPlaybookNameMapOptions> _playbookNameMap;
    private readonly IRagService _ragService;
    private readonly AssistantToolCallHandler _assistantHandler;
    private readonly ILogger<InsightsOrchestrator> _logger;

    public InsightsOrchestrator(
        IPlaybookExecutionEngine engine,
        IInsightsPlaybookExecutionCache cache,
        IOpenAiClient openAi,
        IPlaybookOrchestrationService playbookOrchestration,
        IIngestDocumentSource ingestDocumentSource,
        IOptionsMonitor<InsightsPlaybookNameMapOptions> playbookNameMap,
        IRagService ragService,
        AssistantToolCallHandler assistantHandler,
        ILogger<InsightsOrchestrator> logger)
    {
        _engine = engine ?? throw new ArgumentNullException(nameof(engine));
        _cache = cache ?? throw new ArgumentNullException(nameof(cache));
        _openAi = openAi ?? throw new ArgumentNullException(nameof(openAi));
        _playbookOrchestration = playbookOrchestration ?? throw new ArgumentNullException(nameof(playbookOrchestration));
        _ingestDocumentSource = ingestDocumentSource ?? throw new ArgumentNullException(nameof(ingestDocumentSource));
        _playbookNameMap = playbookNameMap ?? throw new ArgumentNullException(nameof(playbookNameMap));
        _ragService = ragService ?? throw new ArgumentNullException(nameof(ragService));
        _assistantHandler = assistantHandler ?? throw new ArgumentNullException(nameof(assistantHandler));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
    }

    /// <inheritdoc />
    public Task<AssistantQueryFacadeResult> AssistantQueryAsync(
        AssistantQueryFacadeRequest request,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);

        // Delegate to the Wave E3 handler. Pass the orchestrator's OWN playbook + RAG methods
        // as delegates so the handler does NOT take a direct dependency on IInsightsAi
        // (avoids constructor-cycle: AssistantToolCallHandler ← IInsightsAi ← InsightsOrchestrator
        // ← AssistantToolCallHandler). The delegates capture `this` which is safe because the
        // orchestrator is Scoped and the request lifetime never outlives its hosting scope.
        return _assistantHandler.ExecuteAsync(
            request,
            playbookInvoker: AnswerQuestionAsync,
            ragInvoker: SearchAsync,
            cancellationToken);
    }

    /// <inheritdoc />
    public async IAsyncEnumerable<AssistantQueryChunk> AssistantQueryStreamAsync(
        AssistantQueryFacadeRequest request,
        [EnumeratorCancellation] CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        ArgumentException.ThrowIfNullOrWhiteSpace(request.Query, nameof(request));
        ArgumentException.ThrowIfNullOrWhiteSpace(request.ParentEntityType, nameof(request));
        ArgumentException.ThrowIfNullOrWhiteSpace(request.ParentEntityId, nameof(request));
        ArgumentException.ThrowIfNullOrWhiteSpace(request.Subject, nameof(request));
        ArgumentException.ThrowIfNullOrWhiteSpace(request.TenantId, nameof(request));
        ArgumentException.ThrowIfNullOrWhiteSpace(request.CallerOid, nameof(request));

        var sw = Stopwatch.StartNew();

        // ─── Step 1: Routing decision via shared handler logic ────────────────────────
        // FeatureDisabledException from the classifier propagates BEFORE we yield any chunk
        // — the endpoint catches it pre-stream and returns 503 ProblemDetails with no SSE
        // body (ADR-032 kill-switch ordering invariant + Wave F1 spike Section A).
        yield return new AssistantQueryChunk { Type = "progress", Step = "classifier_started" };

        AssistantToolCallHandler.RoutingDecision routing;
        try
        {
            routing = await _assistantHandler.DecideRouteAsync(request, cancellationToken).ConfigureAwait(false);
        }
        catch (Configuration.FeatureDisabledException)
        {
            // Per ADR-032 kill-switch ordering: re-throw BEFORE the first non-control chunk.
            // We already emitted classifier_started — that's a benign progress marker; the
            // endpoint will still write 503 ProblemDetails because the exception unwinds the
            // entire SSE body if it surfaces here. To preserve the "no SSE body on 503"
            // invariant, the endpoint must guard the DecideRouteAsync call BEFORE opening
            // the SSE response. See InsightsAssistantEndpoint streaming flow.
            throw;
        }

        yield return new AssistantQueryChunk
        {
            Type = "progress",
            Step = "classifier_complete",
            Content = routing.Path
        };

        // ─── Step 2: Dispatch path-specific streaming ─────────────────────────────────
        if (routing.Path == "playbook")
        {
            await foreach (var chunk in StreamPlaybookPathAsync(request, routing, cancellationToken).ConfigureAwait(false))
            {
                yield return chunk;
            }
        }
        else
        {
            await foreach (var chunk in StreamRagPathAsync(request, routing, cancellationToken).ConfigureAwait(false))
            {
                yield return chunk;
            }
        }

        sw.Stop();
        _logger.LogInformation(
            "InsightsOrchestrator.AssistantQueryStreamAsync completed path={Path} intentSource={IntentSource} elapsedMs={ElapsedMs} tenant={TenantId} subject={Scheme}:{Id}",
            routing.Path, routing.IntentSource, sw.ElapsedMilliseconds,
            request.TenantId, request.ParentEntityType, request.ParentEntityId);
    }

    /// <summary>
    /// Stream the RAG path: emit retrieval progress, then forward AOAI synthesis tokens as
    /// <c>delta</c> chunks, then emit the final <c>result</c>. Mirrors
    /// <see cref="SearchAsync"/>'s logic but swaps the single-shot
    /// <see cref="IOpenAiClient.GetCompletionAsync"/> call for token streaming via
    /// <see cref="IOpenAiClient.StreamCompletionAsync"/>.
    /// </summary>
    private async IAsyncEnumerable<AssistantQueryChunk> StreamRagPathAsync(
        AssistantQueryFacadeRequest request,
        AssistantToolCallHandler.RoutingDecision routing,
        [EnumeratorCancellation] CancellationToken cancellationToken)
    {
        // Build RAG facade request (same as single-shot per AssistantToolCallHandler.ExecuteRagPathAsync).
        var ragRequest = new InsightsSearchFacadeRequest(
            Query: request.Query,
            ParentEntityType: request.ParentEntityType,
            ParentEntityId: request.ParentEntityId,
            ArtifactType: null,
            Predicate: null,
            TopK: 10,
            TenantId: request.TenantId,
            CallerPrincipal: request.CallerPrincipal,
            ForceMode: request.ForceMode);

        yield return new AssistantQueryChunk { Type = "progress", Step = "rag_search_started" };

        // FeatureDisabledException from NullRagService propagates here (ADR-032 P3); the
        // streaming caller has already emitted classifier_complete chunk(s). The endpoint
        // converts to a mid-stream `error` chunk via the IsAsyncEnumerable's outer try/catch.
        var ragResult = await SearchAsync(ragRequest, cancellationToken).ConfigureAwait(false);

        yield return new AssistantQueryChunk
        {
            Type = "progress",
            Step = "rag_search_complete",
            Content = ragResult.Results.Count.ToString(CultureInfo.InvariantCulture)
        };

        // Zero-hit short-circuit: no synthesis, emit empty result + done. Matches SearchAsync
        // semantics (no grounding → no synthesis).
        if (ragResult.Results.Count == 0)
        {
            var emptyResult = _assistantHandler.BuildRagResult(ragResult, streamedAnswer: null, routing.IntentSource, routing.BelowThreshold)
                with
            { DurationMs = ragResult.DurationMs };
            yield return new AssistantQueryChunk { Type = "result", Result = emptyResult };
            yield break;
        }

        // Stream LLM synthesis tokens. Build the same prompt SearchAsync uses for parity.
        yield return new AssistantQueryChunk { Type = "progress", Step = "llm_synthesis_started" };

        var prompt = BuildGroundedSynthesisPrompt(
            request.Query, request.ParentEntityType, request.ParentEntityId, ragResult.Results);

        var accumulator = new StringBuilder();
        int sequence = 0;
        await foreach (var token in _openAi.StreamCompletionAsync(
            prompt, model: null, maxOutputTokens: 400, cancellationToken).ConfigureAwait(false))
        {
            accumulator.Append(token);
            yield return new AssistantQueryChunk
            {
                Type = "delta",
                Path = "answer",
                Content = token,
                Sequence = ++sequence
            };
        }

        var streamedAnswer = accumulator.ToString();
        var ragFinalResult = _assistantHandler.BuildRagResult(ragResult, streamedAnswer, routing.IntentSource, routing.BelowThreshold)
            with
        { DurationMs = ragResult.DurationMs };
        yield return new AssistantQueryChunk { Type = "result", Result = ragFinalResult };
    }

    /// <summary>
    /// Stream the playbook path: emit cache-aware progress + final <c>result</c>.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>v1.1 limitation (per F1 spike Section D)</b>: the playbook path emits COARSE-GRAINED
    /// progress only (<c>playbook_started</c>, <c>playbook_complete</c> OR <c>cache_hit</c>),
    /// not per-node events. This is because the existing D-P13
    /// <see cref="IInsightsPlaybookExecutionCache"/> drains the engine stream internally — we
    /// don't have a peek-then-stream API. Per-node streaming is deferred to v1.2 (would require
    /// either a cache refactor or bypassing the cache for streaming, both out of v1.1 scope).
    /// </para>
    /// <para>
    /// <b>Cache-hit short-circuit</b>: when the cache serves the answer (synchronous fast path),
    /// we emit <c>progress {step: "cache_hit"}</c> + <c>result</c> immediately per spike
    /// Section D. R5's chat agent treats cache-hit as instant render.
    /// </para>
    /// </remarks>
    private async IAsyncEnumerable<AssistantQueryChunk> StreamPlaybookPathAsync(
        AssistantQueryFacadeRequest request,
        AssistantToolCallHandler.RoutingDecision routing,
        [EnumeratorCancellation] CancellationToken cancellationToken)
    {
        var canonicalName = _assistantHandler.ResolvePlaybookCanonicalName(routing.ClassifierPlaybookHint);
        var playbookId = _playbookNameMap.CurrentValue.ResolveOrDefault(canonicalName);
        if (playbookId == Guid.Empty)
        {
            // Same error path as the single-shot handler — InvalidOperationException with the
            // canonical "Default playbook" message. Endpoint catches and maps to 503 with
            // errorCode = "ai.assistant-default-playbook.unconfigured" BEFORE the stream opens
            // (this throws before the first chunk yields from this method). Caller must
            // catch BEFORE calling MoveNextAsync past the first chunk.
            throw new InvalidOperationException(
                $"Default playbook '{canonicalName}' is not configured in 'Insights:Playbooks:NameMap:Map'. " +
                "Configure the playbook Guid per-environment OR omit forceMode to let the classifier route the query.");
        }

        yield return new AssistantQueryChunk
        {
            Type = "progress",
            Step = "playbook_started",
            Content = canonicalName
        };

        // Build playbook request (same shape as AssistantToolCallHandler.ExecutePlaybookPathAsync).
        var playbookRequest = new InsightsAgentRequest(
            Question: playbookId,
            Subject: request.Subject,
            Parameters: null,
            TenantId: request.TenantId,
            AccessibleScopeHash: AssistantToolCallHandler.ComputeAccessibleScopeHash(request.TenantId, request.CallerOid));

        // Invoke single-shot AnswerQuestionAsync (cache-aware). FeatureDisabledException
        // propagates unchanged.
        var agentResult = await AnswerQuestionAsync(playbookRequest, cancellationToken).ConfigureAwait(false);

        // Cache-hit short-circuit per F1 spike Section D — emit single cache_hit progress
        // then go straight to result. No coarse-grained playbook_complete (semantically
        // redundant when CacheHit signals "no engine ran").
        if (agentResult.CacheHit)
        {
            yield return new AssistantQueryChunk { Type = "progress", Step = "cache_hit" };
        }
        else
        {
            yield return new AssistantQueryChunk { Type = "progress", Step = "playbook_complete" };
        }

        var facadeResult = _assistantHandler.BuildPlaybookResult(
            agentResult, canonicalName, routing.IntentSource, routing.BelowThreshold)
            with
        { DurationMs = agentResult.ProcessingTimeMs };

        yield return new AssistantQueryChunk { Type = "result", Result = facadeResult };
    }

    /// <summary>
    /// Build the grounded-synthesis prompt for the RAG path. Identical shape to
    /// <see cref="SynthesizeGroundedSummaryAsync"/> so the streamed answer matches the
    /// single-shot answer for the same input. Factored out for reuse by the streaming path.
    /// </summary>
    private static string BuildGroundedSynthesisPrompt(
        string query,
        string parentEntityType,
        string parentEntityId,
        IReadOnlyList<InsightsSearchHit> hits)
    {
        var contextBuilder = new StringBuilder();
        for (int i = 0; i < hits.Count; i++)
        {
            var hit = hits[i];
            contextBuilder
                .Append('[').Append(i + 1).Append("] ")
                .Append(hit.DocumentName)
                .Append(" — ")
                .Append(hit.Snippet)
                .AppendLine();
        }

        return
            "You are a legal research assistant answering questions about a specific " +
            $"{parentEntityType} (id: {parentEntityId}). " +
            "Answer the user's question using ONLY the numbered context snippets below. " +
            "Cite every factual claim with [n] referring to the snippet it came from. " +
            "If the snippets do not contain enough information to answer, say so plainly. " +
            "Do NOT fabricate facts not present in the snippets.\n\n" +
            $"Question: {query}\n\n" +
            "Context:\n" +
            contextBuilder.ToString() + "\n" +
            "Answer (with [n] citations):";
    }

    /// <inheritdoc />
    public async Task<InsightsAgentResult> AnswerQuestionAsync(
        InsightsAgentRequest request,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        ArgumentException.ThrowIfNullOrWhiteSpace(request.Subject);
        ArgumentException.ThrowIfNullOrWhiteSpace(request.TenantId);
        ArgumentException.ThrowIfNullOrWhiteSpace(request.AccessibleScopeHash);

        var sw = Stopwatch.StartNew();

        // Derive well-known template variables from Subject so playbook node ConfigJson
        // can reference them as {{matterId}} etc. without callers having to supply them
        // redundantly. Per Insights Engine r2 Wave B (2026-06-02 smoke trace): playbook nodes
        // like resolveLiveFacts have configJson `"subject": "matter:{{matterId}}"` — without
        // this enrichment the literal "{{matterId}}" was passed to LiveFactResolver, which
        // rejected the request as InvalidConfiguration. Wave B5 SC-01 unblock.
        IReadOnlyDictionary<string, string>? enrichedParameters = EnrichParametersFromSubject(
            request.Parameters, request.Subject);

        var cacheRequest = new InsightsPlaybookExecutionRequest(
            PlaybookId: request.Question,
            Subject: request.Subject,
            Parameters: enrichedParameters,
            AccessibleScopeHash: request.AccessibleScopeHash,
            TenantId: request.TenantId,
            Ttl: null); // Defer to InsightsPlaybookExecutionCache.DefaultTtl (D-P13: 5 min).

        // Cache wraps the engine. On HIT the engine factory is never invoked.
        // On MISS the cache invokes the factory which drives ExecuteBatchAsync and
        // drains the stream looking for BOTH the ReturnInsightArtifactNode output (D-P12)
        // and the DeclineToFindNode output (task 071). The result carries whichever path
        // the playbook took.
        bool factoryWasCalled = false;

        var runResult = await _cache.GetOrExecuteAsync(
            cacheRequest,
            engineInvocation: ct =>
            {
                factoryWasCalled = true;
                return _engine.ExecuteBatchAsync(
                    new PlaybookRunRequest
                    {
                        PlaybookId = request.Question,
                        // Phase 1 scaffold note: D-P15 endpoint (task 061) is responsible
                        // for resolving subject → relevant document ids before calling the
                        // facade. The synthesis playbook (D-P14) uses LiveFactNode +
                        // IndexRetrieveNode for cohort retrieval; it does NOT process
                        // ad-hoc DocumentIds. We pass an empty array to satisfy the
                        // engine's required[] contract; the playbook ignores it.
                        DocumentIds = Array.Empty<Guid>(),
                        Parameters = enrichedParameters
                    },
                    ct);
            },
            cancellationToken);

        sw.Stop();
        var elapsedMs = sw.ElapsedMilliseconds;
        var cacheHit = !factoryWasCalled;

        // Path 1: artifact produced (sufficient-evidence path). Defensive "both populated"
        // case: prefer Artifact per InsightsEngineRunResult contract ("sufficient path wins").
        if (runResult.HasArtifact)
        {
            _logger.LogDebug(
                "InsightsOrchestrator AnswerQuestionAsync: playbook {PlaybookId} subject {Subject} produced artifact (cacheHit={CacheHit}, elapsedMs={ElapsedMs})",
                request.Question, request.Subject, cacheHit, elapsedMs);
            return InsightsAgentResult.Success(runResult.Artifact!, cacheHit, elapsedMs);
        }

        // Path 2: real decline produced (insufficient-evidence path). Per task 071, the
        // cache now extracts DeclineToFindNode output from the engine stream and surfaces
        // it here with structured MinimumEvidenceNeeded gap analysis from upstream
        // EvidenceSufficiencyNode — no more scaffold "no-artifact-produced" for this case.
        // CacheHit is ALWAYS false on the decline path because declines are never cached
        // (evidence sufficiency depends on the current state of the index).
        if (runResult.HasDecline)
        {
            _logger.LogDebug(
                "InsightsOrchestrator AnswerQuestionAsync: playbook {PlaybookId} subject {Subject} produced decline (reason={Reason}, gaps={GapCount}, elapsedMs={ElapsedMs})",
                request.Question, request.Subject, runResult.Decline!.Reason,
                runResult.Decline.MinimumEvidenceNeeded.Count, elapsedMs);
            return InsightsAgentResult.Declined(runResult.Decline, cacheHit: false, elapsedMs);
        }

        // Path 3 (defensive): engine produced neither artifact nor decline. This should not
        // happen with a well-formed playbook (EvidenceSufficiencyNode's branch routing
        // guarantees exactly one terminal node fires). If it does — malformed playbook,
        // engine error masked, branch routing bug — log Warning and emit a scaffold decline
        // so the facade contract's "exactly one of artifact/decline" invariant holds for
        // Zone B callers. The scaffold's ConfidenceInDecline = 0.0 signals "this is not a
        // real decline verdict" to observability tooling.
        _logger.LogWarning(
            "InsightsOrchestrator AnswerQuestionAsync: playbook {PlaybookId} subject {Subject} produced NO artifact AND NO decline; engine may be misconfigured. Returning scaffold decline. (cacheHit={CacheHit}, elapsedMs={ElapsedMs})",
            request.Question, request.Subject, cacheHit, elapsedMs);

        return InsightsAgentResult.Declined(
            new DeclineResponse
            {
                Reason = "no-artifact-produced",
                Explanation = "The playbook completed without emitting an InsightArtifact or DeclineResponse. This indicates a malformed playbook (missing terminal node), an engine error masked by node validation, or a branch-routing bug. Operations: inspect the playbook's terminal nodes (ReturnInsightArtifactNode + DeclineToFindNode) and EvidenceSufficiencyNode branch wiring.",
                MinimumEvidenceNeeded = new Dictionary<string, object>(),
                SuggestedActions = Array.Empty<string>(),
                ConfidenceInDecline = 0.0 // Sentinel: not a real decline verdict
            },
            cacheHit,
            elapsedMs);
    }

    /// <inheritdoc />
    public async Task<InsightsIngestResult> RunIngestAsync(
        InsightsIngestRequest request,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        ArgumentException.ThrowIfNullOrWhiteSpace(request.DocumentId);
        ArgumentException.ThrowIfNullOrWhiteSpace(request.MatterId);
        ArgumentException.ThrowIfNullOrWhiteSpace(request.TenantId);

        // Phase 1.5 r2 Wave C5 (task 024): validate optional parameter overrides at the
        // facade boundary so that bad inputs fail fast with a clear ArgumentException
        // before any AI cost is incurred. The validation enforces well-formedness only;
        // domain validation (e.g., practice-area code exists in sprk_practicearea_ref)
        // happens downstream in the playbook node executor where Dataverse is reachable.
        // See design-a5-universal-ingest-jps.md §6 for the parameter contract.
        ValidateIngestParameters(request);

        // Phase 1.5 r2 Wave C-G4 (task 022): the universal-ingest@v1 JPS playbook is the
        // ONLY runtime path. The legacy code-defined IIngestOrchestrator path has been
        // retired per D-P15-02 "Insights IS a JPS application; no parallel orchestrators".
        // Operators can disable ingest by deploying a no-op playbook at the
        // `universal-ingest@v1` canonical name (playbook-level kill-switch); this layer
        // no longer carries a feature flag. See InsightsOrchestrator class-level <remarks>
        // for the rationale and Wave C-G4 task POML for the decision record.
        return await RunIngestViaPlaybookAsync(request, cancellationToken)
            .ConfigureAwait(false);
    }

    /// <summary>
    /// Invoke <c>universal-ingest@v1</c> via
    /// <see cref="IPlaybookOrchestrationService.ExecuteAppOnlyAsync"/>, drain the stream,
    /// and adapt the final <c>emitObservations</c> node output to
    /// <see cref="InsightsIngestResult"/>. The adapter preserves the r1 facade contract —
    /// Zone B callers see no surface change.
    /// </summary>
    /// <remarks>
    /// <para>
    /// <b>Path</b>: IIngestDocumentSource.FetchAsync → assemble parameters →
    /// IPlaybookOrchestrationService.ExecuteAppOnlyAsync(universal-ingest@v1, parameters)
    /// → drain stream → find emission node output → project to <see cref="InsightsIngestResult"/>.
    /// </para>
    /// <para>
    /// <b>Why ExecuteAppOnlyAsync, not IPlaybookExecutionEngine.ExecuteBatchAsync</b>: the
    /// ingest path is invoked from a background <c>BackgroundService</c> (D-P8 SPE-upload
    /// consumer / Service Bus). <see cref="IPlaybookExecutionEngine.ExecuteBatchAsync"/>
    /// requires an <see cref="Microsoft.AspNetCore.Http.HttpContext"/> (per
    /// <c>PlaybookExecutionEngine</c> line 91); app-only invocation explicitly avoids it.
    /// </para>
    /// <para>
    /// <b>Failure handling</b> (post Wave C-G4 retirement): on playbook failure (engine
    /// throws OR emits <c>RunFailed</c>) we log Error and propagate the failure to the
    /// caller. The D-P8 SPE-upload consumer (<c>InsightsIngestJobHandler</c>) treats this
    /// per ADR-004 — transient failures retry via Service Bus; persistent failures
    /// dead-letter after delivery-count exhaustion. There is no longer a legacy fallback.
    /// </para>
    /// </remarks>
    private async Task<InsightsIngestResult> RunIngestViaPlaybookAsync(
        InsightsIngestRequest request,
        CancellationToken cancellationToken)
    {
        var sw = Stopwatch.StartNew();

        // Step 1: Fetch document content (the facade owns the fetch per design-a5 §4
        // Node 1 — the executor receives pre-fetched text + chunks via parameters).
        // Null result = non-indexable document; the playbook will short-circuit at
        // sanitize. Match the r1 early-return semantics: produce an empty result so
        // Zone B callers see the same "0 observations, no Layer 1" outcome.
        var content = await _ingestDocumentSource.FetchAsync(
            request.DocumentId, request.TenantId, cancellationToken)
            .ConfigureAwait(false);
        if (content is null)
        {
            _logger.LogInformation(
                "InsightsOrchestrator.RunIngestAsync (playbook path): document not indexable, returning empty result (documentId={DocumentId} tenantId={TenantId})",
                request.DocumentId, request.TenantId);
            return new InsightsIngestResult(
                ObservationsEmitted: 0,
                Layer1Classification: null,
                Layer2Triggered: false);
        }

        // Step 2: Assemble playbook parameters per design-a5 §6 parameterSchema.
        // Required: documentId, matterId, tenantId, documentText, chunksJson, documentRef.
        // Optional: practiceAreaHint, costCapOverride, layer2Threshold (null → omit,
        // playbook schema defaults apply per §6).
        var parameters = AssemblePlaybookParameters(request, content);

        // Step 3: Invoke the playbook via app-only orchestration. ExecuteAppOnlyAsync is
        // the correct entry — it does NOT require HttpContext (D-P8 dispatch is a
        // BackgroundService scope, not a request scope).
        //
        // Post Wave C-G4 (task 022): the playbook Guid is resolved at invocation time
        // through the existing InsightsPlaybookNameMapOptions (the same per-env name →
        // Guid map the /api/insights/ask endpoint uses for predict-matter-cost@v1). The
        // canonical name `universal-ingest@v1` is the operational identity per D-P15-02
        // "ONE canonical universal-ingest playbook"; the per-env Guid is set by
        // Deploy-Playbook.ps1 and configured at the `Insights:Playbooks:Map` section.
        var playbookId = _playbookNameMap.CurrentValue
            .ResolveOrDefault(UniversalIngestPlaybookCanonicalName);
        if (playbookId == Guid.Empty)
        {
            _logger.Log(
                LogLevel.Error,
                IngestPlaybookFailedEvent,
                "InsightsOrchestrator.RunIngestAsync: universal-ingest@v1 playbook Guid is unconfigured. Set Insights:Playbooks:Map.{CanonicalName} to the Dataverse sprk_analysisplaybook row Guid in this environment (Deploy-Playbook.ps1 emits it). documentId={DocumentId} matterId={MatterId} tenantId={TenantId}",
                UniversalIngestPlaybookCanonicalName, request.DocumentId, request.MatterId, request.TenantId);
            throw new InvalidOperationException(
                $"universal-ingest@v1 playbook is not registered in InsightsPlaybookNameMapOptions " +
                $"(missing config key Insights:Playbooks:Map:{UniversalIngestPlaybookCanonicalName}). " +
                $"Deploy the playbook via scripts/Deploy-Playbook.ps1 and add its Guid to per-environment configuration.");
        }
        var runRequest = new PlaybookRunRequest
        {
            PlaybookId = playbookId,
            // Universal-ingest does NOT process ad-hoc DocumentIds (each playbook node
            // reads from parameters.documentText / parameters.chunks). Pass an empty array
            // to satisfy the required[] contract; nodes ignore it.
            DocumentIds = Array.Empty<Guid>(),
            Parameters = parameters
        };

        _logger.LogInformation(
            "InsightsOrchestrator.RunIngestAsync invoking universal-ingest@v1 (playbookId={PlaybookId} documentId={DocumentId} matterId={MatterId} tenantId={TenantId})",
            playbookId, request.DocumentId, request.MatterId, request.TenantId);

        ObservationEmissionResult? emission = null;
        string? layer1Classification = null;
        string? runFailedError = null;

        try
        {
            await foreach (var evt in _playbookOrchestration.ExecuteAppOnlyAsync(
                runRequest, request.TenantId, cancellationToken).ConfigureAwait(false))
            {
                switch (evt.Type)
                {
                    case PlaybookEventType.NodeCompleted when evt.NodeOutput is { Success: true }:
                        // Capture the emission node output (project to InsightsIngestResult below).
                        if (string.Equals(evt.NodeOutput.OutputVariable, EmitObservationsOutputVariable, StringComparison.Ordinal))
                        {
                            emission = evt.NodeOutput.GetData<ObservationEmissionResult>();
                        }
                        // Capture the layer1 classification as a fallback (used if the emission node
                        // did not run — e.g., sanitize short-circuit short of the L1+gate path).
                        else if (string.Equals(evt.NodeOutput.OutputVariable, Layer1OutputVariable, StringComparison.Ordinal))
                        {
                            layer1Classification = ExtractLayer1Classification(evt.NodeOutput);
                        }
                        break;

                    case PlaybookEventType.RunFailed:
                        runFailedError = evt.Error ?? "Playbook run failed (no error message provided)";
                        break;
                }
            }
        }
        catch (OperationCanceledException) { throw; }
        catch (Exception ex)
        {
            _logger.Log(
                LogLevel.Error,
                IngestPlaybookFailedEvent,
                ex,
                "InsightsOrchestrator.RunIngestAsync universal-ingest@v1 threw: playbookId={PlaybookId} documentId={DocumentId} matterId={MatterId} tenantId={TenantId} elapsedMs={ElapsedMs}. Failure propagates per ADR-004 (D-P8 SPE-upload consumer policy: transient → retry; persistent → dead-letter).",
                playbookId, request.DocumentId, request.MatterId, request.TenantId, sw.ElapsedMilliseconds);
            throw;
        }

        sw.Stop();

        if (runFailedError is not null)
        {
            _logger.Log(
                LogLevel.Error,
                IngestPlaybookFailedEvent,
                "InsightsOrchestrator.RunIngestAsync universal-ingest@v1 emitted RunFailed: playbookId={PlaybookId} documentId={DocumentId} matterId={MatterId} tenantId={TenantId} error={Error} elapsedMs={ElapsedMs}. Failure propagates per ADR-004 (D-P8 SPE-upload consumer policy: transient → retry; persistent → dead-letter).",
                playbookId, request.DocumentId, request.MatterId, request.TenantId, runFailedError, sw.ElapsedMilliseconds);
            throw new InvalidOperationException(
                $"universal-ingest@v1 playbook execution failed for documentId={request.DocumentId} matterId={request.MatterId}: {runFailedError}");
        }

        return AdaptPlaybookResult(emission, layer1Classification, request, sw.ElapsedMilliseconds);
    }

    /// <summary>
    /// Build the playbook parameters dictionary per design-a5 §6 parameterSchema. All
    /// values are stringified — the playbook engine's template substitution operates on
    /// the string form. Optional overrides (PracticeAreaHint, CostCapOverride,
    /// Layer2Threshold) are omitted when null so the parameterSchema defaults apply.
    /// </summary>
    /// <remarks>
    /// <b>Invariant culture for numerics</b> — currency caps and thresholds must
    /// serialize as <c>1.50</c>, <c>0.7</c> (not <c>1,50</c> / <c>0,7</c>) regardless of
    /// the App Service host culture. ALL invariant-culture formatting throughout.
    /// </remarks>
    internal static IReadOnlyDictionary<string, string> AssemblePlaybookParameters(
        InsightsIngestRequest request,
        IngestDocumentContent content)
    {
        // Serialize chunks as a JSON array per the SanitizerNodeExecutor contract
        // (parameters.chunksJson is parsed back into a JsonElement[] by the executor).
        var chunksJson = JsonSerializer.Serialize(content.Chunks);

        var parameters = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
        {
            // Required (per design-a5 §6 parameterSchema "required" array).
            ["documentId"] = request.DocumentId,
            ["matterId"] = request.MatterId,
            ["tenantId"] = request.TenantId,
            // Required (consumed by SanitizerNodeExecutor + emitObservations executor —
            // these are NOT in the schema "required" array because the design assumes
            // they're injected by the facade, not supplied by upstream callers).
            ["documentText"] = content.FullText,
            ["chunksJson"] = chunksJson,
            ["documentRef"] = content.DocumentRef
        };

        // Optional overrides — omit (rather than send null/empty) so the playbook
        // parameterSchema's default values apply per design-a5 §6:
        //   layer2Threshold default = 0.7 (Phase 1 D-59)
        //   practiceAreaHint default = null (litigation-default prompts)
        //   costCapOverride default = null (tenant monthly cap from D-P9)
        if (!string.IsNullOrWhiteSpace(request.PracticeAreaHint))
        {
            parameters["practiceAreaHint"] = request.PracticeAreaHint;
        }
        if (request.CostCapOverride is { } cap)
        {
            parameters["costCapOverride"] = cap.ToString(CultureInfo.InvariantCulture);
        }
        if (request.Layer2Threshold is { } threshold)
        {
            parameters["layer2Threshold"] = threshold.ToString(CultureInfo.InvariantCulture);
        }

        return parameters;
    }

    /// <summary>
    /// Project the playbook's <see cref="ObservationEmissionResult"/> (from the
    /// <c>emitObservations</c> node — per Wave C1 task 020 shape-matched to
    /// <see cref="InsightsIngestResult"/>) to the facade's <see cref="InsightsIngestResult"/>.
    /// Handles the defensive case where the emission node did not run (e.g., the playbook
    /// short-circuited at sanitize-empty) by surfacing the Layer 1 classification when
    /// available + zero observations.
    /// </summary>
    private InsightsIngestResult AdaptPlaybookResult(
        ObservationEmissionResult? emission,
        string? layer1ClassificationFallback,
        InsightsIngestRequest request,
        long elapsedMs)
    {
        if (emission is not null)
        {
            _logger.LogInformation(
                "InsightsOrchestrator.RunIngestAsync (playbook path) completed: documentId={DocumentId} layer1Classification={Layer1Classification} layer2Triggered={Layer2Triggered} observationsEmitted={ObservationsEmitted} elapsedMs={ElapsedMs}",
                request.DocumentId, emission.Layer1Classification, emission.Layer2Triggered,
                emission.ObservationsEmitted, elapsedMs);
            return new InsightsIngestResult(
                ObservationsEmitted: emission.ObservationsEmitted,
                Layer1Classification: emission.Layer1Classification,
                Layer2Triggered: emission.Layer2Triggered);
        }

        // Defensive path — playbook ran to completion (no RunFailed) but no emission
        // output captured. Most likely cause: sanitize short-circuited (SANITIZE_EMPTY)
        // and downstream nodes skipped — semantically equivalent to r1's
        // "sanitized-empty" early return. Surface the Layer 1 classification if we
        // captured it (we usually won't on this path); otherwise emit empty.
        _logger.Log(
            LogLevel.Warning,
            IngestPlaybookAdapterMismatchEvent,
            "InsightsOrchestrator.RunIngestAsync (playbook path) completed without an emitObservations output (documentId={DocumentId} layer1ClassificationFallback={Layer1Classification} elapsedMs={ElapsedMs}). Most likely cause: sanitize short-circuit (SANITIZE_EMPTY). Surfacing empty result to preserve r1 parity.",
            request.DocumentId, layer1ClassificationFallback, elapsedMs);
        return new InsightsIngestResult(
            ObservationsEmitted: 0,
            Layer1Classification: layer1ClassificationFallback,
            Layer2Triggered: false);
    }

    /// <summary>
    /// Extract the <c>classification</c> string from a Layer 1 node output (case-insensitive).
    /// Mirrors <see cref="ObservationEmitterNodeExecutor"/>'s extraction logic so the
    /// fallback path produces the same field value as the canonical emission path.
    /// </summary>
    private static string? ExtractLayer1Classification(NodeOutput layer1)
    {
        if (layer1.StructuredData is null) return null;
        var data = layer1.StructuredData.Value;
        if (data.ValueKind != JsonValueKind.Object) return null;

        if (data.TryGetProperty("classification", out var camel) && camel.ValueKind == JsonValueKind.String)
            return camel.GetString();
        if (data.TryGetProperty("Classification", out var pascal) && pascal.ValueKind == JsonValueKind.String)
            return pascal.GetString();
        return null;
    }

    /// <summary>
    /// Validate the Wave C5 optional parameter overrides on
    /// <see cref="InsightsIngestRequest"/>. Throws <see cref="ArgumentException"/> on
    /// any malformed override; returns silently when overrides are absent or valid.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Rules per task 024 POML §step 2 + design-a5 §6 parameterSchema:
    /// <list type="bullet">
    ///   <item><c>PracticeAreaHint</c> — when supplied, must be non-whitespace. Domain
    ///   validation against <c>sprk_practicearea_ref</c> codes happens in the playbook
    ///   node executor (Wave D2) where Dataverse is reachable; the facade only enforces
    ///   well-formedness.</item>
    ///   <item><c>CostCapOverride</c> — when supplied, must be strictly positive
    ///   (&gt; 0). Zero or negative caps are nonsensical; the schema default
    ///   (<c>null</c>) means "use tenant monthly cap from D-P9".</item>
    ///   <item><c>Layer2Threshold</c> — when supplied, must lie in <c>[0.0, 1.0]</c>
    ///   inclusive. NaN and infinity are rejected. The schema default (<c>null</c>)
    ///   means "use playbook default 0.7 per Phase 1 D-59".</item>
    /// </list>
    /// </para>
    /// <para>
    /// Validation runs <em>before</em> any work is dispatched so that bad inputs fail
    /// without incurring LLM cost or Dataverse round-trips. Internal-visible for unit
    /// tests; not part of the public Zone B surface.
    /// </para>
    /// </remarks>
    internal static void ValidateIngestParameters(InsightsIngestRequest request)
    {
        if (request.PracticeAreaHint is not null
            && string.IsNullOrWhiteSpace(request.PracticeAreaHint))
        {
            throw new ArgumentException(
                "PracticeAreaHint, when supplied, must be a non-whitespace practice-area code (e.g., 'CTRNS'). Pass null to omit and use the litigation-default per Phase 1 D-59.",
                nameof(request));
        }

        if (request.CostCapOverride is { } cap && cap <= 0m)
        {
            throw new ArgumentException(
                $"CostCapOverride, when supplied, must be strictly positive (got {cap}). Pass null to omit and use the tenant's monthly cap per D-P9.",
                nameof(request));
        }

        if (request.Layer2Threshold is { } threshold)
        {
            if (double.IsNaN(threshold) || double.IsInfinity(threshold)
                || threshold < 0.0 || threshold > 1.0)
            {
                throw new ArgumentException(
                    $"Layer2Threshold, when supplied, must be a finite value in [0.0, 1.0] (got {threshold}). Pass null to omit and use the playbook default 0.7 per Phase 1 D-59.",
                    nameof(request));
            }
        }
    }

    /// <inheritdoc />
    public Task<ReadOnlyMemory<float>> EmbedTextAsync(
        string text,
        CancellationToken cancellationToken = default)
    {
        ArgumentException.ThrowIfNullOrWhiteSpace(text);

        // Thin delegation to IOpenAiClient. Model + dimensions are left at the
        // client's configured defaults (text-embedding-3-large, 3072 dims) per
        // SPEC §3.4 / D-P2 — the spaarke-insights-index schema is fixed at 3072
        // and the facade is opinionated for substrate consistency. Callers
        // (e.g., D-P4 PrecedentProjectionSync per task 041) do not choose.
        return _openAi.GenerateEmbeddingAsync(
            text,
            model: null,
            dimensions: null,
            cancellationToken: cancellationToken);
    }

    /// <inheritdoc />
    public async Task<InsightsSearchFacadeResult> SearchAsync(
        InsightsSearchFacadeRequest request,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(request);
        ArgumentException.ThrowIfNullOrWhiteSpace(request.Query, nameof(request));
        ArgumentException.ThrowIfNullOrWhiteSpace(request.ParentEntityType, nameof(request));
        ArgumentException.ThrowIfNullOrWhiteSpace(request.ParentEntityId, nameof(request));
        ArgumentException.ThrowIfNullOrWhiteSpace(request.TenantId, nameof(request));

        var sw = Stopwatch.StartNew();

        // Build RagSearchOptions — the IRagService facade already supports the filters
        // Insights search needs (ParentEntityType/Id from Wave D5, DocumentType, Tags).
        // No new RAG-facade interface methods required per task 040 Step 2 decision.
        // Note: tags carry the OR-semantics meaning "matches ANY of the supplied tags";
        // since we set a single Predicate as a RequiredTag (AND semantics), the chunk
        // MUST have that exact tag. That's the desired semantics for predicate filtering.
        var ragOptions = new RagSearchOptions
        {
            TenantId = request.TenantId,
            TopK = request.TopK,
            ParentEntityType = request.ParentEntityType,
            ParentEntityId = request.ParentEntityId,
            DocumentType = request.ArtifactType,
            RequiredTags = !string.IsNullOrWhiteSpace(request.Predicate)
                ? new[] { request.Predicate }
                : null,
            CallerPrincipal = request.CallerPrincipal,
            UseSemanticRanking = true,
            UseVectorSearch = true,
            UseKeywordSearch = true,
            // Slightly lower MinScore than the default (0.7) — Insights queries are
            // open-ended NL and we want recall to dominate precision at the top-K cap.
            // Subject + privilege filtering already trim the space substantially.
            MinScore = 0.5f
        };

        // RAG search. If the kill-switch is OFF, NullRagService throws
        // FeatureDisabledException with ErrorCode = "ai.rag.disabled" (ADR-032 P3).
        // We propagate it unchanged so the endpoint can catch and convert to 503
        // ProblemDetails via AsFeatureDisabled503(). DO NOT swallow.
        var ragResponse = await _ragService.SearchAsync(request.Query, ragOptions, cancellationToken);

        // Project RagSearchResult → InsightsSearchHit (the Zone B-importable shape).
        // Predicate is derived from the first matching Insights-shaped tag when present;
        // we don't have schema confirmation of which tag prefixes indicate Insights
        // predicates yet, so we surface the first tag verbatim and let the caller display.
        // When predicate filtering was applied (RequiredTags), we already know the
        // predicate — prefer it to avoid surfacing a stale "first tag" mismatch.
        var hits = ragResponse.Results
            .Select(r => new InsightsSearchHit(
                ChunkId: r.Id,
                ObservationId: r.DocumentId,
                DocumentName: r.DocumentName,
                Snippet: PickSnippet(r),
                Predicate: !string.IsNullOrWhiteSpace(request.Predicate)
                    ? request.Predicate
                    : r.Tags is { Count: > 0 } ? r.Tags[0] : null,
                Confidence: r.Score))
            .ToList();

        // Synthesis: only fabricate a summary when we have hits to ground against.
        // Empty result + empty summary is honest signal to the client ("no matches found")
        // and avoids hallucinated answers — matches the design.md FR-04 "synthesis with
        // grounded citations" contract (no grounding → no synthesis).
        string summary = string.Empty;
        if (hits.Count > 0)
        {
            summary = await SynthesizeGroundedSummaryAsync(
                request.Query,
                request.ParentEntityType,
                request.ParentEntityId,
                hits,
                cancellationToken);
        }
        else
        {
            _logger.LogInformation(
                "InsightsOrchestrator.SearchAsync: zero RAG hits for tenant {TenantId} subject {Scheme}:{Id} query length {QueryLength}; returning empty summary (no grounding available).",
                request.TenantId, request.ParentEntityType, request.ParentEntityId, request.Query.Length);
        }

        sw.Stop();

        _logger.LogInformation(
            "InsightsOrchestrator.SearchAsync completed for tenant {TenantId} subject {Scheme}:{Id}: hits={HitCount} synthesizedSummary={HasSummary} elapsedMs={ElapsedMs}",
            request.TenantId, request.ParentEntityType, request.ParentEntityId,
            hits.Count, !string.IsNullOrEmpty(summary), sw.ElapsedMilliseconds);

        return new InsightsSearchFacadeResult
        {
            Query = request.Query,
            Results = hits,
            Summary = summary,
            DurationMs = sw.ElapsedMilliseconds
        };
    }

    /// <summary>
    /// Pick a display snippet for a <see cref="RagSearchResult"/>: prefer the first
    /// highlight (semantic caption or content highlight) when available, otherwise fall
    /// back to the chunk Content truncated to <c>~280 chars</c>. We deliberately do NOT
    /// return the full chunk because (a) the UI doesn't need it and (b) it bloats the
    /// response payload for top-K hits where K can be up to 20.
    /// </summary>
    private static string PickSnippet(RagSearchResult result)
    {
        if (result.Highlights is { Count: > 0 })
        {
            return result.Highlights[0];
        }

        var content = result.Content ?? string.Empty;
        const int maxLen = 280;
        return content.Length <= maxLen ? content : content[..maxLen] + "…";
    }

    /// <summary>
    /// Synthesize a grounded summary from the ranked RAG hits, instructing the model to
    /// cite each claim using <c>[n]</c> tokens that index into <paramref name="hits"/>
    /// (1-based). Per ADR-019 we do not leak the raw prompt or model output details on
    /// failure — exceptions propagate to the orchestrator and surface as 500 to the
    /// caller.
    /// </summary>
    /// <remarks>
    /// <para>
    /// The prompt is intentionally terse and instruction-heavy: open-ended NL queries +
    /// Insights chunks tend to be short factual snippets, so a wordy system prompt
    /// would dilute the grounding signal. The "cite every claim" instruction is the
    /// only safeguard against ungrounded synthesis at this layer; the
    /// <see cref="PickSnippet(RagSearchResult)"/> truncation ensures we don't blow past
    /// model context limits for high-K queries.
    /// </para>
    /// <para>
    /// <b>Token budget</b>: we cap the LLM at 400 output tokens — enough for a 2–3
    /// paragraph answer with citations, short enough to keep P95 well under the 800ms
    /// budget design.md targets for the synthesis path.
    /// </para>
    /// </remarks>
    private async Task<string> SynthesizeGroundedSummaryAsync(
        string query,
        string parentEntityType,
        string parentEntityId,
        IReadOnlyList<InsightsSearchHit> hits,
        CancellationToken cancellationToken)
    {
        // Build the grounded-context block. Each hit is numbered [n] so the model can
        // cite them; 1-based indexing matches reader convention. Snippets are already
        // truncated by PickSnippet.
        var contextBuilder = new System.Text.StringBuilder();
        for (int i = 0; i < hits.Count; i++)
        {
            var hit = hits[i];
            contextBuilder
                .Append('[').Append(i + 1).Append("] ")
                .Append(hit.DocumentName)
                .Append(" — ")
                .Append(hit.Snippet)
                .AppendLine();
        }

        var prompt =
            "You are a legal research assistant answering questions about a specific " +
            $"{parentEntityType} (id: {parentEntityId}). " +
            "Answer the user's question using ONLY the numbered context snippets below. " +
            "Cite every factual claim with [n] referring to the snippet it came from. " +
            "If the snippets do not contain enough information to answer, say so plainly. " +
            "Do NOT fabricate facts not present in the snippets.\n\n" +
            $"Question: {query}\n\n" +
            "Context:\n" +
            contextBuilder.ToString() + "\n" +
            "Answer (with [n] citations):";

        // Single non-streaming LLM call — endpoint returns the whole response, so
        // streaming would just add complexity without latency benefit at this size.
        return await _openAi.GetCompletionAsync(
            prompt,
            model: null,            // use configured SummarizeModel
            maxOutputTokens: 400,
            cancellationToken: cancellationToken);
    }

    /// <summary>
    /// Enrich the caller-supplied Parameters with well-known template variables derived
    /// from the Subject ref, so playbook node ConfigJson can reference them as
    /// <c>{{matterId}}</c>, <c>{{projectId}}</c>, etc. without callers having to supply
    /// them redundantly alongside Subject. Phase 1 supports the <c>matter:</c> scheme;
    /// Phase 1.5 multi-entity work (Wave D5) extends to <c>project:</c> / <c>invoice:</c>.
    /// </summary>
    /// <remarks>
    /// Caller-supplied Parameters take precedence — if the caller explicitly supplied
    /// "matterId" the derived value does NOT overwrite it. This preserves the
    /// power-user override path while making the common case work without ceremony.
    /// Returns a NEW dictionary; never mutates the caller's collection.
    /// </remarks>
    internal static IReadOnlyDictionary<string, string>? EnrichParametersFromSubject(
        IReadOnlyDictionary<string, string>? callerParameters,
        string? subject)
    {
        if (string.IsNullOrWhiteSpace(subject))
            return callerParameters;

        var merged = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
        if (callerParameters is not null)
        {
            foreach (var kvp in callerParameters)
                merged[kvp.Key] = kvp.Value;
        }

        // Format: "<scheme>:<id>" — Phase 1 supports "matter:<guid>".
        var colonIdx = subject.IndexOf(':');
        if (colonIdx > 0 && colonIdx < subject.Length - 1)
        {
            var scheme = subject[..colonIdx].Trim().ToLowerInvariant();
            var id = subject[(colonIdx + 1)..].Trim();
            if (id.Length > 0)
            {
                // Well-known key per scheme. Caller-supplied value wins via TryAdd.
                var key = scheme switch
                {
                    "matter" => "matterId",
                    "project" => "projectId",
                    "invoice" => "invoiceId",
                    _ => null
                };
                if (key is not null && !merged.ContainsKey(key))
                    merged[key] = id;
            }
        }

        return merged;
    }
}
