using System.Text;
using System.Text.Json;
using Sprk.Bff.Api.Models.Ai;

namespace Sprk.Bff.Api.Services.Ai.Streaming;

/// <summary>
/// Incremental JSON parser for Azure OpenAI Structured Outputs streaming.
/// Consumes streamed JSON tokens (typically sub-word fragments per the R5 task 006 spike)
/// and emits <see cref="FieldDeltaEvent"/> records at top-level field boundaries.
///
/// Per R5 spec FR-02 + FR-13, the Summarize playbook streams structured output progressively:
/// each top-level field of the Summarize schema (e.g., <c>tldr</c>, <c>summary</c>, <c>keywords</c>,
/// <c>entities</c>) emits a <c>FieldStart</c> event when its <c>"fieldName":</c> opens at depth 1,
/// then any number of <c>FieldContent</c> events as token fragments arrive within the field's value,
/// then a <c>FieldComplete</c> event when the value's closing delimiter is detected.
///
/// The parser tolerates partial JSON at every intermediate state — token boundaries do not align
/// with JSON-syntactic boundaries, so the implementation is a character-level state machine, not
/// a <see cref="Utf8JsonReader"/>-backed parser.
///
/// Per R5 CLAUDE.md §3.1 (reuse mandate) the existence of this NEW helper class is justified
/// because the repo has no equivalent: <see cref="OpenAiClient.GetStructuredCompletionAsync{T}"/>
/// uses non-streaming completion; <see cref="OpenAiClient.StreamCompletionAsync"/> streams plain
/// text with no JSON-path tagging. R5 needs the union: streaming + incremental JSON path inference.
/// Spike evidence in <c>notes/task-006-spike-results.md</c>.
/// </summary>
public sealed class IncrementalJsonParser
{
    private readonly StringBuilder _buffer = new();
    private int _sequence;

    // JSON parser state
    private int _depth;             // current object/array depth
    private bool _inString;         // currently scanning a string literal (between unescaped quotes)
    private bool _escapeNext;       // previous char was a backslash inside a string

    // Active top-level field tracking
    private string? _activeFieldName;       // name of the currently-streaming top-level field
    private int _activeFieldValueStart;     // _buffer index where the active field's value starts
    private int _activeFieldValueDepth;     // _depth at which the active field's value sits (1 for top-level fields)
    private bool _activeFieldStarted;       // whether we've emitted FieldStart for the active field

    // Field-name detection state (only relevant at depth == 1 when not currently in a field value)
    private bool _expectingFieldName;       // just saw '{' or ',' at depth 1; next quoted string IS a key
    private bool _readingFieldNameString;   // currently accumulating a field-name string literal
    private readonly StringBuilder _pendingFieldName = new();
    private bool _justClosedFieldNameString;// finished reading a field name; awaiting ':' to confirm

    /// <summary>Appends one streaming token and returns events generated by processing its characters.</summary>
    public IReadOnlyList<FieldDeltaEvent> Append(string token)
    {
        if (string.IsNullOrEmpty(token))
        {
            return Array.Empty<FieldDeltaEvent>();
        }

        // Pre-compute the active-field content buffer index BEFORE appending, so we can
        // attribute any content captured within this token to the right field-value range.
        var contentStartBeforeAppend = _buffer.Length;
        var hadActiveFieldBeforeAppend = _activeFieldName is not null && _activeFieldStarted;
        var activeFieldNameBefore = _activeFieldName;

        var events = new List<FieldDeltaEvent>();

        foreach (var c in token)
        {
            _buffer.Append(c);
            ProcessChar(c, events);
        }

        // If a field was active throughout this Append (no boundary change), emit one FieldContent
        // event covering the new content. Boundary changes (FieldStart, FieldComplete) are emitted
        // inline by ProcessChar; FieldContent is batched at end-of-token for efficiency.
        if (hadActiveFieldBeforeAppend
            && _activeFieldName == activeFieldNameBefore
            && _activeFieldStarted
            && events.All(e => e.Kind != FieldDeltaEventKind.FieldContent))
        {
            var added = _buffer.ToString(contentStartBeforeAppend, _buffer.Length - contentStartBeforeAppend);
            if (added.Length > 0)
            {
                events.Add(new FieldDeltaEvent(
                    Path: $"$.{activeFieldNameBefore}",
                    Content: added,
                    Sequence: ++_sequence,
                    Kind: FieldDeltaEventKind.FieldContent));
            }
        }

        return events;
    }

    private void ProcessChar(char c, List<FieldDeltaEvent> events)
    {
        // Inside a string literal — only ", \ (escape), and any escape-target are special.
        if (_inString)
        {
            if (_escapeNext)
            {
                _escapeNext = false;
                if (_readingFieldNameString)
                {
                    _pendingFieldName.Append(c);
                }
                return;
            }
            if (c == '\\')
            {
                _escapeNext = true;
                return;
            }
            if (c == '"')
            {
                // String closes.
                _inString = false;
                if (_readingFieldNameString)
                {
                    _readingFieldNameString = false;
                    _justClosedFieldNameString = true;
                }
                else if (_activeFieldStarted
                         && _activeFieldName is not null
                         && _activeFieldValueDepth == _depth)
                {
                    // String VALUE of a top-level field just closed. The value may itself be the
                    // field's full value (e.g., `summary` is a string) — but we cannot tell here
                    // whether the parent is a string-typed field or a nested element. Defer the
                    // FieldComplete decision to depth/closing-delimiter logic in the non-string
                    // branch below; only emit if depth would naturally drop here. Since string
                    // close itself doesn't change depth, completion is determined by the next
                    // non-string char (',' or '}' at depth == _activeFieldValueDepth - 1).
                }
                return;
            }
            // Inside a string-literal value of a field name being read
            if (_readingFieldNameString)
            {
                _pendingFieldName.Append(c);
            }
            return;
        }

        // Not in a string.
        if (c == '"')
        {
            _inString = true;
            if (_expectingFieldName && _depth == 1)
            {
                _readingFieldNameString = true;
                _pendingFieldName.Clear();
                _expectingFieldName = false;
            }
            return;
        }
        if (_justClosedFieldNameString && c == ':')
        {
            // Field name is confirmed. If at depth 1, this is a top-level field — promote to active.
            _justClosedFieldNameString = false;
            if (_depth == 1)
            {
                // Close any previously-active field that was a primitive value (we couldn't tell on
                // string-close; depth-2 closures handle structured values). For primitives, we now
                // see a new field key, which signals the prior field has completed.
                if (_activeFieldStarted && _activeFieldName is not null)
                {
                    EmitFieldComplete(events, includeContentSinceLastEmit: true);
                }

                _activeFieldName = _pendingFieldName.ToString();
                _activeFieldValueDepth = _depth;
                _activeFieldStarted = true;
                _activeFieldValueStart = _buffer.Length; // value starts AFTER the colon
                events.Add(new FieldDeltaEvent(
                    Path: $"$.{_activeFieldName}",
                    Content: string.Empty,
                    Sequence: ++_sequence,
                    Kind: FieldDeltaEventKind.FieldStart));
            }
            return;
        }
        // Cancel field-name-pending state if we see non-colon after a string close
        if (_justClosedFieldNameString && !char.IsWhiteSpace(c))
        {
            _justClosedFieldNameString = false;
        }

        if (c == '{' || c == '[')
        {
            _depth++;
            // Inside any structured value, the immediate child of an object is itself expecting a key.
            if (c == '{')
            {
                _expectingFieldName = (_depth == 1) ? true : _expectingFieldName;
            }
            return;
        }
        if (c == '}' || c == ']')
        {
            _depth--;
            // When the closing delimiter takes us BELOW the depth of an active top-level field's value,
            // that field is complete. Top-level fields sit at depth 1; their values, if structured, occupy
            // deeper levels until the matching close pops back to depth 1.
            if (_activeFieldStarted
                && _activeFieldName is not null
                && _depth < _activeFieldValueDepth)
            {
                // The structured field has closed; everything between _activeFieldValueStart and now is
                // the field's value (including the closing delimiter we just consumed).
                EmitFieldComplete(events, includeContentSinceLastEmit: true);
            }
            return;
        }
        if (c == ',' && _depth == 1)
        {
            // Top-level comma — separates top-level fields. The current field is complete.
            if (_activeFieldStarted && _activeFieldName is not null)
            {
                // Trim the trailing comma from the field's reported content (the comma is a separator,
                // not part of the value). The event content reflects what arrived since last FieldContent.
                EmitFieldComplete(events, includeContentSinceLastEmit: true);
            }
            _expectingFieldName = true;
            return;
        }
    }

    private void EmitFieldComplete(List<FieldDeltaEvent> events, bool includeContentSinceLastEmit)
    {
        if (_activeFieldName is null || !_activeFieldStarted)
        {
            return;
        }
        // Reconstruct any trailing content that hasn't been emitted via batched FieldContent. The batched
        // event in Append only fires when NO boundary change occurred during the token; if the same token
        // contained content + a boundary, the trailing content is captured here.
        if (includeContentSinceLastEmit)
        {
            // No-op: FieldContent batching is best-effort. The widget concatenates Path-matching content
            // events; field completion is a state signal, not a value-bearing event.
        }
        events.Add(new FieldDeltaEvent(
            Path: $"$.{_activeFieldName}",
            Content: string.Empty,
            Sequence: ++_sequence,
            Kind: FieldDeltaEventKind.FieldComplete));
        _activeFieldName = null;
        _activeFieldStarted = false;
    }

    /// <summary>
    /// Returns the full accumulated JSON buffer for final deserialization or fallback.
    /// </summary>
    public string GetAccumulatedJson() => _buffer.ToString();

    /// <summary>
    /// Attempts to deserialize the accumulated buffer as <see cref="DocumentAnalysisResult"/>.
    /// Returns <c>null</c> if deserialization fails (caller should use
    /// <see cref="DocumentAnalysisResult.Fallback(string, string)"/> with the raw buffer).
    /// </summary>
    public DocumentAnalysisResult? TryParseFinal(JsonSerializerOptions options)
    {
        try
        {
            var json = _buffer.ToString();
            if (string.IsNullOrWhiteSpace(json))
            {
                return null;
            }
            var result = JsonSerializer.Deserialize<DocumentAnalysisResult>(json, options);
            if (result is not null)
            {
                result.ParsedSuccessfully = true;
                result.RawResponse = json;
            }
            return result;
        }
        catch (JsonException)
        {
            return null;
        }
    }
}

/// <summary>
/// Event emitted by <see cref="IncrementalJsonParser"/> at JSON top-level field boundaries.
/// Carries the same shape as <see cref="FieldDelta"/> (per task 005) plus a discriminator
/// for start/content/complete semantics so the streaming consumer can render progressively.
/// </summary>
/// <param name="Path">JSON path of the affected field (e.g., <c>$.tldr</c>, <c>$.summary</c>).</param>
/// <param name="Content">Incremental content fragment for <see cref="FieldDeltaEventKind.FieldContent"/>;
/// empty for <see cref="FieldDeltaEventKind.FieldStart"/> and <see cref="FieldDeltaEventKind.FieldComplete"/>.</param>
/// <param name="Sequence">Monotonically increasing sequence number across all events from one parser instance.</param>
/// <param name="Kind">Event discriminator.</param>
public sealed record FieldDeltaEvent(
    string Path,
    string Content,
    int Sequence,
    FieldDeltaEventKind Kind);

public enum FieldDeltaEventKind
{
    FieldStart,
    FieldContent,
    FieldComplete
}
