using FluentAssertions;
using Sprk.Bff.Api.Services.Ai;
using Xunit;

namespace Sprk.Bff.Api.Tests.Services.Ai;

/// <summary>
/// Unit tests for the R6 Pillar 2 task D-A-09 invocation context split:
/// <see cref="ToolInvocationContextBase"/> shared base, <see cref="ToolExecutionContext"/>
/// (playbook), and <see cref="ChatInvocationContext"/> (chat).
/// </summary>
public class InvocationContextTests
{
    // ------------------------------------------------------------------
    // ToolInvocationContextBase — base type semantics
    // ------------------------------------------------------------------

    [Fact]
    public void ToolExecutionContext_DerivesFromBase()
    {
        // Arrange
        var ctx = BuildPlaybookContext();

        // Assert — semantic test: derived from base
        ctx.Should().BeAssignableTo<ToolInvocationContextBase>(
            "ToolExecutionContext must derive from ToolInvocationContextBase per FR-09");
    }

    [Fact]
    public void ChatInvocationContext_DerivesFromBase()
    {
        // Arrange
        var ctx = BuildChatContext();

        // Assert
        ctx.Should().BeAssignableTo<ToolInvocationContextBase>(
            "ChatInvocationContext must derive from ToolInvocationContextBase per FR-09");
    }

    [Fact]
    public void ToolExecutionContext_AnalysisIdForwardsToBaseInvocationId()
    {
        // Arrange
        var analysisId = Guid.NewGuid();

        // Act
        var ctx = BuildPlaybookContext(analysisId: analysisId);

        // Assert — bidirectional forwarding preserves backward compat
        ctx.AnalysisId.Should().Be(analysisId);
        ctx.InvocationId.Should().Be(analysisId,
            "AnalysisId is sugar over InvocationId so the base correlation field is populated");
    }

    [Fact]
    public void ChatInvocationContext_DecisionIdAutoGenerated_WhenNotSupplied()
    {
        // Act
        var ctx = BuildChatContext();

        // Assert
        ctx.DecisionId.Should().NotBe(Guid.Empty,
            "DecisionId auto-generates so adapter does not have to supply it explicitly");
    }

    // ------------------------------------------------------------------
    // ToolExecutionContext — playbook field set preserved (NFR-08)
    // ------------------------------------------------------------------

    [Fact]
    public void ToolExecutionContext_PreservesAllPlaybookFields()
    {
        // Arrange
        var doc = BuildDocument();
        var skillCtx = "skill context";
        var knowCtx = "knowledge context";
        var actionPrompt = "action system prompt";

        // Act
        var ctx = new ToolExecutionContext
        {
            AnalysisId = Guid.NewGuid(),
            TenantId = "tenant-a",
            Document = doc,
            SkillContext = skillCtx,
            KnowledgeContext = knowCtx,
            ActionSystemPrompt = actionPrompt
        };

        // Assert — every playbook-specific field readable, semantics unchanged
        ctx.Document.Should().Be(doc);
        ctx.SkillContext.Should().Be(skillCtx);
        ctx.KnowledgeContext.Should().Be(knowCtx);
        ctx.ActionSystemPrompt.Should().Be(actionPrompt);
        ctx.PreviousResults.Should().NotBeNull().And.BeEmpty(
            "PreviousResults defaults to empty dictionary per pre-R6 contract");
    }

    [Fact]
    public void ToolExecutionContext_DefaultMaxTokens_MatchesPreR6Contract()
    {
        // Act
        var ctx = BuildPlaybookContext();

        // Assert — MaxTokens default preserved per NFR-08 (playbook semantics unchanged).
        ctx.MaxTokens.Should().Be(4096);
    }

    [Fact]
    public void ToolExecutionContext_DefaultTemperature_IsZero_PostHotfixBG9c1()
    {
        // Act
        var ctx = BuildPlaybookContext();

        // Assert — Hotfix Wave B-G9c1 (B6) lowered the default Temperature from 0.3 to 0.0
        // to match sibling structured methods (GetStructuredCompletionAsync<T>,
        // StreamStructuredCompletionAsync) which hardcode Temperature=0 for deterministic
        // JSON-shaped output. The per-action override flows through
        // sprk_analysisaction.sprk_temperature when set. NULL on the column = use this
        // 0.0 default. See projects/spaarke-ai-platform-unification-r6/notes/wave-b-g9c-medium-bugs.md
        // section B6.
        ctx.Temperature.Should().Be(0.0);
    }

    // ------------------------------------------------------------------
    // ChatInvocationContext — chat-specific field set (FR-09)
    // ------------------------------------------------------------------

    [Fact]
    public void ChatInvocationContext_ExposesChatSessionFields()
    {
        // Arrange
        var chatSessionId = Guid.NewGuid();
        var historyRef = "session-abc:history";
        var toolName = "summarize-document-for-chat";
        var argsJson = "{\"documentId\":\"doc-1\"}";
        var matterId = Guid.NewGuid();

        // Act
        var ctx = new ChatInvocationContext
        {
            ChatSessionId = chatSessionId,
            TenantId = "tenant-a",
            ConversationHistoryRef = historyRef,
            RequestedToolName = toolName,
            ToolArgumentsJson = argsJson,
            MatterId = matterId
        };

        // Assert
        ctx.ChatSessionId.Should().Be(chatSessionId);
        ctx.ConversationHistoryRef.Should().Be(historyRef);
        ctx.RequestedToolName.Should().Be(toolName);
        ctx.ToolArgumentsJson.Should().Be(argsJson);
        ctx.MatterId.Should().Be(matterId);
    }

    [Fact]
    public void ChatInvocationContext_AdrFifteenBinding_DoesNotExposeRawUserMessageContent()
    {
        // Assert — reflection sanity: no property on ChatInvocationContext named like
        // a raw-message field. Only handle/ref fields are exposed.
        var propNames = typeof(ChatInvocationContext)
            .GetProperties()
            .Select(p => p.Name)
            .ToList();

        propNames.Should().NotContain("UserMessage",
            "ADR-015 binding: never carry raw user message text on the chat invocation context");
        propNames.Should().NotContain("ConversationHistory",
            "ADR-015 binding: conversation history is referenced by handle (ConversationHistoryRef) only");
        propNames.Should().NotContain("MessageBody",
            "ADR-015 binding: no message-body field on the context type");

        propNames.Should().Contain("ConversationHistoryRef",
            "Conversation context exposed as handle only");
    }

    // ------------------------------------------------------------------
    // Polymorphic dispatch — adapter (task 010) precondition
    // ------------------------------------------------------------------

    [Fact]
    public void BothContexts_CanBeTreatedPolymorphicallyAsBase()
    {
        // Arrange
        var playbook = BuildPlaybookContext();
        var chat = BuildChatContext();

        // Act — code that only cares about shared identity can take base reference
        IReadOnlyList<ToolInvocationContextBase> ctxs = new ToolInvocationContextBase[]
        {
            playbook, chat
        };

        // Assert
        ctxs.Should().HaveCount(2);
        ctxs.Select(c => c.TenantId).Should().AllBe("tenant-a",
            "Shared TenantId field readable polymorphically");
    }

    // ------------------------------------------------------------------
    // Helpers
    // ------------------------------------------------------------------

    private static ToolExecutionContext BuildPlaybookContext(Guid? analysisId = null) =>
        new()
        {
            AnalysisId = analysisId ?? Guid.NewGuid(),
            TenantId = "tenant-a",
            Document = BuildDocument()
        };

    private static ChatInvocationContext BuildChatContext() =>
        new()
        {
            ChatSessionId = Guid.NewGuid(),
            TenantId = "tenant-a"
        };

    private static DocumentContext BuildDocument() => new()
    {
        DocumentId = Guid.NewGuid(),
        Name = "Doc",
        ExtractedText = "Sample"
    };
}
