using System.Text.Json;
using System.Text.Json.Serialization;

namespace Sprk.Bff.Api.Services.Ai.Builder;

/// <summary>
/// Represents a parsed tool call from the LLM response.
/// </summary>
public record BuilderToolCall
{
    /// <summary>
    /// Tool call ID from OpenAI (used for matching tool results).
    /// </summary>
    public required string Id { get; init; }

    /// <summary>
    /// Name of the tool being called (e.g., "add_node", "search_scopes").
    /// </summary>
    public required string ToolName { get; init; }

    /// <summary>
    /// Parsed arguments for the tool call.
    /// </summary>
    public required JsonDocument Arguments { get; init; }

    /// <summary>
    /// Raw arguments JSON string (for logging/debugging).
    /// </summary>
    public required string RawArguments { get; init; }
}

/// <summary>
/// Result of executing a builder tool.
/// </summary>
public record BuilderToolResult
{
    /// <summary>
    /// Tool call ID this result corresponds to.
    /// </summary>
    public required string ToolCallId { get; init; }

    /// <summary>
    /// Name of the tool that was executed.
    /// </summary>
    public required string ToolName { get; init; }

    /// <summary>
    /// Whether the tool execution succeeded.
    /// </summary>
    public required bool Success { get; init; }

    /// <summary>
    /// Result data (tool-specific).
    /// </summary>
    public JsonDocument? Result { get; init; }

    /// <summary>
    /// Error message if execution failed.
    /// </summary>
    public string? Error { get; init; }

    /// <summary>
    /// Canvas operations generated by this tool (for streaming to PCF).
    /// </summary>
    public IReadOnlyList<CanvasOperation>? CanvasOperations { get; init; }
}

/// <summary>
/// Represents a canvas operation to be sent to the PCF control.
/// </summary>
public record CanvasOperation
{
    /// <summary>
    /// Operation type: AddNode, RemoveNode, AddEdge, RemoveEdge, UpdateNode, UpdateLayout.
    /// </summary>
    public required CanvasOperationType Type { get; init; }

    /// <summary>
    /// Operation payload (node data, edge data, etc.).
    /// </summary>
    public required JsonDocument Payload { get; init; }
}

public enum CanvasOperationType
{
    AddNode,
    RemoveNode,
    AddEdge,
    RemoveEdge,
    UpdateNode,
    UpdateLayout,
    ValidateResult
}

#region Tool-Specific Argument Types

/// <summary>
/// Arguments for the add_node tool.
/// </summary>
public record AddNodeArguments
{
    [JsonPropertyName("nodeType")]
    public required string NodeType { get; init; }

    [JsonPropertyName("label")]
    public required string Label { get; init; }

    [JsonPropertyName("position")]
    public NodePosition? Position { get; init; }

    [JsonPropertyName("config")]
    public JsonDocument? Config { get; init; }
}

/// <summary>
/// Arguments for the remove_node tool.
/// </summary>
public record RemoveNodeArguments
{
    [JsonPropertyName("nodeId")]
    public string? NodeId { get; init; }

    [JsonPropertyName("nodeLabel")]
    public string? NodeLabel { get; init; }
}

/// <summary>
/// Arguments for the create_edge tool.
/// </summary>
public record CreateEdgeArguments
{
    [JsonPropertyName("sourceId")]
    public string? SourceId { get; init; }

    [JsonPropertyName("sourceLabel")]
    public string? SourceLabel { get; init; }

    [JsonPropertyName("targetId")]
    public string? TargetId { get; init; }

    [JsonPropertyName("targetLabel")]
    public string? TargetLabel { get; init; }

    [JsonPropertyName("label")]
    public string? Label { get; init; }

    [JsonPropertyName("edgeType")]
    public string? EdgeType { get; init; }
}

/// <summary>
/// Arguments for the update_node_config tool.
/// </summary>
public record UpdateNodeConfigArguments
{
    [JsonPropertyName("nodeId")]
    public string? NodeId { get; init; }

    [JsonPropertyName("nodeLabel")]
    public string? NodeLabel { get; init; }

    [JsonPropertyName("updates")]
    public required NodeUpdates Updates { get; init; }
}

public record NodeUpdates
{
    [JsonPropertyName("label")]
    public string? Label { get; init; }

    [JsonPropertyName("position")]
    public NodePosition? Position { get; init; }

    [JsonPropertyName("config")]
    public JsonDocument? Config { get; init; }
}

// Note: NodePosition is defined in IAiPlaybookBuilderService.cs as record NodePosition(double X, double Y)

/// <summary>
/// Arguments for the link_scope tool.
/// </summary>
public record LinkScopeArguments
{
    [JsonPropertyName("nodeId")]
    public string? NodeId { get; init; }

    [JsonPropertyName("nodeLabel")]
    public string? NodeLabel { get; init; }

    [JsonPropertyName("scopeType")]
    public required string ScopeType { get; init; }

    [JsonPropertyName("scopeId")]
    public string? ScopeId { get; init; }

    [JsonPropertyName("scopeName")]
    public string? ScopeName { get; init; }

    [JsonPropertyName("replaceExisting")]
    public bool ReplaceExisting { get; init; }
}

/// <summary>
/// Arguments for the create_scope tool.
/// </summary>
public record CreateScopeArguments
{
    [JsonPropertyName("scopeType")]
    public required string ScopeType { get; init; }

    [JsonPropertyName("name")]
    public required string Name { get; init; }

    [JsonPropertyName("displayName")]
    public required string DisplayName { get; init; }

    [JsonPropertyName("description")]
    public string? Description { get; init; }

    [JsonPropertyName("content")]
    public required JsonDocument Content { get; init; }

    [JsonPropertyName("metadata")]
    public ScopeMetadata? Metadata { get; init; }

    [JsonPropertyName("basedOnId")]
    public string? BasedOnId { get; init; }
}

public record ScopeMetadata
{
    [JsonPropertyName("tags")]
    public IReadOnlyList<string>? Tags { get; init; }

    [JsonPropertyName("documentTypes")]
    public IReadOnlyList<string>? DocumentTypes { get; init; }
}

/// <summary>
/// Arguments for the search_scopes tool.
/// </summary>
public record SearchScopesArguments
{
    [JsonPropertyName("scopeType")]
    public string? ScopeType { get; init; }

    [JsonPropertyName("query")]
    public string? Query { get; init; }

    [JsonPropertyName("semanticQuery")]
    public string? SemanticQuery { get; init; }

    [JsonPropertyName("filters")]
    public SearchFilters? Filters { get; init; }

    [JsonPropertyName("limit")]
    public int? Limit { get; init; }
}

public record SearchFilters
{
    [JsonPropertyName("ownerType")]
    public string? OwnerType { get; init; }

    [JsonPropertyName("documentTypes")]
    public IReadOnlyList<string>? DocumentTypes { get; init; }

    [JsonPropertyName("tags")]
    public IReadOnlyList<string>? Tags { get; init; }
}

/// <summary>
/// Arguments for the auto_layout tool.
/// </summary>
public record AutoLayoutArguments
{
    [JsonPropertyName("direction")]
    public string? Direction { get; init; }

    [JsonPropertyName("nodeSpacing")]
    public NodeSpacing? NodeSpacing { get; init; }

    [JsonPropertyName("selectedNodesOnly")]
    public bool? SelectedNodesOnly { get; init; }
}

public record NodeSpacing
{
    [JsonPropertyName("horizontal")]
    public double? Horizontal { get; init; }

    [JsonPropertyName("vertical")]
    public double? Vertical { get; init; }
}

/// <summary>
/// Arguments for the validate_canvas tool.
/// </summary>
public record ValidateCanvasArguments
{
    [JsonPropertyName("strictMode")]
    public bool? StrictMode { get; init; }

    [JsonPropertyName("validationRules")]
    public IReadOnlyList<string>? ValidationRules { get; init; }
}

#endregion

#region Tool Result Types

/// <summary>
/// Result of add_node operation.
/// </summary>
public record AddNodeResult
{
    [JsonPropertyName("nodeId")]
    public required string NodeId { get; init; }

    [JsonPropertyName("success")]
    public required bool Success { get; init; }
}

/// <summary>
/// Result of remove_node operation.
/// </summary>
public record RemoveNodeResult
{
    [JsonPropertyName("removedNodeId")]
    public required string RemovedNodeId { get; init; }

    [JsonPropertyName("removedEdgeIds")]
    public IReadOnlyList<string>? RemovedEdgeIds { get; init; }

    [JsonPropertyName("success")]
    public required bool Success { get; init; }
}

/// <summary>
/// Result of create_edge operation.
/// </summary>
public record CreateEdgeResult
{
    [JsonPropertyName("edgeId")]
    public required string EdgeId { get; init; }

    [JsonPropertyName("success")]
    public required bool Success { get; init; }
}

/// <summary>
/// Result of search_scopes operation.
/// </summary>
public record SearchScopesResult
{
    [JsonPropertyName("results")]
    public required IReadOnlyList<ScopeSearchResult> Results { get; init; }

    [JsonPropertyName("totalCount")]
    public required int TotalCount { get; init; }

    [JsonPropertyName("success")]
    public required bool Success { get; init; }
}

public record ScopeSearchResult
{
    [JsonPropertyName("scopeId")]
    public required string ScopeId { get; init; }

    [JsonPropertyName("name")]
    public required string Name { get; init; }

    [JsonPropertyName("displayName")]
    public required string DisplayName { get; init; }

    [JsonPropertyName("scopeType")]
    public required string ScopeType { get; init; }

    [JsonPropertyName("description")]
    public string? Description { get; init; }

    [JsonPropertyName("ownerType")]
    public string? OwnerType { get; init; }

    [JsonPropertyName("matchScore")]
    public double? MatchScore { get; init; }

    [JsonPropertyName("tags")]
    public IReadOnlyList<string>? Tags { get; init; }
}

/// <summary>
/// Result of create_scope operation.
/// </summary>
public record CreateScopeResult
{
    [JsonPropertyName("scopeId")]
    public required string ScopeId { get; init; }

    [JsonPropertyName("fullName")]
    public required string FullName { get; init; }

    [JsonPropertyName("success")]
    public required bool Success { get; init; }
}

/// <summary>
/// Result of validate_canvas operation.
/// </summary>
public record ValidateCanvasResult
{
    [JsonPropertyName("isValid")]
    public required bool IsValid { get; init; }

    [JsonPropertyName("errors")]
    public IReadOnlyList<ValidationIssue>? Errors { get; init; }

    [JsonPropertyName("warnings")]
    public IReadOnlyList<ValidationIssue>? Warnings { get; init; }

    [JsonPropertyName("summary")]
    public required ValidationSummary Summary { get; init; }
}

public record ValidationIssue
{
    [JsonPropertyName("code")]
    public required string Code { get; init; }

    [JsonPropertyName("message")]
    public required string Message { get; init; }

    [JsonPropertyName("nodeId")]
    public string? NodeId { get; init; }

    [JsonPropertyName("severity")]
    public string? Severity { get; init; }
}

public record ValidationSummary
{
    [JsonPropertyName("totalNodes")]
    public required int TotalNodes { get; init; }

    [JsonPropertyName("totalEdges")]
    public required int TotalEdges { get; init; }

    [JsonPropertyName("errorCount")]
    public required int ErrorCount { get; init; }

    [JsonPropertyName("warningCount")]
    public required int WarningCount { get; init; }
}

#endregion
