using System.Globalization;
using System.Text.Json;
using Microsoft.Extensions.Caching.Distributed;
using Sprk.Bff.Api.Api.Workspace.Models;
using Sprk.Bff.Api.Services.Ai;

namespace Sprk.Bff.Api.Services.Workspace;

/// <summary>
/// Aggregates portfolio metrics and builds a briefing response for the Quick Summary card
/// and briefing dialog (GET /api/workspace/briefing).
/// </summary>
/// <remarks>
/// Follows ADR-009: Redis-first caching with a 10-minute TTL.
/// Cache key pattern: "workspace:briefing:{userId}"
///
/// Deterministic metrics are always computed from portfolio data (via <see cref="PortfolioService"/>).
/// AI-enhanced narrative is an optional, progressive enhancement:
/// - Default: template-based narrative built from the metrics.
/// - Enhanced: rich contextual paragraphs generated by <see cref="IOpenAiClient"/> when available.
/// - Fallback: if AI fails or times out (3-second timeout), the template narrative is used instead.
///   The AI failure is logged but never surfaced to the caller.
///
/// The top-priority matter is selected as the active matter with the most overdue events
/// (deterministic rule — highest urgency indicator). When overdue event counts are equal,
/// the matter with the highest individual utilization is chosen.
/// </remarks>
public class BriefingService
{
    private readonly PortfolioService _portfolioService;
    private readonly IDistributedCache _cache;
    private readonly IOpenAiClient? _openAiClient;
    private readonly ILogger<BriefingService> _logger;

    private static readonly TimeSpan CacheTtl = TimeSpan.FromMinutes(10);
    private static readonly TimeSpan AiTimeout = TimeSpan.FromSeconds(3);

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNameCaseInsensitive = true
    };

    /// <summary>
    /// Initializes a new instance of <see cref="BriefingService"/>.
    /// </summary>
    /// <param name="portfolioService">Portfolio aggregation service providing Dataverse data.</param>
    /// <param name="cache">Distributed cache (Redis) for briefing data.</param>
    /// <param name="logger">Logger for diagnostics.</param>
    /// <param name="openAiClient">
    /// Optional AI client for enhanced narrative generation. When null or when AI feature flags
    /// are disabled, the service falls back to template-based narrative.
    /// </param>
    public BriefingService(
        PortfolioService portfolioService,
        IDistributedCache cache,
        ILogger<BriefingService> logger,
        IOpenAiClient? openAiClient = null)
    {
        _portfolioService = portfolioService ?? throw new ArgumentNullException(nameof(portfolioService));
        _cache = cache ?? throw new ArgumentNullException(nameof(cache));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        _openAiClient = openAiClient; // Nullable: AI is optional enhancement
    }

    /// <summary>
    /// Returns the briefing response for the specified user.
    /// Checks Redis cache first (10-minute TTL) before computing deterministic metrics
    /// and optionally enhancing the narrative with AI.
    /// </summary>
    /// <param name="userId">The Entra ID object ID of the authenticated user.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>Briefing response with metrics and narrative.</returns>
    public async Task<BriefingResponse> GetBriefingAsync(string userId, CancellationToken ct)
    {
        var cacheKey = $"workspace:briefing:{userId}";

        // 1. Check Redis cache first (ADR-009: Redis-first caching)
        var cached = await _cache.GetStringAsync(cacheKey, ct);
        if (cached is not null)
        {
            _logger.LogDebug(
                "Briefing cache hit. UserId={UserId}, CacheKey={CacheKey}",
                userId,
                cacheKey);

            var deserialized = JsonSerializer.Deserialize<BriefingResponse>(cached, JsonOptions);
            if (deserialized is not null)
                return deserialized;

            _logger.LogWarning(
                "Briefing cache entry deserialization returned null, recomputing. " +
                "UserId={UserId}, CacheKey={CacheKey}",
                userId,
                cacheKey);
        }

        _logger.LogDebug(
            "Briefing cache miss. UserId={UserId}, CacheKey={CacheKey}",
            userId,
            cacheKey);

        // 2. Compute deterministic base metrics via PortfolioService
        var portfolio = await _portfolioService.GetPortfolioSummaryAsync(userId, ct);
        var topMatter = await GetTopPriorityMatterAsync(userId, ct);

        // 3. Build template-based narrative (always available)
        var templateNarrative = BuildTemplateNarrative(portfolio, topMatter);
        var isAiEnhanced = false;
        var narrative = templateNarrative;

        // 4. Optionally enhance narrative with AI (3-second timeout, silent fallback)
        if (_openAiClient is not null)
        {
            (narrative, isAiEnhanced) = await TryGetAiNarrativeAsync(
                portfolio,
                topMatter,
                templateNarrative,
                ct);
        }

        // 5. Assemble response
        var result = new BriefingResponse(
            ActiveMatters: portfolio.ActiveMatters,
            TotalSpend: portfolio.TotalSpend,
            TotalBudget: portfolio.TotalBudget,
            UtilizationPercent: (double)portfolio.UtilizationPercent,
            MattersAtRisk: portfolio.MattersAtRisk,
            OverdueEvents: portfolio.OverdueEvents,
            TopPriorityMatter: topMatter,
            Narrative: narrative,
            IsAiEnhanced: isAiEnhanced,
            GeneratedAt: DateTimeOffset.UtcNow);

        // 6. Cache with 10-minute TTL (ADR-009)
        var serialized = JsonSerializer.Serialize(result, JsonOptions);
        await _cache.SetStringAsync(
            cacheKey,
            serialized,
            new DistributedCacheEntryOptions
            {
                AbsoluteExpirationRelativeToNow = CacheTtl
            },
            ct);

        _logger.LogDebug(
            "Briefing cached. UserId={UserId}, CacheKey={CacheKey}, " +
            "ActiveMatters={ActiveMatters}, IsAiEnhanced={IsAiEnhanced}",
            userId,
            cacheKey,
            result.ActiveMatters,
            result.IsAiEnhanced);

        return result;
    }

    // -------------------------------------------------------------------------
    // Private helpers
    // -------------------------------------------------------------------------

    /// <summary>
    /// Determines the top-priority matter for the user.
    /// Selection rule (deterministic):
    ///   1. Most overdue events (highest urgency indicator).
    ///   2. Tie-break: highest individual utilization percentage.
    /// Returns null when there are no active matters.
    /// </summary>
    private Task<TopMatterSummary?> GetTopPriorityMatterAsync(string userId, CancellationToken ct)
    {
        // TODO: Replace with actual Dataverse query when matter entity schema is finalized.
        // The query should retrieve active matters (statecode eq 0) and order by
        //   overdueeventcount DESC, (sprk_invoicedamount / sprk_budgetamount) DESC
        // returning: sprk_matterid, sprk_name, sprk_overdueeventcount,
        //            sprk_invoicedamount, sprk_budgetamount, sprk_duedate
        //
        // For now, return mock top-priority matter derived from mock portfolio data.
        _logger.LogInformation(
            "TODO: Querying top-priority matter from Dataverse. UserId={UserId} — returning mock data.",
            userId);

        // Mock: Matter C from PortfolioService mock data (3 overdue events → highest urgency)
        TopMatterSummary? topMatter = new(
            MatterId: Guid.Parse("00000000-0000-0000-0000-000000000003"),
            Name: "Matter C (at risk — overdue events)",
            Deadline: DateTimeOffset.UtcNow.AddDays(14),
            Reason: "Highest number of overdue events (3)");

        return Task.FromResult<TopMatterSummary?>(topMatter);
    }

    /// <summary>
    /// Builds a deterministic template-based narrative from portfolio metrics.
    /// This is always available as the fallback when AI is unavailable or fails.
    /// </summary>
    private static string BuildTemplateNarrative(
        PortfolioSummaryResponse portfolio,
        TopMatterSummary? topMatter)
    {
        var spend = portfolio.TotalSpend.ToString("C0", CultureInfo.CurrentCulture);
        var budget = portfolio.TotalBudget.ToString("C0", CultureInfo.CurrentCulture);
        var pct = ((double)portfolio.UtilizationPercent).ToString("F1", CultureInfo.InvariantCulture);

        var parts = new List<string>
        {
            $"You manage {portfolio.ActiveMatters} active matter{(portfolio.ActiveMatters == 1 ? "" : "s")} " +
            $"with {spend} of {budget} budget utilized ({pct}%)."
        };

        if (portfolio.MattersAtRisk > 0)
        {
            parts.Add(
                $"{portfolio.MattersAtRisk} matter{(portfolio.MattersAtRisk == 1 ? " is" : "s are")} at risk.");
        }
        else
        {
            parts.Add("No matters are currently at risk.");
        }

        if (portfolio.OverdueEvents > 0)
        {
            parts.Add(
                $"{portfolio.OverdueEvents} event{(portfolio.OverdueEvents == 1 ? " is" : "s are")} overdue.");
        }
        else
        {
            parts.Add("No events are overdue.");
        }

        if (topMatter is not null)
        {
            var deadlinePart = topMatter.Deadline.HasValue
                ? $" (due {topMatter.Deadline.Value:MMM d, yyyy})"
                : string.Empty;
            parts.Add($"Top priority: {topMatter.Name}{deadlinePart}.");
        }

        return string.Join(" ", parts);
    }

    /// <summary>
    /// Attempts to generate an AI-enhanced narrative via <see cref="IOpenAiClient"/>.
    /// Returns a tuple of (narrative, isAiEnhanced).
    /// Falls back to the template narrative on any failure or timeout.
    /// </summary>
    private async Task<(string Narrative, bool IsAiEnhanced)> TryGetAiNarrativeAsync(
        PortfolioSummaryResponse portfolio,
        TopMatterSummary? topMatter,
        string templateNarrative,
        CancellationToken ct)
    {
        try
        {
            using var cts = CancellationTokenSource.CreateLinkedTokenSource(ct);
            cts.CancelAfter(AiTimeout);

            var prompt = BuildAiPrompt(portfolio, topMatter);
            var aiNarrative = await _openAiClient!.GetCompletionAsync(prompt, cancellationToken: cts.Token);

            if (!string.IsNullOrWhiteSpace(aiNarrative))
            {
                _logger.LogDebug("AI narrative generated successfully for briefing.");
                return (aiNarrative.Trim(), true);
            }

            _logger.LogDebug("AI returned empty narrative; falling back to template.");
        }
        catch (OperationCanceledException) when (!ct.IsCancellationRequested)
        {
            // AI timed out (3-second timeout) — silent fallback, never block the response
            _logger.LogWarning(
                "AI narrative generation timed out after {Timeout}s; using template narrative.",
                AiTimeout.TotalSeconds);
        }
        catch (Exception ex)
        {
            // Any AI failure — silent fallback per spec constraint
            _logger.LogWarning(
                ex,
                "AI narrative generation failed; using template narrative.");
        }

        return (templateNarrative, false);
    }

    /// <summary>
    /// Builds a structured prompt for AI narrative generation.
    /// The prompt is designed to produce a concise, professional 2-3 sentence briefing.
    /// </summary>
    private static string BuildAiPrompt(
        PortfolioSummaryResponse portfolio,
        TopMatterSummary? topMatter)
    {
        var spend = portfolio.TotalSpend.ToString("C0", CultureInfo.CurrentCulture);
        var budget = portfolio.TotalBudget.ToString("C0", CultureInfo.CurrentCulture);
        var pct = ((double)portfolio.UtilizationPercent).ToString("F1", CultureInfo.InvariantCulture);

        var topMatterLine = topMatter is not null
            ? $"Top priority matter: {topMatter.Name}" +
              (topMatter.Deadline.HasValue ? $" (due {topMatter.Deadline.Value:MMM d, yyyy})" : string.Empty) + "."
            : "No specific top-priority matter identified.";

        return $"""
            You are a legal operations AI assistant. Write a concise, professional 2-3 sentence portfolio briefing
            for a legal operations manager based on the following portfolio data. Focus on actionable insights.

            Portfolio data:
            - Active matters: {portfolio.ActiveMatters}
            - Total spend: {spend} of {budget} budget ({pct}% utilized)
            - Matters at risk: {portfolio.MattersAtRisk}
            - Overdue events: {portfolio.OverdueEvents}
            - {topMatterLine}

            Write the briefing as plain prose (no bullet points, no headings). Keep it under 100 words.
            """;
    }
}
