using System.Globalization;
using System.Text;
using System.Text.Json;
using Microsoft.Extensions.Caching.Distributed;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Query;
using Spaarke.Dataverse;
using Sprk.Bff.Api.Api.Workspace.Models;
using Sprk.Bff.Api.Services.Ai.Membership;
using Sprk.Bff.Api.Services.Ai.PublicContracts;
using Sprk.Bff.Api.Services.Communication;

namespace Sprk.Bff.Api.Services.Workspace;

/// <summary>
/// Aggregates portfolio metrics and builds a briefing response for the Quick Summary card
/// and briefing dialog (GET /api/workspace/briefing).
/// </summary>
/// <remarks>
/// Follows ADR-009: Redis-first caching with a 10-minute TTL.
/// Cache key pattern: "workspace:briefing:{userId}"
///
/// Deterministic metrics are always computed from portfolio data (via <see cref="PortfolioService"/>).
/// AI-enhanced narrative is an optional, progressive enhancement:
/// - Default: template-based narrative built from the metrics.
/// - Enhanced: rich contextual paragraphs generated by <see cref="IBriefingAi"/> when available.
/// - Fallback: if AI fails or times out (3-second timeout), the template narrative is used instead.
///   The AI failure is logged but never surfaced to the caller.
///
/// Per refined ADR-013 (2026-05-20, task 046), this service consumes AI through the
/// <see cref="IBriefingAi"/> public facade rather than injecting AI-internal types
/// directly. The facade preserves AI-internal flexibility (model swaps, streaming
/// policy changes) without rippling through CRUD code.
///
/// The top-priority matter is selected as the active matter with the most overdue events
/// (deterministic rule — highest urgency indicator). When overdue event counts are equal,
/// the matter with the highest individual utilization is chosen. The candidate matter set
/// is derived from <see cref="IMembershipResolverService"/> per ADR-034 (canonical
/// user-record membership mechanism): the caller's AAD <c>oid</c> is cross-referenced to
/// the Dataverse <c>systemuserid</c> (mirroring <c>MembershipEndpoints.ResolveSystemUserIdAsync</c>
/// per ADR-028), and the resolver returns the <c>sprk_matter</c> rows the user is a member
/// of (across all roles: owner, owningTeam, assignedAttorney, assignedLawFirm, etc.). The
/// "top-priority" heuristic is then applied to the resolved candidate set. When the user
/// has zero memberships, no AAD-oid is resolvable, or any membership/Dataverse failure
/// occurs, the service returns <c>null</c> for <see cref="TopMatterSummary"/> — the
/// briefing degrades gracefully rather than failing the response.
/// </remarks>
public class BriefingService
{
    private readonly PortfolioService _portfolioService;
    private readonly IDistributedCache _cache;
    private readonly IMembershipResolverService _membershipResolver;
    private readonly IDataverseService _dataverse;
    private readonly IImpersonatedCommunicationQuery _callerQuery;
    private readonly IBriefingAi? _briefingAi;
    private readonly ILogger<BriefingService> _logger;

    private static readonly TimeSpan CacheTtl = TimeSpan.FromMinutes(10);
    private static readonly TimeSpan AiTimeout = TimeSpan.FromSeconds(3);

    /// <summary>
    /// TTL for the AAD-oid → systemuserid cache used by the top-priority-matter resolver.
    /// Mirrors <c>MembershipEndpoints.CurrentUserCacheTtl</c> (10 minutes) so a freshly
    /// disabled user surfaces as a missing matter within at most 10 minutes.
    /// </summary>
    private static readonly TimeSpan CurrentUserCacheTtl = TimeSpan.FromMinutes(10);

    /// <summary>
    /// Cache key prefix for AAD-oid → systemuserid lookups performed by this service.
    /// Sibling namespace to <c>MembershipEndpoints.CurrentUserCacheKeyPrefix</c>
    /// (<c>"membership:currentuser:"</c>) — separate prefix so a future per-namespace
    /// invalidation does not have to coordinate with the membership endpoint's cache.
    /// Both share the <c>membership:*</c> root so a bulk <c>membership:*</c> wipe clears
    /// both.
    /// </summary>
    private const string CurrentUserCacheKeyPrefix = "membership:briefing-currentuser:";

    /// <summary>The Dataverse logical name of the entity whose membership drives the
    /// top-priority-matter selection. ADR-034 canonical name.</summary>
    private const string MatterEntityLogicalName = "sprk_matter";

    private static readonly JsonSerializerOptions JsonOptions = new()
    {
        PropertyNameCaseInsensitive = true
    };

    /// <summary>
    /// Initializes a new instance of <see cref="BriefingService"/>.
    /// </summary>
    /// <param name="portfolioService">Portfolio aggregation service providing Dataverse data.</param>
    /// <param name="cache">Distributed cache (Redis) for briefing data + AAD-oid lookup.</param>
    /// <param name="membershipResolver">
    /// Canonical user-record membership resolver (ADR-034). Used to enumerate the
    /// <c>sprk_matter</c> rows the caller is a member of as the candidate set for the
    /// top-priority-matter heuristic.
    /// </param>
    /// <param name="dataverse">
    /// Dataverse service used for (a) the AAD-oid → systemuserid cross-reference (per
    /// ADR-028) and (b) retrieving matter details (overdue event count, utilization,
    /// deadline) for the resolved candidate set.
    /// </param>
    /// <param name="callerQuery">
    /// unified-access-control-r2 task 152: the existing caller-context read seam (MSCRMCallerID = the caller). The
    /// top-priority matter's detail row is read AS THE CALLER so Dataverse trims a matter the caller cannot open.
    /// </param>
    /// <param name="logger">Logger for diagnostics.</param>
    /// <param name="briefingAi">
    /// Optional AI facade for enhanced narrative generation. When null or when AI feature flags
    /// are disabled, the service falls back to template-based narrative.
    /// </param>
    public BriefingService(
        PortfolioService portfolioService,
        IDistributedCache cache,
        IMembershipResolverService membershipResolver,
        IDataverseService dataverse,
        IImpersonatedCommunicationQuery callerQuery,
        ILogger<BriefingService> logger,
        IBriefingAi? briefingAi = null)
    {
        _portfolioService = portfolioService ?? throw new ArgumentNullException(nameof(portfolioService));
        _cache = cache ?? throw new ArgumentNullException(nameof(cache));
        _membershipResolver = membershipResolver ?? throw new ArgumentNullException(nameof(membershipResolver));
        _dataverse = dataverse ?? throw new ArgumentNullException(nameof(dataverse));
        _callerQuery = callerQuery ?? throw new ArgumentNullException(nameof(callerQuery));
        _logger = logger ?? throw new ArgumentNullException(nameof(logger));
        _briefingAi = briefingAi; // Nullable: AI is optional enhancement
    }

    /// <summary>
    /// Returns the briefing response for the specified user.
    /// Checks Redis cache first (10-minute TTL) before computing deterministic metrics
    /// and optionally enhancing the narrative with AI.
    /// </summary>
    /// <param name="userId">The Entra ID object ID of the authenticated user.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>Briefing response with metrics and narrative.</returns>
    public async Task<BriefingResponse> GetBriefingAsync(string userId, CancellationToken ct)
    {
        var cacheKey = $"workspace:briefing:{userId}";

        // 1. Check Redis cache first (ADR-009: Redis-first caching)
        var cached = await _cache.GetStringAsync(cacheKey, ct);
        if (cached is not null)
        {
            _logger.LogDebug(
                "Briefing cache hit. UserId={UserId}, CacheKey={CacheKey}",
                userId,
                cacheKey);

            var deserialized = JsonSerializer.Deserialize<BriefingResponse>(cached, JsonOptions);
            if (deserialized is not null)
                return deserialized;

            _logger.LogWarning(
                "Briefing cache entry deserialization returned null, recomputing. " +
                "UserId={UserId}, CacheKey={CacheKey}",
                userId,
                cacheKey);
        }

        _logger.LogDebug(
            "Briefing cache miss. UserId={UserId}, CacheKey={CacheKey}",
            userId,
            cacheKey);

        // 2. Compute deterministic base metrics via PortfolioService
        var portfolio = await _portfolioService.GetPortfolioSummaryAsync(userId, ct);
        var (topMatter, topMatterUnavailable) = await GetTopPriorityMatterAsync(userId, ct);

        // 3. Build template-based narrative (always available)
        var templateNarrative = BuildTemplateNarrative(portfolio, topMatter);
        var isAiEnhanced = false;
        var narrative = templateNarrative;

        // 4. Optionally enhance narrative with AI (3-second timeout, silent fallback)
        if (_briefingAi is not null)
        {
            (narrative, isAiEnhanced) = await TryGetAiNarrativeAsync(
                portfolio,
                topMatter,
                templateNarrative,
                ct);
        }

        // 5. Assemble response
        var result = new BriefingResponse(
            ActiveMatters: portfolio.ActiveMatters,
            TotalSpend: portfolio.TotalSpend,
            TotalBudget: portfolio.TotalBudget,
            UtilizationPercent: (double)portfolio.UtilizationPercent,
            MattersAtRisk: portfolio.MattersAtRisk,
            OverdueEvents: portfolio.OverdueEvents,
            TopPriorityMatter: topMatter,
            Narrative: narrative,
            IsAiEnhanced: isAiEnhanced,
            GeneratedAt: DateTimeOffset.UtcNow,
            TopPriorityMatterUnavailable: topMatterUnavailable);

        // 6. Cache with 10-minute TTL (ADR-009)
        var serialized = JsonSerializer.Serialize(result, JsonOptions);
        await _cache.SetStringAsync(
            cacheKey,
            serialized,
            new DistributedCacheEntryOptions
            {
                AbsoluteExpirationRelativeToNow = CacheTtl
            },
            ct);

        _logger.LogDebug(
            "Briefing cached. UserId={UserId}, CacheKey={CacheKey}, " +
            "ActiveMatters={ActiveMatters}, IsAiEnhanced={IsAiEnhanced}",
            userId,
            cacheKey,
            result.ActiveMatters,
            result.IsAiEnhanced);

        return result;
    }

    // -------------------------------------------------------------------------
    // Private helpers
    // -------------------------------------------------------------------------

    /// <summary>
    /// Determines the top-priority matter for the user: among the matters FOR the user (ADR-034 A3 people-targeting
    /// surface) that the user can READ (caller-context read), the one with the most overdue tasks.
    /// </summary>
    /// <remarks>
    /// <para>
    /// Pipeline:
    ///   1. Parse <paramref name="userId"/> as an AAD <c>oid</c> (Guid). Non-Guid inputs
    ///      (e.g., legacy test identities) log Warning + return null — no crash.
    ///   2. Cross-reference AAD-oid → Dataverse <c>systemuserid</c> via the
    ///      <c>systemuser.azureactivedirectoryobjectid</c> column (ADR-028), cached
    ///      <see cref="CurrentUserCacheTtl"/>. Unprovisioned users return null.
    ///   3. <see cref="IMembershipResolverService.ResolveAsync"/> for <see cref="MatterEntityLogicalName"/> with
    ///      <see cref="MembershipResolveOptions.People"/> (task 152): the matters the user CREATED (human Created By),
    ///      is NAMED on ("Assigned *", through the linked contact) or personally OWNS. A team- or BU-owned matter
    ///      that names nobody is NOT a candidate — before task 152 the default surface made every same-BU user a
    ///      candidate for it through the BU default team. Zero candidates → null.
    ///   4. Read the candidates' detail rows AND their overdue open tasks AS THE CALLER
    ///      (<see cref="IImpersonatedCommunicationQuery"/>), chunked, so Dataverse drops any matter the caller cannot
    ///      open (owner D1). No app-only fallback.
    ///   5. Apply the deterministic heuristic: max overdue tasks; tie-break on highest utilization
    ///      (<c>spend / budget</c>); final tie-break on matter name (alphabetical).
    /// </para>
    /// <para>
    /// Failure semantics (task 152, ADR-003): a failed people resolution or caller-context read returns
    /// <c>Unavailable = true</c> — the response carries <c>TopPriorityMatterUnavailable</c>, so "could not be
    /// determined" is distinguishable from "you have no matters". Cancellation is always propagated.
    /// </para>
    /// <para>
    /// ⚠️ Corrected by task 152 (verified against live <c>sprk_matter</c> metadata, 2026-10-02): the detail query used
    /// to select <c>sprk_name</c>, <c>sprk_overdueeventcount</c>, <c>sprk_totalspend</c> and <c>sprk_duedate</c> —
    /// none of which exist on <c>sprk_matter</c> — so it always threw and the top matter was always null. It now
    /// reads <c>sprk_mattername</c>, <c>sprk_totalspendtodate</c> and <c>sprk_totalbudget</c>, and COUNTS overdue
    /// open tasks from <c>sprk_event</c> (there is no stored count). <c>sprk_matter</c> has no deadline column, so
    /// <see cref="TopMatterSummary.Deadline"/> is null.
    /// </para>
    /// </remarks>
    private async Task<(TopMatterSummary? Matter, bool Unavailable)> GetTopPriorityMatterAsync(string userId, CancellationToken ct)
    {
        // Step 1 — Parse AAD oid. Test fixtures use non-Guid sentinels; degrade gracefully.
        if (!Guid.TryParse(userId, out var aadObjectId) || aadObjectId == Guid.Empty)
        {
            _logger.LogWarning(
                "Top-priority matter resolution skipped: userId '{UserId}' is not a parseable AAD oid Guid. " +
                "Returning null TopMatterSummary.",
                userId);
            return (null, false);
        }

        Guid systemUserId;
        try
        {
            var resolved = await ResolveSystemUserIdAsync(aadObjectId, ct).ConfigureAwait(false);
            if (resolved is null)
            {
                _logger.LogInformation(
                    "Top-priority matter resolution: AAD oid={AadObjectId} has no provisioned systemuser row. " +
                    "Returning null TopMatterSummary.",
                    aadObjectId);
                return (null, false);
            }
            systemUserId = resolved.Value;
        }
        catch (OperationCanceledException) when (ct.IsCancellationRequested)
        {
            throw;
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex,
                "Top-priority matter resolution: AAD-oid → systemuserid cross-reference failed " +
                "for AadObjectId={AadObjectId}. TopPriorityMatterUnavailable.",
                aadObjectId);
            return (null, true);
        }

        // Step 3 — the matters FOR the user (ADR-034 A3 people-targeting surface).
        Sprk.Bff.Api.Services.Ai.Membership.Models.MembershipResponse memberships;
        try
        {
            memberships = await _membershipResolver
                .ResolveAsync(systemUserId, MatterEntityLogicalName, MembershipResolveOptions.People, ct)
                .ConfigureAwait(false);
        }
        catch (OperationCanceledException) when (ct.IsCancellationRequested)
        {
            throw;
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex,
                "Top-priority matter resolution: people-targeting resolution failed for SystemUserId={SystemUserId}. " +
                "TopPriorityMatterUnavailable (fail closed, no app-only fallback).",
                systemUserId);
            return (null, true);
        }

        if (memberships.Count == 0)
        {
            _logger.LogDebug(
                "Top-priority matter resolution: SystemUserId={SystemUserId} has no matters targeted to them. " +
                "Returning null TopMatterSummary.",
                systemUserId);
            return (null, false);
        }

        // Step 4 — detail rows + overdue counts, read AS THE CALLER.
        IReadOnlyList<MatterDetailRow> matters;
        try
        {
            matters = await QueryMatterDetailsAsync(memberships.Ids, systemUserId, ct).ConfigureAwait(false);
        }
        catch (OperationCanceledException) when (ct.IsCancellationRequested)
        {
            throw;
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex,
                "Top-priority matter resolution: the caller-context read of matter details failed for " +
                "SystemUserId={SystemUserId} (candidate count={Count}). TopPriorityMatterUnavailable — never answered app-only.",
                systemUserId, memberships.Count);
            return (null, true);
        }

        if (matters.Count == 0)
        {
            return (null, false);
        }

        // Step 5 — Apply the deterministic heuristic.
        var winner = matters
            .OrderByDescending(m => m.OverdueEventCount)
            .ThenByDescending(m => m.BudgetAmount > 0 ? m.InvoicedAmount / m.BudgetAmount : 0m)
            .ThenBy(m => m.Name, StringComparer.OrdinalIgnoreCase)
            .First();

        var reason = BuildTopMatterReason(winner);

        _logger.LogDebug(
            "Top-priority matter resolved: MatterId={MatterId}, OverdueEvents={Overdue}, " +
            "Utilization={Util:F1}% (SystemUserId={SystemUserId}, candidates={Count}).",
            winner.Id,
            winner.OverdueEventCount,
            winner.BudgetAmount > 0 ? (double)(winner.InvoicedAmount / winner.BudgetAmount * 100m) : 0d,
            systemUserId,
            matters.Count);

        return (new TopMatterSummary(
            MatterId: winner.Id,
            Name: winner.Name,
            Deadline: winner.Deadline,
            Reason: reason), false);
    }

    /// <summary>
    /// Cross-references an AAD <c>oid</c> (Entra ID object id) to a Dataverse
    /// <c>systemuserid</c> via the <c>systemuser.azureactivedirectoryobjectid</c> column
    /// (per ADR-028). Result is cached in <see cref="IDistributedCache"/> for
    /// <see cref="CurrentUserCacheTtl"/>.
    /// </summary>
    /// <remarks>
    /// Algorithm mirrors <c>MembershipEndpoints.ResolveSystemUserIdAsync</c> (an internal
    /// helper duplicated here to avoid coupling the Workspace surface to the Membership
    /// endpoint module). A future R4 task may extract both into a shared
    /// <c>ICurrentUserResolver</c> once a third consumer needs the same lookup.
    /// </remarks>
    private async Task<Guid?> ResolveSystemUserIdAsync(Guid aadObjectId, CancellationToken ct)
    {
        var cacheKey = CurrentUserCacheKeyPrefix + aadObjectId.ToString("D");

        // Cache lookup — fail-open on read errors.
        try
        {
            var cached = await _cache.GetAsync(cacheKey, ct).ConfigureAwait(false);
            if (cached is not null && cached.Length == 16)
            {
                var cachedGuid = new Guid(cached);
                if (cachedGuid != Guid.Empty)
                {
                    return cachedGuid;
                }
            }
        }
        catch (OperationCanceledException)
        {
            throw;
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex,
                "BriefingService: AAD-oid cache read failed for {CacheKey}; falling through to live resolve.",
                cacheKey);
        }

        // Live cross-reference via systemuser.azureactivedirectoryobjectid (ADR-028).
        var query = new QueryExpression("systemuser")
        {
            ColumnSet = new ColumnSet("systemuserid"),
            TopCount = 1,
            NoLock = true
        };
        query.Criteria.AddCondition(
            "azureactivedirectoryobjectid",
            ConditionOperator.Equal,
            aadObjectId);
        // Exclude disabled users — see MembershipEndpoints.ResolveSystemUserIdAsync rationale.
        query.Criteria.AddCondition(
            "isdisabled",
            ConditionOperator.Equal,
            false);

        var results = await _dataverse.RetrieveMultipleAsync(query, ct).ConfigureAwait(false);
        if (results.Entities.Count == 0)
        {
            return null;
        }

        var systemUserId = results.Entities[0].Id;
        if (systemUserId == Guid.Empty)
        {
            return null;
        }

        // Cache write — fail-open on write errors.
        try
        {
            await _cache.SetAsync(
                cacheKey,
                systemUserId.ToByteArray(),
                new DistributedCacheEntryOptions { AbsoluteExpirationRelativeToNow = CurrentUserCacheTtl },
                ct).ConfigureAwait(false);
        }
        catch (OperationCanceledException)
        {
            throw;
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex,
                "BriefingService: AAD-oid cache write failed for {CacheKey}; next call will re-resolve.",
                cacheKey);
        }

        return systemUserId;
    }

    /// <summary>
    /// The most candidate ids bound into ONE caller-context GET (task 152) — keeps each query near 4 KB, far under the
    /// Web API URL limit. A failed chunk fails the whole read (it never shrinks the candidate set).
    /// </summary>
    internal const int MaxIdsPerImpersonatedRequest = 50;

    /// <summary>sprk_event type id for Task — same constant the Daily Briefing collector and TaskActionCore use.</summary>
    private const string EventTypeTask = "124f5fc9-98ff-f011-8406-7c1e525abd8b";

    /// <summary>
    /// Reads the candidate matters' detail rows and their overdue open-task counts AS THE CALLER, chunked. Matters the
    /// caller cannot read are absent from the result (Dataverse trims them). Throws on any failed read — the caller
    /// reports TopPriorityMatterUnavailable; there is no app-only path.
    /// </summary>
    private async Task<IReadOnlyList<MatterDetailRow>> QueryMatterDetailsAsync(
        IReadOnlyList<Guid> matterIds,
        Guid callerSystemUserId,
        CancellationToken ct)
    {
        if (matterIds.Count == 0)
        {
            return Array.Empty<MatterDetailRow>();
        }

        var details = new Dictionary<Guid, Dictionary<string, JsonElement>>();
        var overdue = new Dictionary<Guid, int>();
        // "Overdue" = due before today (on or before yesterday), UTC.
        var yesterday = DateTime.UtcNow.Date.AddDays(-1).ToString("yyyy-MM-dd", CultureInfo.InvariantCulture);

        foreach (var chunk in matterIds.Distinct().Chunk(MaxIdsPerImpersonatedRequest))
        {
            // Active candidate matters, as the caller.
            var matterClause = string.Join(" or ", chunk.Select(id => $"sprk_matterid eq {id:D}"));
            var matterRows = await _callerQuery.QueryAsync(
                "sprk_matters",
                "$select=sprk_matterid,sprk_mattername,sprk_totalspendtodate,sprk_totalbudget"
                + $"&$filter=statecode eq 0 and ({matterClause})",
                callerSystemUserId,
                ct).ConfigureAwait(false);

            foreach (var row in matterRows)
            {
                if (ReadGuid(row, "sprk_matterid") is { } id)
                {
                    details.TryAdd(id, row);
                }
            }

            // Open Task events on those matters whose due date has passed, as the caller. Counted here — sprk_matter
            // has no stored overdue count.
            var regardingClause = string.Join(" or ", chunk.Select(id => $"_sprk_regardingmatter_value eq {id:D}"));
            var eventRows = await _callerQuery.QueryAsync(
                "sprk_events",
                "$select=sprk_eventid,_sprk_regardingmatter_value"
                + $"&$filter=_sprk_eventtype_ref_value eq {EventTypeTask} and statecode eq 0"
                + $" and Microsoft.Dynamics.CRM.OnOrBefore(PropertyName='sprk_duedate',PropertyValue='{yesterday}')"
                + $" and ({regardingClause})",
                callerSystemUserId,
                ct).ConfigureAwait(false);

            foreach (var row in eventRows)
            {
                if (ReadGuid(row, "_sprk_regardingmatter_value") is { } matterId)
                {
                    overdue[matterId] = overdue.TryGetValue(matterId, out var n) ? n + 1 : 1;
                }
            }
        }

        var rows = new List<MatterDetailRow>(details.Count);
        foreach (var (id, row) in details)
        {
            rows.Add(new MatterDetailRow
            {
                Id = id,
                Name = ReadString(row, "sprk_mattername") ?? string.Empty,
                OverdueEventCount = overdue.TryGetValue(id, out var count) ? count : 0,
                InvoicedAmount = ReadDecimal(row, "sprk_totalspendtodate"),
                BudgetAmount = ReadDecimal(row, "sprk_totalbudget"),
                // sprk_matter carries no deadline column (live metadata, 2026-10-02).
                Deadline = null,
            });
        }

        return rows;
    }

    private static string? ReadString(Dictionary<string, JsonElement> row, string key) =>
        row.TryGetValue(key, out var el) && el.ValueKind == JsonValueKind.String ? el.GetString() : null;

    private static Guid? ReadGuid(Dictionary<string, JsonElement> row, string key) =>
        Guid.TryParse(ReadString(row, key), out var g) && g != Guid.Empty ? g : null;

    private static decimal ReadDecimal(Dictionary<string, JsonElement> row, string key) =>
        row.TryGetValue(key, out var el) && el.ValueKind == JsonValueKind.Number && el.TryGetDecimal(out var d) ? d : 0m;

    /// <summary>
    /// Builds a human-readable reason string for the selected top-priority matter.
    /// Mirrors the prior STUB phrasing so downstream UI / narrative consumers see a
    /// consistent shape; the data is now real.
    /// </summary>
    private static string BuildTopMatterReason(MatterDetailRow winner)
    {
        if (winner.OverdueEventCount > 0)
        {
            return $"Highest number of overdue events ({winner.OverdueEventCount}).";
        }

        if (winner.BudgetAmount > 0)
        {
            var utilPct = (double)(winner.InvoicedAmount / winner.BudgetAmount * 100m);
            return $"Highest budget utilization ({utilPct.ToString("F1", CultureInfo.InvariantCulture)}%).";
        }

        return "Top matter from your membership set.";
    }

    /// <summary>
    /// Internal projection of a Dataverse <c>sprk_matter</c> row carrying just the
    /// fields needed to apply the top-priority heuristic.
    /// </summary>
    private sealed class MatterDetailRow
    {
        public Guid Id { get; init; }
        public string Name { get; init; } = string.Empty;
        public int OverdueEventCount { get; init; }
        public decimal InvoicedAmount { get; init; }
        public decimal BudgetAmount { get; init; }
        public DateTimeOffset? Deadline { get; init; }
    }

    /// <summary>
    /// Builds a deterministic template-based narrative from portfolio metrics.
    /// This is always available as the fallback when AI is unavailable or fails.
    /// </summary>
    private static string BuildTemplateNarrative(
        PortfolioSummaryResponse portfolio,
        TopMatterSummary? topMatter)
    {
        var spend = portfolio.TotalSpend.ToString("C0", CultureInfo.CurrentCulture);
        var budget = portfolio.TotalBudget.ToString("C0", CultureInfo.CurrentCulture);
        var pct = ((double)portfolio.UtilizationPercent).ToString("F1", CultureInfo.InvariantCulture);

        var parts = new List<string>
        {
            $"You manage {portfolio.ActiveMatters} active matter{(portfolio.ActiveMatters == 1 ? "" : "s")} " +
            $"with {spend} of {budget} budget utilized ({pct}%)."
        };

        if (portfolio.MattersAtRisk > 0)
        {
            parts.Add(
                $"{portfolio.MattersAtRisk} matter{(portfolio.MattersAtRisk == 1 ? " is" : "s are")} at risk.");
        }
        else
        {
            parts.Add("No matters are currently at risk.");
        }

        if (portfolio.OverdueEvents > 0)
        {
            parts.Add(
                $"{portfolio.OverdueEvents} event{(portfolio.OverdueEvents == 1 ? " is" : "s are")} overdue.");
        }
        else
        {
            parts.Add("No events are overdue.");
        }

        if (topMatter is not null)
        {
            var deadlinePart = topMatter.Deadline.HasValue
                ? $" (due {topMatter.Deadline.Value:MMM d, yyyy})"
                : string.Empty;
            parts.Add($"Top priority: {topMatter.Name}{deadlinePart}.");
        }

        return string.Join(" ", parts);
    }

    /// <summary>
    /// Attempts to generate an AI-enhanced narrative via <see cref="IBriefingAi"/>.
    /// Returns a tuple of (narrative, isAiEnhanced).
    /// Falls back to the template narrative on any failure or timeout.
    /// </summary>
    private async Task<(string Narrative, bool IsAiEnhanced)> TryGetAiNarrativeAsync(
        PortfolioSummaryResponse portfolio,
        TopMatterSummary? topMatter,
        string templateNarrative,
        CancellationToken ct)
    {
        try
        {
            using var cts = CancellationTokenSource.CreateLinkedTokenSource(ct);
            cts.CancelAfter(AiTimeout);

            var prompt = BuildAiPrompt(portfolio, topMatter);
            var aiNarrative = await _briefingAi!.GenerateNarrativeAsync(prompt, cancellationToken: cts.Token);

            if (!string.IsNullOrWhiteSpace(aiNarrative))
            {
                _logger.LogDebug("AI narrative generated successfully for briefing.");
                return (aiNarrative.Trim(), true);
            }

            _logger.LogDebug("AI returned empty narrative; falling back to template.");
        }
        catch (OperationCanceledException) when (!ct.IsCancellationRequested)
        {
            // AI timed out (3-second timeout) — silent fallback, never block the response
            _logger.LogWarning(
                "AI narrative generation timed out after {Timeout}s; using template narrative.",
                AiTimeout.TotalSeconds);
        }
        catch (Exception ex)
        {
            // Any AI failure — silent fallback per spec constraint
            _logger.LogWarning(
                ex,
                "AI narrative generation failed; using template narrative.");
        }

        return (templateNarrative, false);
    }

    /// <summary>
    /// Builds a structured prompt for AI narrative generation.
    /// The prompt is designed to produce a concise, professional 2-3 sentence briefing.
    /// </summary>
    private static string BuildAiPrompt(
        PortfolioSummaryResponse portfolio,
        TopMatterSummary? topMatter)
    {
        var spend = portfolio.TotalSpend.ToString("C0", CultureInfo.CurrentCulture);
        var budget = portfolio.TotalBudget.ToString("C0", CultureInfo.CurrentCulture);
        var pct = ((double)portfolio.UtilizationPercent).ToString("F1", CultureInfo.InvariantCulture);

        var topMatterLine = topMatter is not null
            ? $"Top priority matter: {topMatter.Name}" +
              (topMatter.Deadline.HasValue ? $" (due {topMatter.Deadline.Value:MMM d, yyyy})" : string.Empty) + "."
            : "No specific top-priority matter identified.";

        return $"""
            You are a legal operations AI assistant. Write a concise, professional 2-3 sentence portfolio briefing
            for a legal operations manager based on the following portfolio data. Focus on actionable insights.

            Portfolio data:
            - Active matters: {portfolio.ActiveMatters}
            - Total spend: {spend} of {budget} budget ({pct}% utilized)
            - Matters at risk: {portfolio.MattersAtRisk}
            - Overdue events: {portfolio.OverdueEvents}
            - {topMatterLine}

            Write the briefing as plain prose (no bullet points, no headings). Keep it under 100 words.
            """;
    }
}
