// FR-06a upload fidelity branch — unit tests for ComposeService.SaveAsync (task 015).
//
// Scope: FR-06a's fidelity branch (unedited-original-vs-regenerated bytes) is a CLIENT-side
// decision — ComposeWorkspace.tsx's `triggerSave` picks which bytes to send, keyed off the
// editor's own dirty flag (`editorRef.current.isDirty()`): clean -> the retained ORIGINAL mount
// bytes (`state.docxBytes`); dirty -> the regenerated `.docx` via the EXISTING
// `tipTapToDocxBytes` path (unchanged). `ComposeService.SaveAsync` is, and must remain,
// content-agnostic: whatever bytes the caller supplies in `SaveComposeDocumentRequest.Content`
// are persisted to SPE BYTE-IDENTICAL, with no server-side re-encode/regeneration/transform of
// any kind, regardless of which of the two client-side branches produced them. These tests are
// the BFF-side regression guard for that invariant — if a future change makes SaveAsync
// re-encode, re-wrap, or otherwise mutate the caller-supplied bytes (or silently discriminates
// on their shape), these tests fail.
//
// Mocking boundary (ADR-038 §4 "mock at module boundaries" — NOT the banned in-process-collaborator
// mocking of §4 B5): every collaborator mocked here is a genuine external boundary —
//   • ISpeFileOperations    → SPE / Graph facade (ADR-007)
//   • IGenericEntityService → Dataverse
//   • ChatSessionManager (virtual GetSessionAsync) → Redis-backed session store
//   • IPostUploadIndexingEnqueuer → the RAG indexing seam
// Same boundary set as ComposeServiceCreateOnSaveTests.cs (task 013), which this file extends
// for the FR-06a byte-fidelity branch.
//
// Banned-pattern compliance (tests/CLAUDE.md B1-B17): no Mock<HttpMessageHandler> (B1), no
// typed-HttpClient mock (B2), no DI-registration test (B3), no ctor null-check test (B4), no
// mirror/pass-through/coverage-filler shapes (B6/B9/B10). Each test names a concrete production
// behavior (byte-identity through the SPE write path) that breaks if the test is deleted.

using System;
using System.IO;
using System.Threading;
using System.Threading.Tasks;
using FluentAssertions;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Logging.Abstractions;
using Microsoft.Xrm.Sdk;
using Moq;
using Spaarke.Dataverse;
using Sprk.Bff.Api.Infrastructure.Cache;
using Sprk.Bff.Api.Infrastructure.Graph;
using Sprk.Bff.Api.Models;
using Sprk.Bff.Api.Models.Ai;
using Sprk.Bff.Api.Models.Ai.Chat;
using Sprk.Bff.Api.Services.Ai;
using Sprk.Bff.Api.Services.Ai.Chat;
using Sprk.Bff.Api.Services.Compose;
using Xunit;

namespace Sprk.Bff.Api.Tests.Services.Compose;

public sealed class ComposeServiceUploadFidelityTests
{
    private const string Tenant = "tenant-aad-015";
    private const string ContainerId = "b!container-fidelity";
    private const string ResolvedDriveId = "drive-fidelity";
    private const string NewSpeItemId = "spe-item-fidelity-new";
    private const string ExistingDriveId = "drive-existing-fidelity";
    private const string ExistingSpeItemId = "spe-existing-fidelity";

    private readonly Mock<ISpeFileOperations> _spe = new(MockBehavior.Strict);
    private readonly Mock<IGenericEntityService> _dataverse = new(MockBehavior.Strict);
    private readonly Mock<IPostUploadIndexingEnqueuer> _indexing = new(MockBehavior.Strict);
    private readonly Mock<ChatSessionManager> _sessions;

    public ComposeServiceUploadFidelityTests()
    {
        _sessions = new Mock<ChatSessionManager>(
            Mock.Of<ITenantCache>(),
            Mock.Of<IChatDataverseRepository>(),
            NullLogger<ChatSessionManager>.Instance,
            null!,
            null!);

        // The rebind step looks up the session; a null session is a benign no-op (warns + returns).
        _sessions
            .Setup(s => s.GetSessionAsync(It.IsAny<string>(), It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync((ChatSession?)null);
    }

    private ComposeService CreateSut() => new(
        _spe.Object,
        _sessions.Object,
        _dataverse.Object,
        new DocxAnnotationWriter(),
        _indexing.Object,
        NullLogger<ComposeService>.Instance);

    /// <summary>The pristine ORIGINAL bytes — as if retained from the 010/012 mount path,
    /// unmodified by any editor round-trip.</summary>
    private static ReadOnlyMemory<byte> OriginalUploadBytes() =>
        new byte[] { 0x50, 0x4B, 0x03, 0x04, 0x14, 0x00, 0xAA, 0xBB, 0xCC }; // DOCX ZIP signature + payload

    /// <summary>Distinguishable "regenerated" bytes — as if produced by the EXISTING
    /// `tipTapToDocxBytes` client-side path for a genuinely edited document. Deliberately a
    /// different length/content than <see cref="OriginalUploadBytes"/> so a test asserting
    /// "persisted == regenerated, NOT original" cannot pass by coincidence.</summary>
    private static ReadOnlyMemory<byte> RegeneratedEditedBytes() =>
        new byte[] { 0x50, 0x4B, 0x03, 0x04, 0x14, 0x00, 0x11, 0x22, 0x33, 0x44, 0x55 };

    private static FileHandleDto NewDriveItem() => new(
        Id: NewSpeItemId,
        Name: "draft.docx",
        ParentId: null,
        Size: 1234,
        CreatedDateTime: DateTimeOffset.UtcNow,
        LastModifiedDateTime: DateTimeOffset.UtcNow,
        ETag: "\"etag-fidelity-v1\"",
        IsFolder: false,
        WebUrl: "https://spe/web",
        DriveId: ResolvedDriveId);

    private static FileHandleDto ReplacedDriveItem() => new(
        Id: ExistingSpeItemId,
        Name: "existing.docx",
        ParentId: null,
        Size: 99,
        CreatedDateTime: DateTimeOffset.UtcNow,
        LastModifiedDateTime: DateTimeOffset.UtcNow,
        ETag: "\"etag-fidelity-v2\"",
        IsFolder: false,
        WebUrl: "https://spe/web",
        DriveId: ExistingDriveId);

    private void ArrangeContainerCreate(out Func<byte[]> capturedBytesAccessor)
    {
        _spe.Setup(s => s.ResolveDriveIdAsync(ContainerId, It.IsAny<CancellationToken>()))
            .ReturnsAsync(ResolvedDriveId);

        byte[]? captured = null;
        _spe.Setup(s => s.UploadSmallAsUserAsync(
                It.IsAny<HttpContext>(), ResolvedDriveId, It.IsAny<string>(), It.IsAny<Stream>(), It.IsAny<CancellationToken>()))
            .Callback<HttpContext, string, string, Stream, CancellationToken>((_, _, _, stream, _) =>
            {
                using var buffer = new MemoryStream();
                stream.CopyTo(buffer);
                captured = buffer.ToArray();
            })
            .ReturnsAsync(NewDriveItem());

        capturedBytesAccessor = () => captured
            ?? throw new InvalidOperationException("UploadSmallAsUserAsync was never invoked.");
    }

    private void ArrangeReplaceExisting(out Func<byte[]> capturedBytesAccessor)
    {
        byte[]? captured = null;
        _spe.Setup(s => s.ReplaceFileContentAsUserAsync(
                It.IsAny<HttpContext>(), ExistingDriveId, ExistingSpeItemId, It.IsAny<Stream>(), It.IsAny<CancellationToken>()))
            .Callback<HttpContext, string, string, Stream, CancellationToken>((_, _, _, stream, _) =>
            {
                using var buffer = new MemoryStream();
                stream.CopyTo(buffer);
                captured = buffer.ToArray();
            })
            .ReturnsAsync(ReplacedDriveItem());

        capturedBytesAccessor = () => captured
            ?? throw new InvalidOperationException("ReplaceFileContentAsUserAsync was never invoked.");
    }

    private void ArrangeExistingRecordFound() =>
        _dataverse.Setup(d => d.RetrieveByAlternateKeyAsync(
                "sprk_document", It.IsAny<KeyAttributeCollection>(), It.IsAny<string[]?>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(new Entity("sprk_document") { Id = Guid.NewGuid() });

    private void ArrangeNoExistingRecordThenCreate(Guid newId)
    {
        _dataverse.Setup(d => d.RetrieveByAlternateKeyAsync(
                "sprk_document", It.IsAny<KeyAttributeCollection>(), It.IsAny<string[]?>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync((Entity)null!);
        _dataverse.Setup(d => d.CreateAsync(It.IsAny<Entity>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(newId);
    }

    private void ArrangeIndexingSubmitted() =>
        _indexing.Setup(i => i.EnqueueIfApplicableAsync(
                It.IsAny<PostUploadIndexingRequest>(), It.IsAny<HttpContext>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(PostUploadIndexingResult.Submitted(Guid.NewGuid()));

    // ── Acceptance #1: unedited upload -> Save persists SPE bytes byte-identical (create path) ──
    [Fact]
    public async Task SaveAsync_TransientDraftWithUneditedOriginalContent_PersistsByteIdenticalToUpload()
    {
        ArrangeContainerCreate(out var capturedBytes);
        ArrangeNoExistingRecordThenCreate(Guid.NewGuid());
        ArrangeIndexingSubmitted();

        var sut = CreateSut();
        var original = OriginalUploadBytes();
        var request = new SaveComposeDocumentRequest
        {
            DocumentSpeId = null,           // transient draft — no SPE item yet
            ContainerId = ContainerId,
            Content = original,             // the client sent the RETAINED ORIGINAL (editor was clean)
            SessionId = Guid.NewGuid().ToString(),
            TenantId = Tenant,
            DisplayName = "Unedited draft",
        };

        await sut.SaveAsync(request, new DefaultHttpContext(), CancellationToken.None);

        capturedBytes().Should().BeEquivalentTo(
            original.ToArray(),
            options => options.WithStrictOrdering(),
            "an unedited save must persist the upload's bytes byte-identical (FR-06a) — no server-side transform");
    }

    // ── Acceptance #2: edited upload -> Save persists the regenerated bytes as-supplied ─────────
    [Fact]
    public async Task SaveAsync_TransientDraftWithRegeneratedEditedContent_PersistsByteIdenticalToRegenerated()
    {
        ArrangeContainerCreate(out var capturedBytes);
        ArrangeNoExistingRecordThenCreate(Guid.NewGuid());
        ArrangeIndexingSubmitted();

        var sut = CreateSut();
        var regenerated = RegeneratedEditedBytes();
        var request = new SaveComposeDocumentRequest
        {
            DocumentSpeId = null,
            ContainerId = ContainerId,
            Content = regenerated,          // the client sent the tipTapToDocxBytes REGENERATION (editor was dirty)
            SessionId = Guid.NewGuid().ToString(),
            TenantId = Tenant,
            DisplayName = "Edited draft",
        };

        await sut.SaveAsync(request, new DefaultHttpContext(), CancellationToken.None);

        var persisted = capturedBytes();
        persisted.Should().BeEquivalentTo(
            regenerated.ToArray(),
            options => options.WithStrictOrdering(),
            "an edited save must persist the regenerated bytes the client supplied, unchanged");
        persisted.Should().NotBeEquivalentTo(
            OriginalUploadBytes().ToArray(),
            "the regenerated-edit branch must never fall back to some server-cached original — SaveAsync has no such cache");
    }

    // ── Acceptance #1 (replace-path variant): unedited Save of an already-promoted document ─────
    [Fact]
    public async Task SaveAsync_ExistingDriveItemWithUneditedOriginalContent_ReplacesWithByteIdenticalContent()
    {
        ArrangeReplaceExisting(out var capturedBytes);
        ArrangeExistingRecordFound();
        ArrangeIndexingSubmitted();

        var sut = CreateSut();
        var original = OriginalUploadBytes();
        var request = new SaveComposeDocumentRequest
        {
            DocumentSpeId = ExistingSpeItemId,
            DriveId = ExistingDriveId,
            Content = original,
            SessionId = Guid.NewGuid().ToString(),
            TenantId = Tenant,
        };

        await sut.SaveAsync(request, new DefaultHttpContext(), CancellationToken.None);

        capturedBytes().Should().BeEquivalentTo(
            original.ToArray(),
            options => options.WithStrictOrdering(),
            "the replace-content path must also persist an unedited save byte-identical to the load-time original");
    }

    // ── Acceptance (negative): a whitespace-only / no-op edit still persists the original ───────
    // ── verbatim — no spurious server-side regeneration is ever triggered by content shape. ────
    [Fact]
    public async Task SaveAsync_WhitespaceOnlyNoOpEditContent_PersistsCallerSuppliedBytesUnchanged_NoServerSideRegeneration()
    {
        ArrangeReplaceExisting(out var capturedBytes);
        ArrangeExistingRecordFound();
        ArrangeIndexingSubmitted();

        var sut = CreateSut();
        // A whitespace-only / no-op interaction never flips the editor's dirty flag (see
        // ComposeEditor's onUpdate/dirtyRef contract), so ComposeWorkspace.triggerSave keeps
        // sending the retained ORIGINAL bytes — never invoking tipTapToDocxBytes. This request
        // is what the BFF actually receives in that case: the untouched original content.
        var originalAfterNoOpEdit = OriginalUploadBytes();
        var request = new SaveComposeDocumentRequest
        {
            DocumentSpeId = ExistingSpeItemId,
            DriveId = ExistingDriveId,
            Content = originalAfterNoOpEdit,
            SessionId = Guid.NewGuid().ToString(),
            TenantId = Tenant,
        };

        var result = await sut.SaveAsync(request, new DefaultHttpContext(), CancellationToken.None);

        // Strict mocks (ISpeFileOperations/IGenericEntityService/IPostUploadIndexingEnqueuer) —
        // any unexpected collaborator call (e.g. a hypothetical server-side regeneration hook)
        // would throw during the Act above. The only assertion needed is byte-identity.
        capturedBytes().Should().BeEquivalentTo(
            originalAfterNoOpEdit.ToArray(),
            options => options.WithStrictOrdering(),
            "a no-op edit that never set dirty must never trigger regeneration — the original is persisted verbatim");
        result.VersionId.Should().Be(ExistingSpeItemId);
    }
}
