# Remove the aiskillconfig records (FormFillFieldOptOut) for the four sprk_event to-do fields.
# These records are auto-generated by Copilot Form Fill opt-out tracking and block attribute deletes.
$ErrorActionPreference = "Stop"
$Environment = "spaarkedev1.crm.dynamics.com"
$BaseUrl = "https://$Environment/api/data/v9.2"
$token = (az account get-access-token --resource "https://$Environment" --query accessToken -o tsv)
$headers = @{
    "Authorization" = "Bearer $token"
    "OData-MaxVersion" = "4.0"
    "OData-Version" = "4.0"
    "Content-Type" = "application/json"
    "Accept" = "application/json"
}

# Query all aiskillconfig records targeting any of the four attributes
$attributeIds = @{
    "817724bf-3a0c-f111-8342-7c1e520aa4df" = "sprk_todoflag"
    "ba8b4528-3b0c-f111-8342-7c1e520aa4df" = "sprk_todostatus"
    "90b8a07a-3913-f111-8342-7c1e525abd8b" = "sprk_todocolumn"
    "388e12e4-3813-f111-8343-7c1e520aa4df" = "sprk_todopinned"
}

Write-Host "`n-- Find aiskillconfig records for each attribute --" -ForegroundColor Yellow
$toDelete = @()
foreach ($entry in $attributeIds.GetEnumerator()) {
    $attrId = $entry.Key
    $field = $entry.Value
    $url = "$BaseUrl/aiskillconfigs?`$filter=_attribute_value eq $attrId&`$select=aiskillconfigid,uniquename,description"
    try {
        $r = Invoke-RestMethod -Uri $url -Headers $headers -Method Get
        foreach ($rec in $r.value) {
            Write-Host ("  [{0}] aiskillconfig id={1}  uniquename={2}" -f $field, $rec.aiskillconfigid, $rec.uniquename) -ForegroundColor Gray
            $toDelete += @{ field = $field; id = $rec.aiskillconfigid; uniquename = $rec.uniquename }
        }
    } catch {
        Write-Host ("  [{0}] query failed: {1}" -f $field, $_.Exception.Message) -ForegroundColor Red
    }
}

Write-Host ("`n-- Deleting {0} aiskillconfig record(s) --" -f $toDelete.Count) -ForegroundColor Cyan
foreach ($r in $toDelete) {
    $url = "$BaseUrl/aiskillconfigs($($r.id))"
    try {
        Invoke-RestMethod -Uri $url -Headers $headers -Method Delete | Out-Null
        Write-Host ("  [OK] deleted {0} ({1})" -f $r.field, $r.uniquename) -ForegroundColor Green
    } catch {
        Write-Host ("  [FAIL] {0}: {1}" -f $r.field, $_.Exception.Message) -ForegroundColor Red
        try { Write-Host ("       body: $($_.ErrorDetails.Message)") -ForegroundColor DarkGray } catch {}
    }
}

# Verify
Write-Host "`n-- Re-check aiskillconfig membership --" -ForegroundColor Yellow
foreach ($entry in $attributeIds.GetEnumerator()) {
    $url = "$BaseUrl/aiskillconfigs?`$filter=_attribute_value eq $($entry.Key)&`$select=aiskillconfigid"
    $r = Invoke-RestMethod -Uri $url -Headers $headers -Method Get
    Write-Host ("  [{0}] remaining: {1} aiskillconfigs" -f $entry.Value, $r.value.Count) -ForegroundColor Gray
}
