/**
 * WorkspaceTabManager.ts — Plain TypeScript tab state manager for WorkspacePane.
 *
 * Manages an ordered array of workspace tabs with a configurable cap on the
 * number of non-Home tabs (`MAX_WORKSPACE_TABS`). When a new non-Home tab is
 * added and the count of non-Home tabs would exceed the cap, the oldest
 * non-Home tab (by insertion order) is evicted first — a FIFO eviction policy.
 *
 * The Home tab (kind === 'home') is exempt from the cap and never evicted
 * by FIFO. It also cannot be closed via closeTab. This supports the
 * SpaarkeAi WorkspacePane model where Home is always present as a non-closable
 * default tab (typically the embedded LegalWorkspace) and widget tabs are
 * added/evicted around it (FR-13, design §C-2 / §F-3).
 *
 * This is a plain class, NOT a React component. WorkspacePane holds an instance
 * in a React ref and drives re-renders by copying managed state into React state.
 *
 * Tab lifecycle:
 *   ensureHomeTab(displayName?, widgetData?, Component?) → returns the Home tab id
 *   addTab(widgetType, data) → returns the new (non-Home) tab id
 *   updateTab(tabId, data)   → updates an existing tab's data payload
 *   closeTab(tabId)          → removes a non-Home tab; returns the id that
 *                              became active (or null). No-op for Home.
 *   setActiveTab(tabId)      → changes the active tab
 *
 * @see WorkspacePane — the React component that owns this manager
 * @see ADR-021 — no hardcoded colors in component layer
 * @see ADR-012 — constants are a single source of truth, exported by name
 * @see FR-13 — `MAX_WORKSPACE_TABS = 8` exempts Home from cap and FIFO
 */

import type React from "react";

// ---------------------------------------------------------------------------
// Constants — exported as the single source of truth
// ---------------------------------------------------------------------------

/**
 * Maximum number of concurrent **non-Home** workspace tabs.
 *
 * When a new non-Home tab is added and `nonHomeTabCount >= MAX_WORKSPACE_TABS`,
 * the oldest non-Home tab (by insertion order) is evicted first (FIFO). The
 * Home tab — if present — is exempt from the cap and never evicted by FIFO.
 *
 * Single source of truth (ADR-012): consumers MUST import this constant by
 * name rather than hardcoding a numeric value.
 *
 * @see FR-13 — Acceptance: 9th non-Home widget evicts oldest; Home preserved.
 */
export const MAX_WORKSPACE_TABS = 8;

// ---------------------------------------------------------------------------
// WorkspaceTab — public tab state record
// ---------------------------------------------------------------------------

/**
 * Discriminant for tab kind.
 *   'home'   — the always-present non-closable, non-evictable tab.
 *   'widget' — a normal widget tab subject to FIFO eviction.
 */
export type WorkspaceTabKind = "home" | "widget";

/**
 * State record for a single workspace tab.
 *
 * `Component` is stored as `unknown` here because this is plain TS; the React
 * layer casts it to `React.ComponentType<WorkspaceWidgetProps>` before render.
 */
export interface WorkspaceTab {
  /** Stable unique id for this tab instance (generated by addTab / fixed for Home). */
  id: string;
  /** Discriminant — 'home' for the Home tab, 'widget' for all others. */
  kind: WorkspaceTabKind;
  /** Widget type string as sent by the server (e.g. "document-summary"). */
  widgetType: string;
  /** Widget payload delivered with the widget_load event. */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  widgetData: any;
  /** Resolved React component — null while the registry promise is pending. */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  Component: React.ComponentType<any> | null;
  /** True while resolveWorkspaceWidget() is still pending. */
  isLoading: boolean;
  /** Human-readable display label (falls back to widgetType if registry lacks displayName). */
  displayName: string;
}

// ---------------------------------------------------------------------------
// WorkspaceTabManagerState — snapshot returned to callers
// ---------------------------------------------------------------------------

/**
 * Immutable snapshot of tab manager state, returned by getSnapshot().
 * WorkspacePane spreads this into React state on every mutation.
 *
 * `tabs` includes the Home tab when present (always at index 0 by convention).
 */
export interface WorkspaceTabManagerState {
  tabs: WorkspaceTab[];
  activeTabId: string | null;
}

// ---------------------------------------------------------------------------
// Internal constants
// ---------------------------------------------------------------------------

/** Stable id used for the Home tab. Reserved — addTab() will reject this id. */
const HOME_TAB_ID = "home";

/** Default widgetType marker for the Home tab. */
const HOME_TAB_WIDGET_TYPE = "home";

// ---------------------------------------------------------------------------
// WorkspaceTabManager
// ---------------------------------------------------------------------------

/**
 * Plain TypeScript tab state manager — NO React, NO side effects.
 *
 * WorkspacePane instantiates this once in a ref and calls the mutating methods
 * in event handlers. After each mutation, getSnapshot() is called and the
 * result is spread into React's useState to trigger a re-render.
 */
export class WorkspaceTabManager {
  private _tabs: WorkspaceTab[] = [];
  private _activeTabId: string | null = null;
  private _nextSeq = 0;

  // -------------------------------------------------------------------------
  // ensureHomeTab — install / update the always-present Home tab
  // -------------------------------------------------------------------------

  /**
   * Install (or update) the always-present Home tab.
   *
   * - On first call, prepends a Home tab at index 0 of the tabs array. The
   *   Home tab is exempt from `MAX_WORKSPACE_TABS` and cannot be closed.
   * - On subsequent calls, updates the existing Home tab's displayName,
   *   widgetData, and resolved Component in place (no eviction, no reordering).
   * - The Home tab does not auto-activate when added; callers may call
   *   setActiveTab(homeTabId) explicitly if desired.
   *
   * @param displayName - Optional display label (defaults to 'Home').
   * @param widgetData  - Optional payload (e.g. layout metadata).
   * @param Component   - Optional resolved React component.
   * @returns The Home tab's stable id.
   */
  ensureHomeTab(
    displayName?: string,
    widgetData: unknown = null,
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    Component: React.ComponentType<any> | null = null,
  ): string {
    const existingIdx = this._tabs.findIndex((t) => t.kind === "home");

    if (existingIdx >= 0) {
      const existing = this._tabs[existingIdx];
      const updated: WorkspaceTab = {
        ...existing,
        widgetData,
        Component: Component ?? existing.Component,
        isLoading: Component != null ? false : existing.isLoading,
        displayName: displayName ?? existing.displayName,
      };
      this._tabs = [
        ...this._tabs.slice(0, existingIdx),
        updated,
        ...this._tabs.slice(existingIdx + 1),
      ];
      return existing.id;
    }

    const homeTab: WorkspaceTab = {
      id: HOME_TAB_ID,
      kind: "home",
      widgetType: HOME_TAB_WIDGET_TYPE,
      widgetData,
      Component,
      isLoading: Component == null,
      displayName: displayName ?? "Home",
    };

    // Home always sits at index 0 by convention.
    this._tabs = [homeTab, ...this._tabs];
    return HOME_TAB_ID;
  }

  // -------------------------------------------------------------------------
  // addTab — add a widget tab (subject to FIFO eviction)
  // -------------------------------------------------------------------------

  /**
   * Add a new widget tab.
   *
   * If the count of existing non-Home tabs is at or above `MAX_WORKSPACE_TABS`,
   * the oldest non-Home tab (by insertion order) is silently evicted first
   * (FIFO). The Home tab — if present — is excluded from eviction candidates
   * and remains untouched.
   *
   * The new tab becomes the active tab.
   *
   * @param widgetType  - Widget type string from the server event.
   * @param widgetData  - Arbitrary payload to pass to the widget component.
   * @param displayName - Optional display label; defaults to widgetType.
   * @returns The new tab's stable id.
   */
  addTab(widgetType: string, widgetData: unknown, displayName?: string): string {
    // Enforce MAX_WORKSPACE_TABS — evict the oldest non-Home tab when at cap.
    const nonHomeIndices = this._tabs
      .map((t, i) => (t.kind === "widget" ? i : -1))
      .filter((i) => i >= 0);

    if (nonHomeIndices.length >= MAX_WORKSPACE_TABS) {
      const oldestNonHomeIdx = nonHomeIndices[0];
      this._tabs = [
        ...this._tabs.slice(0, oldestNonHomeIdx),
        ...this._tabs.slice(oldestNonHomeIdx + 1),
      ];
    }

    const id = `wstab-${++this._nextSeq}-${widgetType}`;

    const newTab: WorkspaceTab = {
      id,
      kind: "widget",
      widgetType,
      widgetData,
      Component: null,
      isLoading: true,
      displayName: displayName ?? widgetType,
    };

    this._tabs = [...this._tabs, newTab];
    this._activeTabId = id;

    return id;
  }

  // -------------------------------------------------------------------------
  // resolveTabComponent
  // -------------------------------------------------------------------------

  /**
   * Set the resolved React component for a tab, clearing its loading state.
   *
   * Called by WorkspacePane after the WorkspaceWidgetRegistry promise resolves.
   * A no-op if the tab no longer exists (e.g. user closed it before resolution).
   *
   * @param tabId     - The tab id returned by addTab.
   * @param Component - The resolved React component type.
   * @param displayName - Optional updated display name from registry metadata.
   */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  resolveTabComponent(tabId: string, Component: React.ComponentType<any>, displayName?: string): void {
    this._tabs = this._tabs.map((t) =>
      t.id === tabId
        ? { ...t, Component, isLoading: false, displayName: displayName ?? t.displayName }
        : t
    );
  }

  // -------------------------------------------------------------------------
  // updateTab
  // -------------------------------------------------------------------------

  /**
   * Update an existing tab's data payload (widget_update event).
   *
   * A no-op if the tab id is not found — callers do not need to guard against
   * stale updates.
   *
   * @param tabId      - The id of the tab to update.
   * @param widgetData - New data payload to pass to the widget component.
   */
  updateTab(tabId: string, widgetData: unknown): void {
    this._tabs = this._tabs.map((t) =>
      t.id === tabId ? { ...t, widgetData } : t
    );
  }

  // -------------------------------------------------------------------------
  // closeTab
  // -------------------------------------------------------------------------

  /**
   * Remove a tab by id.
   *
   * The Home tab cannot be closed — callers passing the Home id receive the
   * current active tab id and no state change occurs.
   *
   * If the closed tab was the active one, the manager selects the next tab to
   * the right, or the previous tab if there is no right neighbour, or null if
   * the tab list becomes empty.
   *
   * @param tabId - The id of the tab to close.
   * @returns The id of the tab that became active after closing, or null.
   */
  closeTab(tabId: string): string | null {
    const idx = this._tabs.findIndex((t) => t.id === tabId);
    if (idx === -1) return this._activeTabId;

    // Home is non-closable.
    if (this._tabs[idx].kind === "home") return this._activeTabId;

    const wasActive = this._activeTabId === tabId;
    this._tabs = this._tabs.filter((t) => t.id !== tabId);

    if (!wasActive) {
      return this._activeTabId;
    }

    // Select successor: prefer right neighbour, then left, then null.
    if (this._tabs.length === 0) {
      this._activeTabId = null;
    } else if (idx < this._tabs.length) {
      this._activeTabId = this._tabs[idx].id;
    } else {
      this._activeTabId = this._tabs[this._tabs.length - 1].id;
    }

    return this._activeTabId;
  }

  // -------------------------------------------------------------------------
  // setActiveTab
  // -------------------------------------------------------------------------

  /**
   * Change the active tab.
   *
   * A no-op if the tab id is not in the current tab list.
   *
   * @param tabId - The id of the tab to activate.
   */
  setActiveTab(tabId: string): void {
    if (this._tabs.some((t) => t.id === tabId)) {
      this._activeTabId = tabId;
    }
  }

  // -------------------------------------------------------------------------
  // getActiveTab
  // -------------------------------------------------------------------------

  /**
   * Return the currently active tab record, or null if no tabs exist.
   */
  getActiveTab(): WorkspaceTab | null {
    return this._tabs.find((t) => t.id === this._activeTabId) ?? null;
  }

  // -------------------------------------------------------------------------
  // clearAllTabs (AIPU2-102 — exclusive playbook selection)
  // -------------------------------------------------------------------------

  /**
   * Remove all **non-Home** tabs and reset active tab.
   *
   * Called by WorkspacePane when a `playbook-selected` event arrives with
   * `isExclusive === true`. Exclusive playbooks enforce a clean slate — the
   * workspace's widget tabs are reset before seeding the playbook's
   * defaultWidgets.
   *
   * The Home tab — if present — is preserved. If the Home tab was active
   * before this call, it remains active; otherwise activeTabId becomes the
   * Home tab id (if Home is present) or null.
   *
   * @returns The number of (non-Home) tabs that were removed.
   */
  clearAllTabs(): number {
    const homeTab = this._tabs.find((t) => t.kind === "home") ?? null;
    const removedCount = this._tabs.filter((t) => t.kind === "widget").length;

    this._tabs = homeTab ? [homeTab] : [];
    this._activeTabId = homeTab ? homeTab.id : null;

    return removedCount;
  }

  // -------------------------------------------------------------------------
  // getSnapshot
  // -------------------------------------------------------------------------

  /**
   * Return an immutable state snapshot.
   *
   * WorkspacePane calls this after every mutation and spreads the result into
   * React state to trigger a re-render. The snapshot is a shallow copy —
   * mutating the returned arrays does not affect the manager's internal state.
   */
  getSnapshot(): WorkspaceTabManagerState {
    return {
      tabs: [...this._tabs],
      activeTabId: this._activeTabId,
    };
  }
}
