/**
 * WorkspaceTabManager.ts — Plain TypeScript tab state manager for WorkspacePane.
 *
 * Manages an ordered array of active workspace tabs with a hard maximum of 3.
 * When a 4th tab would be added, the oldest (index 0) is automatically removed
 * before the new tab is appended — giving a FIFO eviction policy.
 *
 * This is a plain class, NOT a React component. WorkspacePane holds an instance
 * in a React ref and drives re-renders by copying managed state into React state.
 *
 * Tab lifecycle:
 *   addTab(widgetType, data) → returns the new tab id
 *   updateTab(tabId, data)   → updates an existing tab's data payload
 *   closeTab(tabId)          → removes a tab; returns the id that became active (or null)
 *   setActiveTab(tabId)      → changes the active tab
 *
 * @see WorkspacePane — the React component that owns this manager
 * @see ADR-021 — no hardcoded colors in component layer
 */

import type React from "react";

// ---------------------------------------------------------------------------
// WorkspaceTab — public tab state record
// ---------------------------------------------------------------------------

/**
 * State record for a single workspace tab.
 *
 * `Component` is stored as `unknown` here because this is plain TS; the React
 * layer casts it to `React.ComponentType<WorkspaceWidgetProps>` before render.
 */
export interface WorkspaceTab {
  /** Stable unique id for this tab instance (generated by addTab). */
  id: string;
  /** Widget type string as sent by the server (e.g. "document-summary"). */
  widgetType: string;
  /** Widget payload delivered with the widget_load event. */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  widgetData: any;
  /** Resolved React component — null while the registry promise is pending. */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  Component: React.ComponentType<any> | null;
  /** True while resolveWorkspaceWidget() is still pending. */
  isLoading: boolean;
  /** Human-readable display label (falls back to widgetType if registry lacks displayName). */
  displayName: string;
}

// ---------------------------------------------------------------------------
// WorkspaceTabManagerState — snapshot returned to callers
// ---------------------------------------------------------------------------

/**
 * Immutable snapshot of tab manager state, returned by getSnapshot().
 * WorkspacePane spreads this into React state on every mutation.
 */
export interface WorkspaceTabManagerState {
  tabs: WorkspaceTab[];
  activeTabId: string | null;
}

// ---------------------------------------------------------------------------
// WorkspaceTabManager
// ---------------------------------------------------------------------------

/** Maximum number of concurrent tabs. Oldest is evicted when this is exceeded. */
export const MAX_TABS = 3;

/**
 * Plain TypeScript tab state manager — NO React, NO side effects.
 *
 * WorkspacePane instantiates this once in a ref and calls the mutating methods
 * in event handlers. After each mutation, getSnapshot() is called and the
 * result is spread into React's useState to trigger a re-render.
 */
export class WorkspaceTabManager {
  private _tabs: WorkspaceTab[] = [];
  private _activeTabId: string | null = null;
  private _nextSeq = 0;

  // -------------------------------------------------------------------------
  // addTab
  // -------------------------------------------------------------------------

  /**
   * Add a new tab for the given widget type and data payload.
   *
   * If adding the new tab would exceed MAX_TABS (3), the oldest tab (index 0)
   * is silently removed first. The new tab becomes active.
   *
   * @param widgetType  - Widget type string from the server event.
   * @param widgetData  - Arbitrary payload to pass to the widget component.
   * @param displayName - Optional display label; defaults to widgetType.
   * @returns The new tab's stable id.
   */
  addTab(widgetType: string, widgetData: unknown, displayName?: string): string {
    // Enforce MAX_TABS — evict the oldest when at capacity.
    if (this._tabs.length >= MAX_TABS) {
      this._tabs = this._tabs.slice(1); // remove oldest (first) tab
    }

    const id = `wstab-${++this._nextSeq}-${widgetType}`;

    const newTab: WorkspaceTab = {
      id,
      widgetType,
      widgetData,
      Component: null,
      isLoading: true,
      displayName: displayName ?? widgetType,
    };

    this._tabs = [...this._tabs, newTab];
    this._activeTabId = id;

    return id;
  }

  // -------------------------------------------------------------------------
  // resolveTabComponent
  // -------------------------------------------------------------------------

  /**
   * Set the resolved React component for a tab, clearing its loading state.
   *
   * Called by WorkspacePane after the WorkspaceWidgetRegistry promise resolves.
   * A no-op if the tab no longer exists (e.g. user closed it before resolution).
   *
   * @param tabId     - The tab id returned by addTab.
   * @param Component - The resolved React component type.
   * @param displayName - Optional updated display name from registry metadata.
   */
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  resolveTabComponent(tabId: string, Component: React.ComponentType<any>, displayName?: string): void {
    this._tabs = this._tabs.map((t) =>
      t.id === tabId
        ? { ...t, Component, isLoading: false, displayName: displayName ?? t.displayName }
        : t
    );
  }

  // -------------------------------------------------------------------------
  // updateTab
  // -------------------------------------------------------------------------

  /**
   * Update an existing tab's data payload (widget_update event).
   *
   * A no-op if the tab id is not found — callers do not need to guard against
   * stale updates.
   *
   * @param tabId      - The id of the tab to update.
   * @param widgetData - New data payload to pass to the widget component.
   */
  updateTab(tabId: string, widgetData: unknown): void {
    this._tabs = this._tabs.map((t) =>
      t.id === tabId ? { ...t, widgetData } : t
    );
  }

  // -------------------------------------------------------------------------
  // closeTab
  // -------------------------------------------------------------------------

  /**
   * Remove a tab by id.
   *
   * If the closed tab was the active one, the manager selects the next tab to
   * the right, or the previous tab if there is no right neighbour, or null if
   * the tab list becomes empty.
   *
   * @param tabId - The id of the tab to close.
   * @returns The id of the tab that became active after closing, or null.
   */
  closeTab(tabId: string): string | null {
    const idx = this._tabs.findIndex((t) => t.id === tabId);
    if (idx === -1) return this._activeTabId;

    const wasActive = this._activeTabId === tabId;
    this._tabs = this._tabs.filter((t) => t.id !== tabId);

    if (!wasActive) {
      return this._activeTabId;
    }

    // Select successor: prefer right neighbour, then left, then null.
    if (this._tabs.length === 0) {
      this._activeTabId = null;
    } else if (idx < this._tabs.length) {
      this._activeTabId = this._tabs[idx].id;
    } else {
      this._activeTabId = this._tabs[this._tabs.length - 1].id;
    }

    return this._activeTabId;
  }

  // -------------------------------------------------------------------------
  // setActiveTab
  // -------------------------------------------------------------------------

  /**
   * Change the active tab.
   *
   * A no-op if the tab id is not in the current tab list.
   *
   * @param tabId - The id of the tab to activate.
   */
  setActiveTab(tabId: string): void {
    if (this._tabs.some((t) => t.id === tabId)) {
      this._activeTabId = tabId;
    }
  }

  // -------------------------------------------------------------------------
  // getActiveTab
  // -------------------------------------------------------------------------

  /**
   * Return the currently active tab record, or null if no tabs exist.
   */
  getActiveTab(): WorkspaceTab | null {
    return this._tabs.find((t) => t.id === this._activeTabId) ?? null;
  }

  // -------------------------------------------------------------------------
  // clearAllTabs (AIPU2-102 — exclusive playbook selection)
  // -------------------------------------------------------------------------

  /**
   * Remove all tabs and reset active tab to null.
   *
   * Called by WorkspacePane when a `playbook-selected` event arrives with
   * `isExclusive === true`. Exclusive playbooks enforce a clean slate — the
   * workspace is reset before seeding the playbook's defaultWidgets.
   *
   * @returns The number of tabs that were removed.
   */
  clearAllTabs(): number {
    const count = this._tabs.length;
    this._tabs = [];
    this._activeTabId = null;
    return count;
  }

  // -------------------------------------------------------------------------
  // getSnapshot
  // -------------------------------------------------------------------------

  /**
   * Return an immutable state snapshot.
   *
   * WorkspacePane calls this after every mutation and spreads the result into
   * React state to trigger a re-render. The snapshot is a shallow copy —
   * mutating the returned arrays does not affect the manager's internal state.
   */
  getSnapshot(): WorkspaceTabManagerState {
    return {
      tabs: [...this._tabs],
      activeTabId: this._activeTabId,
    };
  }
}
