using System.Text.Json.Serialization;

namespace Sprk.Bff.Api.Models.Ai;

/// <summary>
/// A complete build plan for creating or modifying a playbook.
/// Generated by AI from user requirements for CREATE_PLAYBOOK intent.
/// </summary>
/// <remarks>
/// The build plan represents the internal specification that the Builder
/// will execute step-by-step. It includes:
/// - Playbook metadata and purpose
/// - Ordered execution steps (node creation, edge creation, scope linking)
/// - Scope requirements (which Actions, Skills, Knowledge, Tools are needed)
/// - Confidence scoring for validation
/// </remarks>
public record BuildPlan
{
    /// <summary>
    /// Unique identifier for this build plan.
    /// </summary>
    [JsonPropertyName("id")]
    public string Id { get; init; } = Guid.NewGuid().ToString("N");

    /// <summary>
    /// Brief description of what this playbook will do.
    /// </summary>
    [JsonPropertyName("summary")]
    public required string Summary { get; init; }

    /// <summary>
    /// Detailed description of the playbook purpose.
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; init; }

    /// <summary>
    /// Document types this playbook is designed for.
    /// </summary>
    [JsonPropertyName("documentTypes")]
    public string[]? DocumentTypes { get; init; }

    /// <summary>
    /// Matter types this playbook is designed for (e.g., REAL_ESTATE, CORPORATE).
    /// </summary>
    [JsonPropertyName("matterTypes")]
    public string[]? MatterTypes { get; init; }

    /// <summary>
    /// Ordered list of execution steps to build the playbook.
    /// </summary>
    [JsonPropertyName("steps")]
    public required ExecutionStep[] Steps { get; init; }

    /// <summary>
    /// Estimated number of nodes that will be created.
    /// </summary>
    [JsonPropertyName("estimatedNodeCount")]
    public int EstimatedNodeCount { get; init; }

    /// <summary>
    /// Confidence score for the plan (0.0 to 1.0).
    /// Lower scores may indicate need for user confirmation.
    /// </summary>
    [JsonPropertyName("confidence")]
    public double Confidence { get; init; }

    /// <summary>
    /// Pattern type this playbook follows (e.g., lease-analysis, contract-review).
    /// </summary>
    [JsonPropertyName("pattern")]
    public string? Pattern { get; init; }

    /// <summary>
    /// Scope requirements identified for this playbook.
    /// </summary>
    [JsonPropertyName("scopeRequirements")]
    public ScopeRequirements? ScopeRequirements { get; init; }

    /// <summary>
    /// Timestamp when the plan was generated.
    /// </summary>
    [JsonPropertyName("generatedAt")]
    public DateTimeOffset GeneratedAt { get; init; } = DateTimeOffset.UtcNow;

    /// <summary>
    /// AI reasoning for this plan structure.
    /// </summary>
    [JsonPropertyName("reasoning")]
    public string? Reasoning { get; init; }
}

/// <summary>
/// A single step in the build plan execution.
/// </summary>
public record ExecutionStep
{
    /// <summary>
    /// Order of this step in the execution sequence (1-based).
    /// </summary>
    [JsonPropertyName("order")]
    public int Order { get; init; }

    /// <summary>
    /// The action to perform (addNode, createEdge, linkScope, createScope, updateConfig).
    /// </summary>
    [JsonPropertyName("action")]
    public required string Action { get; init; }

    /// <summary>
    /// Human-readable description of what this step does.
    /// </summary>
    [JsonPropertyName("description")]
    public required string Description { get; init; }

    /// <summary>
    /// Parameters for the action as key-value pairs.
    /// </summary>
    [JsonPropertyName("parameters")]
    public Dictionary<string, object>? Parameters { get; init; }

    /// <summary>
    /// Step references that this step depends on (e.g., ["step_1", "step_2"]).
    /// </summary>
    [JsonPropertyName("dependsOn")]
    public string[]? DependsOn { get; init; }

    /// <summary>
    /// Node specification for addNode actions.
    /// </summary>
    [JsonPropertyName("nodeSpec")]
    public NodeSpec? NodeSpec { get; init; }

    /// <summary>
    /// Scope reference for linkScope or createScope actions.
    /// </summary>
    [JsonPropertyName("scopeReference")]
    public ScopeReference? ScopeReference { get; init; }

    /// <summary>
    /// Edge specification for createEdge actions.
    /// </summary>
    [JsonPropertyName("edgeSpec")]
    public EdgeSpec? EdgeSpec { get; init; }
}

/// <summary>
/// Specification for a node to be created.
/// </summary>
public record NodeSpec
{
    /// <summary>
    /// Type of node (aiAnalysis, aiCompletion, condition, deliverOutput, etc.).
    /// </summary>
    [JsonPropertyName("type")]
    public required string Type { get; init; }

    /// <summary>
    /// Human-readable label for the node.
    /// </summary>
    [JsonPropertyName("label")]
    public required string Label { get; init; }

    /// <summary>
    /// Position on the canvas.
    /// </summary>
    [JsonPropertyName("position")]
    public BuildPlanNodePosition? Position { get; init; }

    /// <summary>
    /// Node-specific configuration.
    /// </summary>
    [JsonPropertyName("configuration")]
    public NodeConfiguration? Configuration { get; init; }
}

/// <summary>
/// Position coordinates for a node on the canvas.
/// Defined for build plan parsing from AI responses.
/// For canvas operations, use Sprk.Bff.Api.Services.Ai.NodePosition.
/// </summary>
public record BuildPlanNodePosition
{
    /// <summary>
    /// X coordinate.
    /// </summary>
    [JsonPropertyName("x")]
    public double X { get; init; }

    /// <summary>
    /// Y coordinate.
    /// </summary>
    [JsonPropertyName("y")]
    public double Y { get; init; }
}

/// <summary>
/// Configuration for a node.
/// </summary>
public record NodeConfiguration
{
    /// <summary>
    /// Output variable name for this node.
    /// </summary>
    [JsonPropertyName("outputVariable")]
    public string? OutputVariable { get; init; }

    /// <summary>
    /// Prompt text for AI nodes.
    /// </summary>
    [JsonPropertyName("prompt")]
    public string? Prompt { get; init; }

    /// <summary>
    /// Condition expression for condition nodes.
    /// </summary>
    [JsonPropertyName("condition")]
    public string? Condition { get; init; }

    /// <summary>
    /// Action scope ID to link (if known).
    /// </summary>
    [JsonPropertyName("actionId")]
    public string? ActionId { get; init; }

    /// <summary>
    /// Skill IDs to link (if known).
    /// </summary>
    [JsonPropertyName("skillIds")]
    public string[]? SkillIds { get; init; }

    /// <summary>
    /// Knowledge source IDs to link (if known).
    /// </summary>
    [JsonPropertyName("knowledgeIds")]
    public string[]? KnowledgeIds { get; init; }

    /// <summary>
    /// Tool IDs to link (if known).
    /// </summary>
    [JsonPropertyName("toolIds")]
    public string[]? ToolIds { get; init; }

    /// <summary>
    /// Additional configuration properties.
    /// </summary>
    [JsonPropertyName("additionalProperties")]
    public Dictionary<string, object>? AdditionalProperties { get; init; }
}

/// <summary>
/// Reference to a scope (Action, Skill, Knowledge, or Tool).
/// </summary>
public record ScopeReference
{
    /// <summary>
    /// Type of scope (action, skill, knowledge, tool).
    /// </summary>
    [JsonPropertyName("type")]
    public required string Type { get; init; }

    /// <summary>
    /// Name of the scope (for search/creation).
    /// </summary>
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    /// <summary>
    /// ID of existing scope (if known).
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// Whether this is an existing scope or needs to be created.
    /// </summary>
    [JsonPropertyName("isExisting")]
    public bool IsExisting { get; init; }

    /// <summary>
    /// Search query to find the scope if ID is not known.
    /// </summary>
    [JsonPropertyName("searchQuery")]
    public string? SearchQuery { get; init; }
}

/// <summary>
/// Specification for an edge to be created.
/// </summary>
public record EdgeSpec
{
    /// <summary>
    /// Reference to the source node (step reference like "step_1" or node ID).
    /// </summary>
    [JsonPropertyName("sourceRef")]
    public required string SourceRef { get; init; }

    /// <summary>
    /// Reference to the target node (step reference like "step_2" or node ID).
    /// </summary>
    [JsonPropertyName("targetRef")]
    public required string TargetRef { get; init; }

    /// <summary>
    /// Label for the edge (e.g., "true", "false" for condition branches).
    /// </summary>
    [JsonPropertyName("label")]
    public string? Label { get; init; }
}

/// <summary>
/// Scope requirements for a playbook build plan.
/// </summary>
public record ScopeRequirements
{
    /// <summary>
    /// Required Action scopes (by name or ID).
    /// </summary>
    [JsonPropertyName("actions")]
    public ScopeRequirement[]? Actions { get; init; }

    /// <summary>
    /// Required Skill scopes (by name or ID).
    /// </summary>
    [JsonPropertyName("skills")]
    public ScopeRequirement[]? Skills { get; init; }

    /// <summary>
    /// Required Knowledge scopes (by name or ID).
    /// </summary>
    [JsonPropertyName("knowledge")]
    public ScopeRequirement[]? Knowledge { get; init; }

    /// <summary>
    /// Required Tool scopes (by name or ID).
    /// </summary>
    [JsonPropertyName("tools")]
    public ScopeRequirement[]? Tools { get; init; }
}

/// <summary>
/// A single scope requirement.
/// </summary>
public record ScopeRequirement
{
    /// <summary>
    /// Name of the required scope.
    /// </summary>
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    /// <summary>
    /// ID if this is an existing scope.
    /// </summary>
    [JsonPropertyName("id")]
    public string? Id { get; init; }

    /// <summary>
    /// Whether this scope exists or needs to be created.
    /// </summary>
    [JsonPropertyName("exists")]
    public bool Exists { get; init; }

    /// <summary>
    /// Reason why this scope is needed.
    /// </summary>
    [JsonPropertyName("reason")]
    public string? Reason { get; init; }
}

/// <summary>
/// Request context for build plan generation.
/// </summary>
public record BuildPlanGenerationContext
{
    /// <summary>
    /// User's description of the playbook they want to build.
    /// </summary>
    [JsonPropertyName("goal")]
    public required string Goal { get; init; }

    /// <summary>
    /// Target document types (optional).
    /// </summary>
    [JsonPropertyName("documentTypes")]
    public string[]? DocumentTypes { get; init; }

    /// <summary>
    /// Matter types for context (optional).
    /// </summary>
    [JsonPropertyName("matterTypes")]
    public string[]? MatterTypes { get; init; }

    /// <summary>
    /// Current canvas state if modifying existing playbook.
    /// </summary>
    [JsonPropertyName("currentCanvas")]
    public CanvasStateSummary? CurrentCanvas { get; init; }

    /// <summary>
    /// Available scopes that can be linked.
    /// </summary>
    [JsonPropertyName("availableScopes")]
    public AvailableScopes? AvailableScopes { get; init; }
}

/// <summary>
/// Summary of current canvas state for build plan context.
/// </summary>
public record CanvasStateSummary
{
    /// <summary>
    /// Number of existing nodes.
    /// </summary>
    [JsonPropertyName("nodeCount")]
    public int NodeCount { get; init; }

    /// <summary>
    /// Number of existing edges.
    /// </summary>
    [JsonPropertyName("edgeCount")]
    public int EdgeCount { get; init; }

    /// <summary>
    /// Brief description of existing canvas structure.
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; init; }

    /// <summary>
    /// List of existing nodes for reference.
    /// </summary>
    [JsonPropertyName("existingNodes")]
    public ExistingNodeSummary[]? ExistingNodes { get; init; }
}

/// <summary>
/// Summary of an existing node for build plan context.
/// </summary>
public record ExistingNodeSummary
{
    /// <summary>
    /// Node ID.
    /// </summary>
    [JsonPropertyName("id")]
    public required string Id { get; init; }

    /// <summary>
    /// Node type.
    /// </summary>
    [JsonPropertyName("type")]
    public required string Type { get; init; }

    /// <summary>
    /// Node label.
    /// </summary>
    [JsonPropertyName("label")]
    public string? Label { get; init; }
}

/// <summary>
/// Available scopes that can be linked in the build plan.
/// </summary>
public record AvailableScopes
{
    /// <summary>
    /// Available Action scopes.
    /// </summary>
    [JsonPropertyName("actions")]
    public AvailableScope[]? Actions { get; init; }

    /// <summary>
    /// Available Skill scopes.
    /// </summary>
    [JsonPropertyName("skills")]
    public AvailableScope[]? Skills { get; init; }

    /// <summary>
    /// Available Knowledge scopes.
    /// </summary>
    [JsonPropertyName("knowledge")]
    public AvailableScope[]? Knowledge { get; init; }

    /// <summary>
    /// Available Tool scopes.
    /// </summary>
    [JsonPropertyName("tools")]
    public AvailableScope[]? Tools { get; init; }
}

/// <summary>
/// An available scope that can be linked.
/// </summary>
public record AvailableScope
{
    /// <summary>
    /// Scope ID.
    /// </summary>
    [JsonPropertyName("id")]
    public required string Id { get; init; }

    /// <summary>
    /// Scope name.
    /// </summary>
    [JsonPropertyName("name")]
    public required string Name { get; init; }

    /// <summary>
    /// Brief description.
    /// </summary>
    [JsonPropertyName("description")]
    public string? Description { get; init; }

    /// <summary>
    /// Applicable document types.
    /// </summary>
    [JsonPropertyName("documentTypes")]
    public string[]? DocumentTypes { get; init; }

    /// <summary>
    /// Tags for matching.
    /// </summary>
    [JsonPropertyName("tags")]
    public string[]? Tags { get; init; }
}

/// <summary>
/// Result of build plan generation.
/// </summary>
public record BuildPlanGenerationResult
{
    /// <summary>
    /// Whether the generation was successful.
    /// </summary>
    [JsonPropertyName("success")]
    public bool Success { get; init; }

    /// <summary>
    /// The generated build plan (if successful).
    /// </summary>
    [JsonPropertyName("plan")]
    public BuildPlan? Plan { get; init; }

    /// <summary>
    /// Error message (if failed).
    /// </summary>
    [JsonPropertyName("error")]
    public string? Error { get; init; }

    /// <summary>
    /// Whether user confirmation is recommended before execution.
    /// </summary>
    [JsonPropertyName("requiresConfirmation")]
    public bool RequiresConfirmation { get; init; }

    /// <summary>
    /// Confirmation message to show user.
    /// </summary>
    [JsonPropertyName("confirmationMessage")]
    public string? ConfirmationMessage { get; init; }

    /// <summary>
    /// Validation warnings (non-blocking issues).
    /// </summary>
    [JsonPropertyName("warnings")]
    public string[]? Warnings { get; init; }

    /// <summary>
    /// Create a successful result.
    /// </summary>
    public static BuildPlanGenerationResult Successful(
        BuildPlan plan,
        bool requiresConfirmation = false,
        string? confirmationMessage = null,
        string[]? warnings = null) => new()
    {
        Success = true,
        Plan = plan,
        RequiresConfirmation = requiresConfirmation,
        ConfirmationMessage = confirmationMessage,
        Warnings = warnings
    };

    /// <summary>
    /// Create a failed result.
    /// </summary>
    public static BuildPlanGenerationResult Failed(string error) => new()
    {
        Success = false,
        Error = error
    };
}

/// <summary>
/// Execution step action types.
/// </summary>
public static class ExecutionStepActions
{
    /// <summary>Add a new node to the canvas.</summary>
    public const string AddNode = "addNode";

    /// <summary>Remove a node from the canvas.</summary>
    public const string RemoveNode = "removeNode";

    /// <summary>Create an edge between two nodes.</summary>
    public const string CreateEdge = "createEdge";

    /// <summary>Remove an edge.</summary>
    public const string RemoveEdge = "removeEdge";

    /// <summary>Link an existing scope to a node.</summary>
    public const string LinkScope = "linkScope";

    /// <summary>Create a new scope in Dataverse.</summary>
    public const string CreateScope = "createScope";

    /// <summary>Update a node's configuration.</summary>
    public const string UpdateConfig = "updateConfig";

    /// <summary>Auto-layout the canvas.</summary>
    public const string AutoLayout = "autoLayout";

    /// <summary>
    /// Validate that an action string is a known action.
    /// </summary>
    public static bool IsValidAction(string action) =>
        action is AddNode or RemoveNode or CreateEdge or RemoveEdge
            or LinkScope or CreateScope or UpdateConfig or AutoLayout;
}

/// <summary>
/// Node types supported by the playbook builder.
/// </summary>
public static class PlaybookNodeTypes
{
    /// <summary>AI-powered document analysis node.</summary>
    public const string AiAnalysis = "aiAnalysis";

    /// <summary>AI text completion node.</summary>
    public const string AiCompletion = "aiCompletion";

    /// <summary>Conditional branching node.</summary>
    public const string Condition = "condition";

    /// <summary>Final output delivery node.</summary>
    public const string DeliverOutput = "deliverOutput";

    /// <summary>Create a Dataverse task record.</summary>
    public const string CreateTask = "createTask";

    /// <summary>Send notification email.</summary>
    public const string SendEmail = "sendEmail";

    /// <summary>Wait/pause execution.</summary>
    public const string Wait = "wait";

    /// <summary>
    /// Validate that a type string is a known node type.
    /// </summary>
    public static bool IsValidNodeType(string type) =>
        type is AiAnalysis or AiCompletion or Condition or DeliverOutput
            or CreateTask or SendEmail or Wait;
}

/// <summary>
/// Scope types for linking.
/// </summary>
public static class ScopeTypes
{
    /// <summary>Action scope (system prompt).</summary>
    public const string Action = "action";

    /// <summary>Skill scope (prompt fragment).</summary>
    public const string Skill = "skill";

    /// <summary>Knowledge scope (RAG source).</summary>
    public const string Knowledge = "knowledge";

    /// <summary>Tool scope (handler).</summary>
    public const string Tool = "tool";

    /// <summary>
    /// Validate that a type string is a known scope type.
    /// </summary>
    public static bool IsValidScopeType(string type) =>
        type is Action or Skill or Knowledge or Tool;
}
