namespace Sprk.Bff.Api.Models.Ai;

/// <summary>
/// Summary of a playbook execution run for history listing.
/// </summary>
public record PlaybookRunSummary
{
    /// <summary>
    /// Unique run identifier.
    /// </summary>
    public Guid RunId { get; init; }

    /// <summary>
    /// Playbook that was executed.
    /// </summary>
    public Guid PlaybookId { get; init; }

    /// <summary>
    /// Current state of the run.
    /// </summary>
    public string State { get; init; } = string.Empty;

    /// <summary>
    /// When the run started.
    /// </summary>
    public DateTimeOffset StartedAt { get; init; }

    /// <summary>
    /// When the run completed (null if still running).
    /// </summary>
    public DateTimeOffset? CompletedAt { get; init; }

    /// <summary>
    /// Total duration in milliseconds.
    /// </summary>
    public long? DurationMs { get; init; }

    /// <summary>
    /// Total number of nodes in the playbook.
    /// </summary>
    public int TotalNodes { get; init; }

    /// <summary>
    /// Number of nodes completed successfully.
    /// </summary>
    public int CompletedNodes { get; init; }

    /// <summary>
    /// Number of nodes that failed.
    /// </summary>
    public int FailedNodes { get; init; }

    /// <summary>
    /// Number of nodes that were skipped.
    /// </summary>
    public int SkippedNodes { get; init; }

    /// <summary>
    /// Total input tokens used.
    /// </summary>
    public int TotalTokensIn { get; init; }

    /// <summary>
    /// Total output tokens generated.
    /// </summary>
    public int TotalTokensOut { get; init; }

    /// <summary>
    /// Error message if the run failed.
    /// </summary>
    public string? ErrorMessage { get; init; }
}

/// <summary>
/// Detailed run information including node-level metrics.
/// </summary>
public record PlaybookRunDetail : PlaybookRunSummary
{
    /// <summary>
    /// Document IDs that were processed.
    /// </summary>
    public Guid[] DocumentIds { get; init; } = [];

    /// <summary>
    /// User-provided context for the run.
    /// </summary>
    public string? UserContext { get; init; }

    /// <summary>
    /// Per-node execution details.
    /// </summary>
    public NodeRunDetail[] NodeDetails { get; init; } = [];
}

/// <summary>
/// Execution details for a single node within a run.
/// </summary>
public record NodeRunDetail
{
    /// <summary>
    /// Node identifier.
    /// </summary>
    public Guid NodeId { get; init; }

    /// <summary>
    /// Node name for display.
    /// </summary>
    public string NodeName { get; init; } = string.Empty;

    /// <summary>
    /// Output variable name.
    /// </summary>
    public string OutputVariable { get; init; } = string.Empty;

    /// <summary>
    /// Whether the node completed successfully.
    /// </summary>
    public bool Success { get; init; }

    /// <summary>
    /// Execution duration in milliseconds.
    /// </summary>
    public long? DurationMs { get; init; }

    /// <summary>
    /// Input tokens used by this node.
    /// </summary>
    public int? TokensIn { get; init; }

    /// <summary>
    /// Output tokens generated by this node.
    /// </summary>
    public int? TokensOut { get; init; }

    /// <summary>
    /// AI confidence score (0.0-1.0) if applicable.
    /// </summary>
    public double? Confidence { get; init; }

    /// <summary>
    /// Error message if the node failed.
    /// </summary>
    public string? ErrorMessage { get; init; }

    /// <summary>
    /// Brief preview of the output (truncated).
    /// </summary>
    public string? OutputPreview { get; init; }
}

/// <summary>
/// Paginated response for run history.
/// </summary>
public record PlaybookRunHistoryResponse
{
    /// <summary>
    /// List of runs.
    /// </summary>
    public PlaybookRunSummary[] Items { get; init; } = [];

    /// <summary>
    /// Total count of runs for this playbook.
    /// </summary>
    public int TotalCount { get; init; }

    /// <summary>
    /// Current page number (1-based).
    /// </summary>
    public int Page { get; init; }

    /// <summary>
    /// Page size.
    /// </summary>
    public int PageSize { get; init; }

    /// <summary>
    /// Total number of pages.
    /// </summary>
    public int TotalPages => (int)Math.Ceiling((double)TotalCount / Math.Max(1, PageSize));

    /// <summary>
    /// Whether there is a next page.
    /// </summary>
    public bool HasNextPage => Page < TotalPages;

    /// <summary>
    /// Whether there is a previous page.
    /// </summary>
    public bool HasPreviousPage => Page > 1;
}

/// <summary>
/// Query parameters for run history.
/// </summary>
public record RunHistoryQueryParameters
{
    /// <summary>
    /// Page number (1-based). Default is 1.
    /// </summary>
    public int Page { get; init; } = 1;

    /// <summary>
    /// Page size. Default is 20, max is 100.
    /// </summary>
    public int PageSize { get; init; } = 20;

    /// <summary>
    /// Filter by run state (e.g., "Completed", "Failed").
    /// </summary>
    public string? StateFilter { get; init; }

    /// <summary>
    /// Filter runs after this date.
    /// </summary>
    public DateTimeOffset? StartedAfter { get; init; }

    /// <summary>
    /// Filter runs before this date.
    /// </summary>
    public DateTimeOffset? StartedBefore { get; init; }

    /// <summary>
    /// Normalize page size to valid range (1-100).
    /// </summary>
    public int GetNormalizedPageSize() => Math.Clamp(PageSize, 1, 100);

    /// <summary>
    /// Get skip count for pagination.
    /// </summary>
    public int GetSkip() => (Math.Max(1, Page) - 1) * GetNormalizedPageSize();
}
